// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const CreateVideoCharacterBodySchema = {
  properties: {
    video: {
      type: 'string',
      format: 'binary',
      description: 'Video file used to create a character.',
    },
    name: {
      type: 'string',
      maxLength: 80,
      minLength: 1,
      description: 'Display name for this API character.',
    },
  },
  type: 'object',
  required: ['video', 'name'],
  title: 'Create character request',
  description: 'Parameters for creating a character from an uploaded video.',
} as const

export const CreateVideoEditJsonBodySchema = {
  properties: {
    video: {
      $ref: '#/$defs/VideoReferenceInputParam',
      description: 'Reference to the completed video to edit.',
    },
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Text prompt that describes how to edit the source video.',
    },
  },
  type: 'object',
  required: ['video', 'prompt'],
  title: 'Create video edit JSON request',
  description: 'JSON parameters for editing an existing generated video.',
  $defs: {
    VideoReferenceInputParam: {
      properties: {
        id: {
          type: 'string',
          description: 'The identifier of the completed video.',
          example: 'video_123',
        },
      },
      type: 'object',
      required: ['id'],
      description: 'Reference to the completed video.',
    },
  },
} as const

export const CreateVideoEditMultipartBodySchema = {
  properties: {
    video: {
      oneOf: [
        {
          type: 'string',
          format: 'binary',
          description: 'Reference to the completed video to edit.',
        },
        { $ref: '#/$defs/VideoReferenceInputParam' },
      ],
    },
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Text prompt that describes how to edit the source video.',
    },
  },
  type: 'object',
  required: ['video', 'prompt'],
  title: 'Create video edit multipart request',
  description: 'Parameters for editing an existing generated video.',
  $defs: {
    VideoReferenceInputParam: {
      properties: {
        id: {
          type: 'string',
          description: 'The identifier of the completed video.',
          example: 'video_123',
        },
      },
      type: 'object',
      required: ['id'],
      description: 'Reference to the completed video.',
    },
  },
} as const

export const CreateVideoExtendJsonBodySchema = {
  properties: {
    video: {
      $ref: '#/$defs/VideoReferenceInputParam',
      description: 'Reference to the completed video to extend.',
    },
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Updated text prompt that directs the extension generation.',
    },
    seconds: {
      $ref: '#/$defs/VideoSeconds',
      description:
        'Length of the newly generated extension segment in seconds (allowed values: 4, 8, 12, 16, 20).',
    },
  },
  type: 'object',
  required: ['video', 'prompt', 'seconds'],
  title: 'Create video extension JSON request',
  description: 'JSON parameters for extending an existing generated video.',
  $defs: {
    VideoReferenceInputParam: {
      properties: {
        id: {
          type: 'string',
          description: 'The identifier of the completed video.',
          example: 'video_123',
        },
      },
      type: 'object',
      required: ['id'],
      description: 'Reference to the completed video.',
    },
    VideoSeconds: { type: 'string', enum: ['4', '8', '12'] },
  },
} as const

export const CreateVideoExtendMultipartBodySchema = {
  properties: {
    video: {
      oneOf: [
        { $ref: '#/$defs/VideoReferenceInputParam' },
        {
          type: 'string',
          format: 'binary',
          description: 'Reference to the completed video to extend.',
        },
      ],
    },
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Updated text prompt that directs the extension generation.',
    },
    seconds: {
      $ref: '#/$defs/VideoSeconds',
      description:
        'Length of the newly generated extension segment in seconds (allowed values: 4, 8, 12, 16, 20).',
    },
  },
  type: 'object',
  required: ['video', 'prompt', 'seconds'],
  title: 'Create video extension multipart request',
  description:
    'Multipart parameters for extending an existing generated video.',
  $defs: {
    VideoReferenceInputParam: {
      properties: {
        id: {
          type: 'string',
          description: 'The identifier of the completed video.',
          example: 'video_123',
        },
      },
      type: 'object',
      required: ['id'],
      description: 'Reference to the completed video.',
    },
    VideoSeconds: { type: 'string', enum: ['4', '8', '12'] },
  },
} as const

export const CreateVideoJsonBodySchema = {
  properties: {
    model: {
      $ref: '#/$defs/VideoModel',
      description:
        'The video generation model to use (allowed values: sora-2, sora-2-pro). Defaults to `sora-2`.',
    },
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Text prompt that describes the video to generate.',
    },
    input_reference: {
      $ref: '#/$defs/ImageRefParam-2',
      description:
        'Optional reference object that guides generation. Provide exactly one of `image_url` or `file_id`.',
    },
    seconds: {
      $ref: '#/$defs/VideoSeconds',
      description:
        'Clip duration in seconds (allowed values: 4, 8, 12). Defaults to 4 seconds.',
    },
    size: {
      $ref: '#/$defs/VideoSize',
      description:
        'Output resolution formatted as width x height (allowed values: 720x1280, 1280x720, 1024x1792, 1792x1024). Defaults to 720x1280.',
    },
  },
  type: 'object',
  required: ['prompt'],
  title: 'Create video JSON request',
  description: 'JSON parameters for creating a new video generation job.',
  $defs: {
    'ImageRefParam-2': {
      properties: {
        image_url: {
          type: 'string',
          maxLength: 20971520,
          format: 'uri',
          description: 'A fully qualified URL or base64-encoded data URL.',
        },
        file_id: { type: 'string', example: 'file-123' },
      },
      type: 'object',
      required: [],
    },
    VideoModel: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'sora-2',
            'sora-2-pro',
            'sora-2-2025-10-06',
            'sora-2-pro-2025-10-06',
            'sora-2-2025-12-08',
          ],
        },
      ],
    },
    VideoSeconds: { type: 'string', enum: ['4', '8', '12'] },
    VideoSize: {
      type: 'string',
      enum: ['720x1280', '1280x720', '1024x1792', '1792x1024'],
    },
  },
} as const

export const CreateVideoMultipartBodySchema = {
  properties: {
    model: {
      $ref: '#/$defs/VideoModel',
      description:
        'The video generation model to use (allowed values: sora-2, sora-2-pro). Defaults to `sora-2`.',
    },
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Text prompt that describes the video to generate.',
    },
    input_reference: {
      oneOf: [
        {
          type: 'string',
          format: 'binary',
          description:
            'Optional reference asset upload or reference object that guides generation.',
        },
        { $ref: '#/$defs/ImageRefParam-2' },
      ],
    },
    seconds: {
      $ref: '#/$defs/VideoSeconds',
      description:
        'Clip duration in seconds (allowed values: 4, 8, 12). Defaults to 4 seconds.',
    },
    size: {
      $ref: '#/$defs/VideoSize',
      description:
        'Output resolution formatted as width x height (allowed values: 720x1280, 1280x720, 1024x1792, 1792x1024). Defaults to 720x1280.',
    },
  },
  type: 'object',
  required: ['prompt'],
  title: 'Create video multipart request',
  description: 'Multipart parameters for creating a new video generation job.',
  $defs: {
    'ImageRefParam-2': {
      properties: {
        image_url: {
          type: 'string',
          maxLength: 20971520,
          format: 'uri',
          description: 'A fully qualified URL or base64-encoded data URL.',
        },
        file_id: { type: 'string', example: 'file-123' },
      },
      type: 'object',
      required: [],
    },
    VideoModel: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'sora-2',
            'sora-2-pro',
            'sora-2-2025-10-06',
            'sora-2-pro-2025-10-06',
            'sora-2-2025-12-08',
          ],
        },
      ],
    },
    VideoSeconds: { type: 'string', enum: ['4', '8', '12'] },
    VideoSize: {
      type: 'string',
      enum: ['720x1280', '1280x720', '1024x1792', '1792x1024'],
    },
  },
} as const

export const CreateVideoRemixBodySchema = {
  properties: {
    prompt: {
      type: 'string',
      maxLength: 32000,
      minLength: 1,
      description: 'Updated text prompt that directs the remix generation.',
    },
  },
  type: 'object',
  required: ['prompt'],
  title: 'Create video remix request',
  description: 'Parameters for remixing an existing generated video.',
} as const

export const Error_2Schema = {
  properties: {
    code: {
      type: 'string',
      description: 'A machine-readable error code that was returned.',
    },
    message: {
      type: 'string',
      description:
        'A human-readable description of the error that was returned.',
    },
  },
  type: 'object',
  required: ['code', 'message'],
  title: 'Error',
  description: 'An error that occurred while generating the response.',
} as const

export const ImageRefParam_2Schema = {
  properties: {
    image_url: {
      type: 'string',
      maxLength: 20971520,
      format: 'uri',
      description: 'A fully qualified URL or base64-encoded data URL.',
    },
    file_id: { type: 'string', example: 'file-123' },
  },
  type: 'object',
  required: [],
} as const

export const VideoCharacterResourceSchema = {
  properties: {
    id: {
      anyOf: [
        {
          type: 'string',
          description: 'Identifier for the character creation cameo.',
        },
        { type: 'null' },
      ],
    },
    name: {
      anyOf: [
        { type: 'string', description: 'Display name for the character.' },
        { type: 'null' },
      ],
    },
    created_at: {
      type: 'integer',
      format: 'unixtime',
      description:
        'Unix timestamp (in seconds) when the character was created.',
    },
  },
  type: 'object',
  required: ['id', 'name', 'created_at'],
} as const

export const VideoModelSchema = {
  anyOf: [
    { type: 'string' },
    {
      type: 'string',
      enum: [
        'sora-2',
        'sora-2-pro',
        'sora-2-2025-10-06',
        'sora-2-pro-2025-10-06',
        'sora-2-2025-12-08',
      ],
    },
  ],
} as const

export const VideoReferenceInputParamSchema = {
  properties: {
    id: {
      type: 'string',
      description: 'The identifier of the completed video.',
      example: 'video_123',
    },
  },
  type: 'object',
  required: ['id'],
  description: 'Reference to the completed video.',
} as const

export const VideoResourceSchema = {
  properties: {
    id: { type: 'string', description: 'Unique identifier for the video job.' },
    object: {
      type: 'string',
      enum: ['video'],
      description: 'The object type, which is always `video`.',
      default: 'video',
      'x-stainless-const': true,
    },
    model: {
      $ref: '#/$defs/VideoModel',
      description: 'The video generation model that produced the job.',
    },
    status: {
      $ref: '#/$defs/VideoStatus',
      description: 'Current lifecycle status of the video job.',
    },
    progress: {
      type: 'integer',
      description: 'Approximate completion percentage for the generation task.',
    },
    created_at: {
      type: 'integer',
      format: 'unixtime',
      description: 'Unix timestamp (seconds) for when the job was created.',
    },
    completed_at: {
      anyOf: [
        {
          type: 'integer',
          format: 'unixtime',
          description:
            'Unix timestamp (seconds) for when the job completed, if finished.',
        },
        { type: 'null' },
      ],
    },
    expires_at: {
      anyOf: [
        {
          type: 'integer',
          format: 'unixtime',
          description:
            'Unix timestamp (seconds) for when the downloadable assets expire, if set.',
        },
        { type: 'null' },
      ],
    },
    prompt: {
      anyOf: [
        {
          type: 'string',
          description: 'The prompt that was used to generate the video.',
        },
        { type: 'null' },
      ],
    },
    size: {
      $ref: '#/$defs/VideoSize',
      description: 'The resolution of the generated video.',
    },
    seconds: {
      type: 'string',
      description:
        'Duration of the generated clip in seconds. For extensions, this is the stitched total duration.',
    },
    remixed_from_video_id: {
      anyOf: [
        {
          type: 'string',
          description:
            'Identifier of the source video if this video is a remix.',
        },
        { type: 'null' },
      ],
    },
    error: {
      anyOf: [
        {
          $ref: '#/$defs/Error-2',
          description:
            'Error payload that explains why generation failed, if applicable.',
        },
        { type: 'null' },
      ],
    },
  },
  type: 'object',
  required: [
    'id',
    'object',
    'model',
    'status',
    'progress',
    'created_at',
    'completed_at',
    'expires_at',
    'prompt',
    'size',
    'seconds',
    'remixed_from_video_id',
    'error',
  ],
  title: 'Video job',
  description: 'Structured information describing a generated video job.',
  $defs: {
    'Error-2': {
      properties: {
        code: {
          type: 'string',
          description: 'A machine-readable error code that was returned.',
        },
        message: {
          type: 'string',
          description:
            'A human-readable description of the error that was returned.',
        },
      },
      type: 'object',
      required: ['code', 'message'],
      title: 'Error',
      description: 'An error that occurred while generating the response.',
    },
    VideoModel: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'sora-2',
            'sora-2-pro',
            'sora-2-2025-10-06',
            'sora-2-pro-2025-10-06',
            'sora-2-2025-12-08',
          ],
        },
      ],
    },
    VideoSize: {
      type: 'string',
      enum: ['720x1280', '1280x720', '1024x1792', '1792x1024'],
    },
    VideoStatus: {
      type: 'string',
      enum: ['queued', 'in_progress', 'completed', 'failed'],
    },
  },
} as const

export const VideoSecondsSchema = {
  type: 'string',
  enum: ['4', '8', '12'],
} as const

export const VideoSizeSchema = {
  type: 'string',
  enum: ['720x1280', '1280x720', '1024x1792', '1792x1024'],
} as const

export const VideoStatusSchema = {
  type: 'string',
  enum: ['queued', 'in_progress', 'completed', 'failed'],
} as const
