// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Create character request
 *
 * Parameters for creating a character from an uploaded video.
 */
export const zCreateVideoCharacterBody = z.object({
  video: z.string(),
  name: z.string().min(1).max(80),
})

/**
 * Create video remix request
 *
 * Parameters for remixing an existing generated video.
 */
export const zCreateVideoRemixBody = z.object({
  prompt: z.string().min(1).max(32000),
})

/**
 * Error
 *
 * An error that occurred while generating the response.
 */
export const zError2 = z.object({
  code: z.string(),
  message: z.string(),
})

export const zImageRefParam2 = z.object({
  image_url: z.url().max(20971520).optional(),
  file_id: z.string().optional(),
})

export const zVideoCharacterResource = z.object({
  id: z.union([z.string(), z.unknown()]),
  name: z.union([z.string(), z.unknown()]),
  created_at: z.int(),
})

export const zVideoModel = z.union([
  z.string(),
  z.enum([
    'sora-2',
    'sora-2-pro',
    'sora-2-2025-10-06',
    'sora-2-pro-2025-10-06',
    'sora-2-2025-12-08',
  ]),
])

/**
 * Reference to the completed video.
 */
export const zVideoReferenceInputParam = z.object({
  id: z.string(),
})

/**
 * Create video edit JSON request
 *
 * JSON parameters for editing an existing generated video.
 */
export const zCreateVideoEditJsonBody = z.object({
  video: zVideoReferenceInputParam,
  prompt: z.string().min(1).max(32000),
})

/**
 * Create video edit multipart request
 *
 * Parameters for editing an existing generated video.
 */
export const zCreateVideoEditMultipartBody = z.object({
  video: z.union([z.string(), zVideoReferenceInputParam]),
  prompt: z.string().min(1).max(32000),
})

export const zVideoSeconds = z.enum(['4', '8', '12'])

/**
 * Create video extension JSON request
 *
 * JSON parameters for extending an existing generated video.
 */
export const zCreateVideoExtendJsonBody = z.object({
  video: zVideoReferenceInputParam,
  prompt: z.string().min(1).max(32000),
  seconds: zVideoSeconds,
})

/**
 * Create video extension multipart request
 *
 * Multipart parameters for extending an existing generated video.
 */
export const zCreateVideoExtendMultipartBody = z.object({
  video: z.union([zVideoReferenceInputParam, z.string()]),
  prompt: z.string().min(1).max(32000),
  seconds: zVideoSeconds,
})

export const zVideoSize = z.enum([
  '720x1280',
  '1280x720',
  '1024x1792',
  '1792x1024',
])

/**
 * Create video JSON request
 *
 * JSON parameters for creating a new video generation job.
 */
export const zCreateVideoJsonBody = z.object({
  model: zVideoModel.optional(),
  prompt: z.string().min(1).max(32000),
  input_reference: zImageRefParam2.optional(),
  seconds: zVideoSeconds.optional(),
  size: zVideoSize.optional(),
})

/**
 * Create video multipart request
 *
 * Multipart parameters for creating a new video generation job.
 */
export const zCreateVideoMultipartBody = z.object({
  model: zVideoModel.optional(),
  prompt: z.string().min(1).max(32000),
  input_reference: z.union([z.string(), zImageRefParam2]).optional(),
  seconds: zVideoSeconds.optional(),
  size: zVideoSize.optional(),
})

export const zVideoStatus = z.enum([
  'queued',
  'in_progress',
  'completed',
  'failed',
])

/**
 * Video job
 *
 * Structured information describing a generated video job.
 */
export const zVideoResource = z.object({
  id: z.string(),
  object: z.enum(['video']).default('video'),
  model: zVideoModel,
  status: zVideoStatus,
  progress: z.int(),
  created_at: z.int(),
  completed_at: z.union([z.int(), z.unknown()]),
  expires_at: z.union([z.int(), z.unknown()]),
  prompt: z.union([z.string(), z.unknown()]),
  size: zVideoSize,
  seconds: z.string(),
  remixed_from_video_id: z.union([z.string(), z.unknown()]),
  error: z.union([zError2, z.unknown()]),
})

export const zCreateVideoBody = zCreateVideoJsonBody

/**
 * Success
 */
export const zCreateVideoResponse = zVideoResource

export const zCreateVideoRemixBody2 = zCreateVideoRemixBody

export const zCreateVideoRemixPath = z.object({
  video_id: z.string(),
})

/**
 * Success
 */
export const zCreateVideoRemixResponse = zVideoResource

export const zCreateVideoCharacterBody2 = zCreateVideoCharacterBody

/**
 * Success
 */
export const zCreateVideoCharacterResponse = zVideoCharacterResource

export const zCreateVideoEditBody = zCreateVideoEditJsonBody

/**
 * Success
 */
export const zCreateVideoEditResponse = zVideoResource

export const zCreateVideoExtendBody = zCreateVideoExtendJsonBody

/**
 * Success
 */
export const zCreateVideoExtendResponse = zVideoResource
