/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuredOutputRouteImport } from './routes/structured-output'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ReportingAgentRouteImport } from './routes/reporting-agent'
import { Route as ProductDemoRouteImport } from './routes/product-demo'
import { Route as NoCodeRouteImport } from './routes/no-code'
import { Route as ExcalidrawDemoRouteImport } from './routes/excalidraw-demo'
import { Route as BankingDemoRouteImport } from './routes/banking-demo'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsDemoRouteImport } from './routes/reports/demo'
import { Route as ApiStructuredOutputRouteImport } from './routes/api.structured-output'
import { Route as ApiSkillsRouteImport } from './routes/api.skills'
import { Route as ApiReportsRouteImport } from './routes/api.reports'
import { Route as ApiReportSseRouteImport } from './routes/api.report-sse'
import { Route as ApiReportEventRouteImport } from './routes/api.report-event'
import { Route as ApiReportDemoRouteImport } from './routes/api.report-demo'
import { Route as ApiProductRegularRouteImport } from './routes/api.product-regular'
import { Route as ApiProductCodemodeRouteImport } from './routes/api.product-codemode'
import { Route as ApiNoCodeRouteImport } from './routes/api.no-code'
import { Route as ApiInvalidateRouteImport } from './routes/api.invalidate'
import { Route as ApiGeneratePdfRouteImport } from './routes/api.generate-pdf'
import { Route as ApiExcalidrawInitRouteImport } from './routes/api.excalidraw-init'
import { Route as ApiExcalidrawDemoRouteImport } from './routes/api.excalidraw-demo'
import { Route as ApiCodemodeSkillsRouteImport } from './routes/api.codemode-skills'
import { Route as ApiCodemodeRouteImport } from './routes/api.codemode'
import { Route as ApiBankingInitRouteImport } from './routes/api.banking-init'
import { Route as ApiBankingDemoRouteImport } from './routes/api.banking-demo'
import { Route as ApiAudioResolveRouteImport } from './routes/api.audio-resolve'
import { Route as ApiAudioRouteImport } from './routes/api.audio'

const StructuredOutputRoute = StructuredOutputRouteImport.update({
  id: '/structured-output',
  path: '/structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingAgentRoute = ReportingAgentRouteImport.update({
  id: '/reporting-agent',
  path: '/reporting-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDemoRoute = ProductDemoRouteImport.update({
  id: '/product-demo',
  path: '/product-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const NoCodeRoute = NoCodeRouteImport.update({
  id: '/no-code',
  path: '/no-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcalidrawDemoRoute = ExcalidrawDemoRouteImport.update({
  id: '/excalidraw-demo',
  path: '/excalidraw-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingDemoRoute = BankingDemoRouteImport.update({
  id: '/banking-demo',
  path: '/banking-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDemoRoute = ReportsDemoRouteImport.update({
  id: '/reports/demo',
  path: '/reports/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStructuredOutputRoute = ApiStructuredOutputRouteImport.update({
  id: '/api/structured-output',
  path: '/api/structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportSseRoute = ApiReportSseRouteImport.update({
  id: '/api/report-sse',
  path: '/api/report-sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportEventRoute = ApiReportEventRouteImport.update({
  id: '/api/report-event',
  path: '/api/report-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportDemoRoute = ApiReportDemoRouteImport.update({
  id: '/api/report-demo',
  path: '/api/report-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductRegularRoute = ApiProductRegularRouteImport.update({
  id: '/api/product-regular',
  path: '/api/product-regular',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductCodemodeRoute = ApiProductCodemodeRouteImport.update({
  id: '/api/product-codemode',
  path: '/api/product-codemode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoCodeRoute = ApiNoCodeRouteImport.update({
  id: '/api/no-code',
  path: '/api/no-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvalidateRoute = ApiInvalidateRouteImport.update({
  id: '/api/invalidate',
  path: '/api/invalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePdfRoute = ApiGeneratePdfRouteImport.update({
  id: '/api/generate-pdf',
  path: '/api/generate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExcalidrawInitRoute = ApiExcalidrawInitRouteImport.update({
  id: '/api/excalidraw-init',
  path: '/api/excalidraw-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExcalidrawDemoRoute = ApiExcalidrawDemoRouteImport.update({
  id: '/api/excalidraw-demo',
  path: '/api/excalidraw-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodemodeSkillsRoute = ApiCodemodeSkillsRouteImport.update({
  id: '/api/codemode-skills',
  path: '/api/codemode-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodemodeRoute = ApiCodemodeRouteImport.update({
  id: '/api/codemode',
  path: '/api/codemode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBankingInitRoute = ApiBankingInitRouteImport.update({
  id: '/api/banking-init',
  path: '/api/banking-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBankingDemoRoute = ApiBankingDemoRouteImport.update({
  id: '/api/banking-demo',
  path: '/api/banking-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioResolveRoute = ApiAudioResolveRouteImport.update({
  id: '/api/audio-resolve',
  path: '/api/audio-resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/banking-demo': typeof BankingDemoRoute
  '/excalidraw-demo': typeof ExcalidrawDemoRoute
  '/no-code': typeof NoCodeRoute
  '/product-demo': typeof ProductDemoRoute
  '/reporting-agent': typeof ReportingAgentRoute
  '/skills': typeof SkillsRoute
  '/structured-output': typeof StructuredOutputRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/audio-resolve': typeof ApiAudioResolveRoute
  '/api/banking-demo': typeof ApiBankingDemoRoute
  '/api/banking-init': typeof ApiBankingInitRoute
  '/api/codemode': typeof ApiCodemodeRoute
  '/api/codemode-skills': typeof ApiCodemodeSkillsRoute
  '/api/excalidraw-demo': typeof ApiExcalidrawDemoRoute
  '/api/excalidraw-init': typeof ApiExcalidrawInitRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/invalidate': typeof ApiInvalidateRoute
  '/api/no-code': typeof ApiNoCodeRoute
  '/api/product-codemode': typeof ApiProductCodemodeRoute
  '/api/product-regular': typeof ApiProductRegularRoute
  '/api/report-demo': typeof ApiReportDemoRoute
  '/api/report-event': typeof ApiReportEventRoute
  '/api/report-sse': typeof ApiReportSseRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/skills': typeof ApiSkillsRoute
  '/api/structured-output': typeof ApiStructuredOutputRoute
  '/reports/demo': typeof ReportsDemoRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/banking-demo': typeof BankingDemoRoute
  '/excalidraw-demo': typeof ExcalidrawDemoRoute
  '/no-code': typeof NoCodeRoute
  '/product-demo': typeof ProductDemoRoute
  '/reporting-agent': typeof ReportingAgentRoute
  '/skills': typeof SkillsRoute
  '/structured-output': typeof StructuredOutputRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/audio-resolve': typeof ApiAudioResolveRoute
  '/api/banking-demo': typeof ApiBankingDemoRoute
  '/api/banking-init': typeof ApiBankingInitRoute
  '/api/codemode': typeof ApiCodemodeRoute
  '/api/codemode-skills': typeof ApiCodemodeSkillsRoute
  '/api/excalidraw-demo': typeof ApiExcalidrawDemoRoute
  '/api/excalidraw-init': typeof ApiExcalidrawInitRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/invalidate': typeof ApiInvalidateRoute
  '/api/no-code': typeof ApiNoCodeRoute
  '/api/product-codemode': typeof ApiProductCodemodeRoute
  '/api/product-regular': typeof ApiProductRegularRoute
  '/api/report-demo': typeof ApiReportDemoRoute
  '/api/report-event': typeof ApiReportEventRoute
  '/api/report-sse': typeof ApiReportSseRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/skills': typeof ApiSkillsRoute
  '/api/structured-output': typeof ApiStructuredOutputRoute
  '/reports/demo': typeof ReportsDemoRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/banking-demo': typeof BankingDemoRoute
  '/excalidraw-demo': typeof ExcalidrawDemoRoute
  '/no-code': typeof NoCodeRoute
  '/product-demo': typeof ProductDemoRoute
  '/reporting-agent': typeof ReportingAgentRoute
  '/skills': typeof SkillsRoute
  '/structured-output': typeof StructuredOutputRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/audio-resolve': typeof ApiAudioResolveRoute
  '/api/banking-demo': typeof ApiBankingDemoRoute
  '/api/banking-init': typeof ApiBankingInitRoute
  '/api/codemode': typeof ApiCodemodeRoute
  '/api/codemode-skills': typeof ApiCodemodeSkillsRoute
  '/api/excalidraw-demo': typeof ApiExcalidrawDemoRoute
  '/api/excalidraw-init': typeof ApiExcalidrawInitRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/invalidate': typeof ApiInvalidateRoute
  '/api/no-code': typeof ApiNoCodeRoute
  '/api/product-codemode': typeof ApiProductCodemodeRoute
  '/api/product-regular': typeof ApiProductRegularRoute
  '/api/report-demo': typeof ApiReportDemoRoute
  '/api/report-event': typeof ApiReportEventRoute
  '/api/report-sse': typeof ApiReportSseRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/skills': typeof ApiSkillsRoute
  '/api/structured-output': typeof ApiStructuredOutputRoute
  '/reports/demo': typeof ReportsDemoRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/banking-demo'
    | '/excalidraw-demo'
    | '/no-code'
    | '/product-demo'
    | '/reporting-agent'
    | '/skills'
    | '/structured-output'
    | '/api/audio'
    | '/api/audio-resolve'
    | '/api/banking-demo'
    | '/api/banking-init'
    | '/api/codemode'
    | '/api/codemode-skills'
    | '/api/excalidraw-demo'
    | '/api/excalidraw-init'
    | '/api/generate-pdf'
    | '/api/invalidate'
    | '/api/no-code'
    | '/api/product-codemode'
    | '/api/product-regular'
    | '/api/report-demo'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/skills'
    | '/api/structured-output'
    | '/reports/demo'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/banking-demo'
    | '/excalidraw-demo'
    | '/no-code'
    | '/product-demo'
    | '/reporting-agent'
    | '/skills'
    | '/structured-output'
    | '/api/audio'
    | '/api/audio-resolve'
    | '/api/banking-demo'
    | '/api/banking-init'
    | '/api/codemode'
    | '/api/codemode-skills'
    | '/api/excalidraw-demo'
    | '/api/excalidraw-init'
    | '/api/generate-pdf'
    | '/api/invalidate'
    | '/api/no-code'
    | '/api/product-codemode'
    | '/api/product-regular'
    | '/api/report-demo'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/skills'
    | '/api/structured-output'
    | '/reports/demo'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/banking-demo'
    | '/excalidraw-demo'
    | '/no-code'
    | '/product-demo'
    | '/reporting-agent'
    | '/skills'
    | '/structured-output'
    | '/api/audio'
    | '/api/audio-resolve'
    | '/api/banking-demo'
    | '/api/banking-init'
    | '/api/codemode'
    | '/api/codemode-skills'
    | '/api/excalidraw-demo'
    | '/api/excalidraw-init'
    | '/api/generate-pdf'
    | '/api/invalidate'
    | '/api/no-code'
    | '/api/product-codemode'
    | '/api/product-regular'
    | '/api/report-demo'
    | '/api/report-event'
    | '/api/report-sse'
    | '/api/reports'
    | '/api/skills'
    | '/api/structured-output'
    | '/reports/demo'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  BankingDemoRoute: typeof BankingDemoRoute
  ExcalidrawDemoRoute: typeof ExcalidrawDemoRoute
  NoCodeRoute: typeof NoCodeRoute
  ProductDemoRoute: typeof ProductDemoRoute
  ReportingAgentRoute: typeof ReportingAgentRoute
  SkillsRoute: typeof SkillsRoute
  StructuredOutputRoute: typeof StructuredOutputRoute
  ApiAudioRoute: typeof ApiAudioRoute
  ApiAudioResolveRoute: typeof ApiAudioResolveRoute
  ApiBankingDemoRoute: typeof ApiBankingDemoRoute
  ApiBankingInitRoute: typeof ApiBankingInitRoute
  ApiCodemodeRoute: typeof ApiCodemodeRoute
  ApiCodemodeSkillsRoute: typeof ApiCodemodeSkillsRoute
  ApiExcalidrawDemoRoute: typeof ApiExcalidrawDemoRoute
  ApiExcalidrawInitRoute: typeof ApiExcalidrawInitRoute
  ApiGeneratePdfRoute: typeof ApiGeneratePdfRoute
  ApiInvalidateRoute: typeof ApiInvalidateRoute
  ApiNoCodeRoute: typeof ApiNoCodeRoute
  ApiProductCodemodeRoute: typeof ApiProductCodemodeRoute
  ApiProductRegularRoute: typeof ApiProductRegularRoute
  ApiReportDemoRoute: typeof ApiReportDemoRoute
  ApiReportEventRoute: typeof ApiReportEventRoute
  ApiReportSseRoute: typeof ApiReportSseRoute
  ApiReportsRoute: typeof ApiReportsRoute
  ApiSkillsRoute: typeof ApiSkillsRoute
  ApiStructuredOutputRoute: typeof ApiStructuredOutputRoute
  ReportsDemoRoute: typeof ReportsDemoRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structured-output': {
      id: '/structured-output'
      path: '/structured-output'
      fullPath: '/structured-output'
      preLoaderRoute: typeof StructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting-agent': {
      id: '/reporting-agent'
      path: '/reporting-agent'
      fullPath: '/reporting-agent'
      preLoaderRoute: typeof ReportingAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-demo': {
      id: '/product-demo'
      path: '/product-demo'
      fullPath: '/product-demo'
      preLoaderRoute: typeof ProductDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-code': {
      id: '/no-code'
      path: '/no-code'
      fullPath: '/no-code'
      preLoaderRoute: typeof NoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excalidraw-demo': {
      id: '/excalidraw-demo'
      path: '/excalidraw-demo'
      fullPath: '/excalidraw-demo'
      preLoaderRoute: typeof ExcalidrawDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking-demo': {
      id: '/banking-demo'
      path: '/banking-demo'
      fullPath: '/banking-demo'
      preLoaderRoute: typeof BankingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/demo': {
      id: '/reports/demo'
      path: '/reports/demo'
      fullPath: '/reports/demo'
      preLoaderRoute: typeof ReportsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/structured-output': {
      id: '/api/structured-output'
      path: '/api/structured-output'
      fullPath: '/api/structured-output'
      preLoaderRoute: typeof ApiStructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-sse': {
      id: '/api/report-sse'
      path: '/api/report-sse'
      fullPath: '/api/report-sse'
      preLoaderRoute: typeof ApiReportSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-event': {
      id: '/api/report-event'
      path: '/api/report-event'
      fullPath: '/api/report-event'
      preLoaderRoute: typeof ApiReportEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-demo': {
      id: '/api/report-demo'
      path: '/api/report-demo'
      fullPath: '/api/report-demo'
      preLoaderRoute: typeof ApiReportDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-regular': {
      id: '/api/product-regular'
      path: '/api/product-regular'
      fullPath: '/api/product-regular'
      preLoaderRoute: typeof ApiProductRegularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-codemode': {
      id: '/api/product-codemode'
      path: '/api/product-codemode'
      fullPath: '/api/product-codemode'
      preLoaderRoute: typeof ApiProductCodemodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/no-code': {
      id: '/api/no-code'
      path: '/api/no-code'
      fullPath: '/api/no-code'
      preLoaderRoute: typeof ApiNoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invalidate': {
      id: '/api/invalidate'
      path: '/api/invalidate'
      fullPath: '/api/invalidate'
      preLoaderRoute: typeof ApiInvalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-pdf': {
      id: '/api/generate-pdf'
      path: '/api/generate-pdf'
      fullPath: '/api/generate-pdf'
      preLoaderRoute: typeof ApiGeneratePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/excalidraw-init': {
      id: '/api/excalidraw-init'
      path: '/api/excalidraw-init'
      fullPath: '/api/excalidraw-init'
      preLoaderRoute: typeof ApiExcalidrawInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/excalidraw-demo': {
      id: '/api/excalidraw-demo'
      path: '/api/excalidraw-demo'
      fullPath: '/api/excalidraw-demo'
      preLoaderRoute: typeof ApiExcalidrawDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codemode-skills': {
      id: '/api/codemode-skills'
      path: '/api/codemode-skills'
      fullPath: '/api/codemode-skills'
      preLoaderRoute: typeof ApiCodemodeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codemode': {
      id: '/api/codemode'
      path: '/api/codemode'
      fullPath: '/api/codemode'
      preLoaderRoute: typeof ApiCodemodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/banking-init': {
      id: '/api/banking-init'
      path: '/api/banking-init'
      fullPath: '/api/banking-init'
      preLoaderRoute: typeof ApiBankingInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/banking-demo': {
      id: '/api/banking-demo'
      path: '/api/banking-demo'
      fullPath: '/api/banking-demo'
      preLoaderRoute: typeof ApiBankingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio-resolve': {
      id: '/api/audio-resolve'
      path: '/api/audio-resolve'
      fullPath: '/api/audio-resolve'
      preLoaderRoute: typeof ApiAudioResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  BankingDemoRoute: BankingDemoRoute,
  ExcalidrawDemoRoute: ExcalidrawDemoRoute,
  NoCodeRoute: NoCodeRoute,
  ProductDemoRoute: ProductDemoRoute,
  ReportingAgentRoute: ReportingAgentRoute,
  SkillsRoute: SkillsRoute,
  StructuredOutputRoute: StructuredOutputRoute,
  ApiAudioRoute: ApiAudioRoute,
  ApiAudioResolveRoute: ApiAudioResolveRoute,
  ApiBankingDemoRoute: ApiBankingDemoRoute,
  ApiBankingInitRoute: ApiBankingInitRoute,
  ApiCodemodeRoute: ApiCodemodeRoute,
  ApiCodemodeSkillsRoute: ApiCodemodeSkillsRoute,
  ApiExcalidrawDemoRoute: ApiExcalidrawDemoRoute,
  ApiExcalidrawInitRoute: ApiExcalidrawInitRoute,
  ApiGeneratePdfRoute: ApiGeneratePdfRoute,
  ApiInvalidateRoute: ApiInvalidateRoute,
  ApiNoCodeRoute: ApiNoCodeRoute,
  ApiProductCodemodeRoute: ApiProductCodemodeRoute,
  ApiProductRegularRoute: ApiProductRegularRoute,
  ApiReportDemoRoute: ApiReportDemoRoute,
  ApiReportEventRoute: ApiReportEventRoute,
  ApiReportSseRoute: ApiReportSseRoute,
  ApiReportsRoute: ApiReportsRoute,
  ApiSkillsRoute: ApiSkillsRoute,
  ApiStructuredOutputRoute: ApiStructuredOutputRoute,
  ReportsDemoRoute: ReportsDemoRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
