import { defineConfig } from 'kiira-core'

export default defineConfig({
  include: ['docs/**/*.md'],
  exclude: [
    // docs/reference/** is auto-generated by TypeDoc (`pnpm generate-docs`);
    // hand-fixing those snippets would be overwritten on regeneration.
    'docs/reference/**',
    // @tanstack/ai-angular is an ng-packagr bundle: its only published entry
    // is dist/types/*.d.ts, which kiira's dist->src heuristic can't map back
    // to a source file (unlike every other package's dist/esm/index.d.ts ->
    // src/index.ts). So these docs only resolve against the built package,
    // which isn't available during a source-based docs check. Excluded until
    // ai-angular exposes a source-resolvable entry.
    'docs/api/ai-angular.md',
    'docs/getting-started/quick-start-angular.md',
  ],
  defaultValidate: 'type',
  languages: ['ts', 'tsx', 'js', 'jsx'],
  overrides: [
    // React (and anything not overridden below) uses the automatic JSX
    // runtime so snippets don't need an explicit `import React`.
    // noImplicitReturns is off: doc snippets routinely show callbacks that
    // return on some branches and fall through on others (e.g. a middleware
    // hook that returns a decision or continues), which is valid and shouldn't
    // force an explicit return type or trailing `return`.
    {
      include: ['docs/**/*.md'],
      jsx: 'react-jsx',
      jsxImportSource: 'react',
      noImplicitReturns: false,
    },
    // Solid snippets compile JSX through solid-js.
    {
      include: ['docs/api/ai-solid.md'],
      jsx: 'preserve',
      jsxImportSource: 'solid-js',
    },
    // Preact snippets compile JSX through preact.
    {
      include: ['docs/api/ai-preact.md'],
      jsx: 'react-jsx',
      jsxImportSource: 'preact',
    },
  ],
})
