import { defineConfig } from "kiira-core"

export default defineConfig({
	include: ["docs/**/*.md"],
	// docs/reference/** is auto-generated by TypeDoc (`pnpm generate-docs`);
	// hand-fixing those snippets would be overwritten on regeneration.
	exclude: ["docs/reference/**"],
	defaultValidate: "type",
	languages: ["ts", "tsx", "js", "jsx"],
	fixtures: {
		// Invisible setup for fragment snippets that reference the illustrative
		// `messages` / `message` values without re-declaring them inline. Applied
		// per-fence with `fixture=ambient`; the prepended lines are type-checked
		// but not rendered in the docs.
		ambient: {
			type: "prepend",
			content: [
				'import type { ModelMessage, UIMessage } from "@tanstack/ai"',
				"declare const messages: Array<ModelMessage>",
				"declare const message: UIMessage",
			].join("\n"),
		},
	},
	overrides: [
		// React (and anything not overridden below) uses the automatic JSX
		// runtime so snippets don't need an explicit `import React`.
		{ include: ["docs/**/*.md"], jsx: "react-jsx", jsxImportSource: "react" },
		// Solid snippets compile JSX through solid-js.
		{
			include: ["docs/api/ai-solid.md"],
			jsx: "preserve",
			jsxImportSource: "solid-js",
		},
		// Preact snippets compile JSX through preact.
		{
			include: ["docs/api/ai-preact.md"],
			jsx: "react-jsx",
			jsxImportSource: "preact",
		},
	],
})
