cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - 'packages/typescript/*'
  - 'packages/typescript/ai-code-mode/models-eval'
  - 'examples/*'
  - 'testing/*'

allowBuilds:
  '@openrouter/sdk': true
  '@parcel/watcher': true
  esbuild: true
  isolated-vm: false
  nx: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  workerd: true
