// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, `vtt`, or `diarized_json`. For `gpt-4o-transcribe` and `gpt-4o-mini-transcribe`, the only supported format is `json`. For `gpt-4o-transcribe-diarize`, the supported formats are `json`, `text`, and `diarized_json`, with `diarized_json` required to receive speaker annotations.
 *
 */
export const zAudioResponseFormat = z
  .enum(['json', 'text', 'srt', 'verbose_json', 'vtt', 'diarized_json'])
  .default('json')

export const zCreateTranslationRequest = z.object({
  file: z.string(),
  model: z.union([z.string(), z.enum(['whisper-1'])]),
  prompt: z.string().optional(),
  response_format: z
    .enum(['json', 'text', 'srt', 'verbose_json', 'vtt'])
    .optional()
    .default('json'),
  temperature: z.number().optional().default(0),
})

export const zCreateTranslationResponseJson = z.object({
  text: z.string(),
})

export const zCreateVoiceConsentRequest = z.object({
  name: z.string(),
  recording: z.string(),
  language: z.string(),
})

export const zCreateVoiceRequest = z.object({
  name: z.string(),
  audio_sample: z.string(),
  consent: z.string(),
})

/**
 * Emitted for each chunk of audio data generated during speech synthesis.
 */
export const zSpeechAudioDeltaEvent = z.object({
  type: z.enum(['speech.audio.delta']),
  audio: z.string(),
})

/**
 * Emitted when the speech synthesis is complete and all audio has been streamed.
 */
export const zSpeechAudioDoneEvent = z.object({
  type: z.enum(['speech.audio.done']),
  usage: z.object({
    input_tokens: z.int(),
    output_tokens: z.int(),
    total_tokens: z.int(),
  }),
})

export const zCreateSpeechResponseStreamEvent = z.discriminatedUnion('type', [
  zSpeechAudioDeltaEvent,
  zSpeechAudioDoneEvent,
])

/**
 * A segment of diarized transcript text with speaker metadata.
 */
export const zTranscriptionDiarizedSegment = z.object({
  type: z.enum(['transcript.text.segment']),
  id: z.string(),
  start: z.number(),
  end: z.number(),
  text: z.string(),
  speaker: z.string(),
})

export const zTranscriptionInclude = z.enum(['logprobs'])

export const zTranscriptionSegment = z.object({
  id: z.int(),
  seek: z.int(),
  start: z.number(),
  end: z.number(),
  text: z.string(),
  tokens: z.array(z.int()),
  temperature: z.number(),
  avg_logprob: z.number(),
  compression_ratio: z.number(),
  no_speech_prob: z.number(),
})

export const zCreateTranslationResponseVerboseJson = z.object({
  language: z.string(),
  duration: z.number(),
  text: z.string(),
  segments: z.array(zTranscriptionSegment).optional(),
})

export const zTranscriptionWord = z.object({
  word: z.string(),
  start: z.number(),
  end: z.number(),
})

/**
 * Emitted when there is an additional text delta. This is also the first event emitted when the transcription starts. Only emitted when you [create a transcription](/docs/api-reference/audio/create-transcription) with the `Stream` parameter set to `true`.
 */
export const zTranscriptTextDeltaEvent = z.object({
  type: z.enum(['transcript.text.delta']),
  delta: z.string(),
  logprobs: z
    .array(
      z.object({
        token: z.string().optional(),
        logprob: z.number().optional(),
        bytes: z.array(z.int()).optional(),
      }),
    )
    .optional(),
  segment_id: z.string().optional(),
})

/**
 * Emitted when a diarized transcription returns a completed segment with speaker information. Only emitted when you [create a transcription](/docs/api-reference/audio/create-transcription) with `stream` set to `true` and `response_format` set to `diarized_json`.
 *
 */
export const zTranscriptTextSegmentEvent = z.object({
  type: z.enum(['transcript.text.segment']),
  id: z.string(),
  start: z.number(),
  end: z.number(),
  text: z.string(),
  speaker: z.string(),
})

/**
 * Duration Usage
 *
 * Usage statistics for models billed by audio input duration.
 */
export const zTranscriptTextUsageDuration = z.object({
  type: z.enum(['duration']),
  seconds: z.number(),
})

/**
 * Represents a verbose json transcription response returned by model, based on the provided input.
 */
export const zCreateTranscriptionResponseVerboseJson = z.object({
  language: z.string(),
  duration: z.number(),
  text: z.string(),
  words: z.array(zTranscriptionWord).optional(),
  segments: z.array(zTranscriptionSegment).optional(),
  usage: zTranscriptTextUsageDuration.optional(),
})

/**
 * Token Usage
 *
 * Usage statistics for models billed by token usage.
 */
export const zTranscriptTextUsageTokens = z.object({
  type: z.enum(['tokens']),
  input_tokens: z.int(),
  input_token_details: z
    .object({
      text_tokens: z.int().optional(),
      audio_tokens: z.int().optional(),
    })
    .optional(),
  output_tokens: z.int(),
  total_tokens: z.int(),
})

/**
 * Represents a diarized transcription response returned by the model, including the combined transcript and speaker-segment annotations.
 *
 */
export const zCreateTranscriptionResponseDiarizedJson = z.object({
  task: z.enum(['transcribe']),
  duration: z.number(),
  text: z.string(),
  segments: z.array(zTranscriptionDiarizedSegment),
  usage: z
    .discriminatedUnion('type', [
      zTranscriptTextUsageTokens,
      zTranscriptTextUsageDuration,
    ])
    .optional(),
})

/**
 * Represents a transcription response returned by model, based on the provided input.
 */
export const zCreateTranscriptionResponseJson = z.object({
  text: z.string(),
  logprobs: z
    .array(
      z.object({
        token: z.string().optional(),
        logprob: z.number().optional(),
        bytes: z.array(z.number()).optional(),
      }),
    )
    .optional(),
  usage: z
    .union([zTranscriptTextUsageTokens, zTranscriptTextUsageDuration])
    .optional(),
})

/**
 * Emitted when the transcription is complete. Contains the complete transcription text. Only emitted when you [create a transcription](/docs/api-reference/audio/create-transcription) with the `Stream` parameter set to `true`.
 */
export const zTranscriptTextDoneEvent = z.object({
  type: z.enum(['transcript.text.done']),
  text: z.string(),
  logprobs: z
    .array(
      z.object({
        token: z.string().optional(),
        logprob: z.number().optional(),
        bytes: z.array(z.int()).optional(),
      }),
    )
    .optional(),
  usage: zTranscriptTextUsageTokens.optional(),
})

export const zCreateTranscriptionResponseStreamEvent = z.discriminatedUnion(
  'type',
  [
    zTranscriptTextSegmentEvent,
    zTranscriptTextDeltaEvent,
    zTranscriptTextDoneEvent,
  ],
)

export const zUpdateVoiceConsentRequest = z.object({
  name: z.string(),
})

export const zVadConfig = z.object({
  type: z.enum(['server_vad']),
  prefix_padding_ms: z.int().optional().default(300),
  silence_duration_ms: z.int().optional().default(200),
  threshold: z.number().optional().default(0.5),
})

export const zCreateTranscriptionRequest = z.object({
  file: z.string(),
  model: z.union([
    z.string(),
    z.enum([
      'whisper-1',
      'gpt-4o-transcribe',
      'gpt-4o-mini-transcribe',
      'gpt-4o-mini-transcribe-2025-12-15',
      'gpt-4o-transcribe-diarize',
    ]),
  ]),
  language: z.string().optional(),
  prompt: z.string().optional(),
  response_format: zAudioResponseFormat.optional(),
  temperature: z.number().optional().default(0),
  include: z.array(zTranscriptionInclude).optional(),
  timestamp_granularities: z
    .array(z.enum(['word', 'segment']))
    .optional()
    .default(['segment']),
  stream: z.union([z.boolean(), z.unknown()]).optional(),
  chunking_strategy: z
    .union([z.union([z.enum(['auto']), zVadConfig]), z.unknown()])
    .optional(),
  known_speaker_names: z.array(z.string()).max(4).optional(),
  known_speaker_references: z.array(z.string()).max(4).optional(),
})

/**
 * Voice consent
 *
 * A consent recording used to authorize creation of a custom voice.
 */
export const zVoiceConsentResource = z.object({
  object: z.enum(['audio.voice_consent']),
  id: z.string(),
  name: z.string(),
  language: z.string(),
  created_at: z.int(),
})

export const zVoiceIdsShared = z.union([
  z.string(),
  z.enum([
    'alloy',
    'ash',
    'ballad',
    'coral',
    'echo',
    'sage',
    'shimmer',
    'verse',
    'marin',
    'cedar',
  ]),
])

/**
 * Voice
 *
 * A built-in voice name or a custom voice reference.
 *
 */
export const zVoiceIdsOrCustomVoice = z.union([
  zVoiceIdsShared,
  z.object({
    id: z.string(),
  }),
])

export const zCreateSpeechRequest = z.object({
  model: z.union([
    z.string(),
    z.enum([
      'tts-1',
      'tts-1-hd',
      'gpt-4o-mini-tts',
      'gpt-4o-mini-tts-2025-12-15',
    ]),
  ]),
  input: z.string().max(4096),
  instructions: z.string().max(4096).optional(),
  voice: zVoiceIdsOrCustomVoice,
  response_format: z
    .enum(['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'])
    .optional()
    .default('mp3'),
  speed: z.number().gte(0.25).lte(4).optional().default(1),
  stream_format: z.enum(['sse', 'audio']).optional().default('audio'),
})

/**
 * Voice
 *
 * A custom voice that can be used for audio output.
 */
export const zVoiceResource = z.object({
  object: z.enum(['audio.voice']),
  id: z.string(),
  name: z.string(),
  created_at: z.int(),
})

export const zCreateSpeechBody = zCreateSpeechRequest

/**
 * OK
 */
export const zCreateSpeechResponse = z.string()

export const zCreateTranscriptionBody = zCreateTranscriptionRequest

/**
 * OK
 */
export const zCreateTranscriptionResponse = z.union([
  zCreateTranscriptionResponseJson,
  zCreateTranscriptionResponseDiarizedJson,
  zCreateTranscriptionResponseVerboseJson,
])

export const zCreateTranslationBody = zCreateTranslationRequest

/**
 * OK
 */
export const zCreateTranslationResponse = z.union([
  zCreateTranslationResponseJson,
  zCreateTranslationResponseVerboseJson,
])

export const zCreateVoiceConsentBody = zCreateVoiceConsentRequest

/**
 * OK
 */
export const zCreateVoiceConsentResponse = zVoiceConsentResource

export const zUpdateVoiceConsentBody = zUpdateVoiceConsentRequest

export const zUpdateVoiceConsentPath = z.object({
  consent_id: z.string(),
})

/**
 * OK
 */
export const zUpdateVoiceConsentResponse = zVoiceConsentResource

export const zCreateVoiceBody = zCreateVoiceRequest

/**
 * OK
 */
export const zCreateVoiceResponse = zVoiceResource
