export interface ChatCompletionContentPartText {
  /** The text content. */
  text: string

  /** The type of the content part. */
  type: 'text'
}

export interface ChatCompletionContentPartImage {
  imageUrl: string | { url: string; detail?: 'auto' | 'low' | 'high' }

  /** The type of the content part. */
  type: 'image_url'
}

export interface ChatCompletionContentPartDocumentUrl {
  documentUrl: string

  /** The type of the content part. */
  type: 'document_url'
}

export type ChatCompletionContentPart =
  | ChatCompletionContentPartText
  | ChatCompletionContentPartImage
  | ChatCompletionContentPartDocumentUrl

export interface ChatCompletionMessageToolCall {
  /** The ID of the tool call. */
  id: string

  /** The type of the tool. Currently only `function` is supported. */
  type?: 'function'

  /** The function that the model called. */
  function: {
    /** The name of the function to call. */
    name: string

    /** Arguments generated by the model as a JSON string. */
    arguments: string
  }
}

export type FunctionParameters = { [key: string]: unknown }

export interface FunctionDefinition {
  name: string

  /** A description of what the function does. */
  description?: string

  /** Function parameters defined as a JSON Schema object. */
  parameters?: FunctionParameters

  /** Whether to enable strict schema adherence. */
  strict?: boolean
}

export interface ChatCompletionTool {
  /** The type of the tool. */
  type: 'function'

  function: FunctionDefinition
}

export interface ChatCompletionNamedToolChoice {
  type: 'function'
  function: {
    name: string
  }
}

export type ChatCompletionToolChoiceOption =
  | 'none'
  | 'auto'
  | 'any'
  | 'required'
  | ChatCompletionNamedToolChoice

export interface ChatCompletionSystemMessageParam {
  role: 'system'
  content: string | Array<ChatCompletionContentPartText>
}

export interface ChatCompletionUserMessageParam {
  role: 'user'
  content: string | Array<ChatCompletionContentPart>
}

export interface ChatCompletionAssistantMessageParam {
  role: 'assistant'
  content?: string | Array<ChatCompletionContentPartText> | null
  toolCalls?: Array<ChatCompletionMessageToolCall>
  prefix?: boolean
}

export interface ChatCompletionToolMessageParam {
  role: 'tool'
  content: string | Array<ChatCompletionContentPartText>
  toolCallId: string
  name?: string
}

export type ChatCompletionMessageParam =
  | ChatCompletionSystemMessageParam
  | ChatCompletionUserMessageParam
  | ChatCompletionAssistantMessageParam
  | ChatCompletionToolMessageParam

export interface ResponseFormatText {
  type: 'text'
}

export interface ResponseFormatJsonObject {
  type: 'json_object'
}

export interface ResponseFormatJsonSchema {
  type: 'json_schema'
  jsonSchema: {
    name: string
    description?: string
    schemaDefinition: { [key: string]: unknown }
    strict?: boolean
  }
}

export type MistralTextMetadata = Record<string, never>

export interface MistralImageMetadata {
  detail?: 'auto' | 'low' | 'high'
}

export type MistralAudioMetadata = Record<string, never>

export type MistralVideoMetadata = Record<string, never>

export type MistralDocumentMetadata = Record<string, never>

export interface MistralMessageMetadataByModality {
  text: MistralTextMetadata
  image: MistralImageMetadata
  audio: MistralAudioMetadata
  video: MistralVideoMetadata
  document: MistralDocumentMetadata
}
