// Generated by scripts/sync-model-reasoning.ts from models.dev. Do not edit.
import type { ModelReasoning } from '@tanstack/ai'

/**
 * Each model's reasoning levels, and whether it takes a token budget, for
 * `chat({ reasoning })`. A model that is not here does not reason.
 */
export type MistralModelReasoningByName = {
  'mistral-medium-latest': { levels: 'off' | 'high'; budget: false }
  'mistral-small-latest': { levels: 'off' | 'high'; budget: false }
  'magistral-medium-latest': {
    levels: 'off' | 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
}

/** The same data at runtime. `false`: the model does not reason. */
export const MISTRAL_MODEL_REASONING: Readonly<Record<string, ModelReasoning>> =
  {
    'mistral-large-latest': false,
    'mistral-medium-latest': {
      map: {
        off: 'none',
        minimal: null,
        low: null,
        medium: null,
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'mistral-small-latest': {
      map: {
        off: 'none',
        minimal: null,
        low: null,
        medium: null,
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'ministral-8b-latest': false,
    'ministral-3b-latest': false,
    'codestral-latest': false,
    'pixtral-large-latest': false,
    'magistral-medium-latest': { budget: false },
    'open-mistral-nemo': false,
    'mistral-medium-3': false,
    'mistral-small-2503': false,
  }
