// Generated by scripts/sync-model-reasoning.ts from models.dev. Do not edit.
import type { ModelReasoning } from '@tanstack/ai'

/**
 * Each model's reasoning levels, and whether it takes a token budget, for
 * `chat({ reasoning })`. A model that is not here does not reason.
 */
export type OpenCodeModelReasoningByName = {
  'anthropic/claude-opus-4-5': {
    levels: 'low' | 'medium' | 'high'
    budget: true
  }
  'anthropic/claude-sonnet-4-5': {
    levels: 'off' | 'minimal' | 'low' | 'medium' | 'high'
    budget: true
  }
  'openai/gpt-5.2': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh'
    budget: false
  }
  'openai/gpt-5.1-codex': { levels: 'low' | 'medium' | 'high'; budget: false }
  'opencode/claude-sonnet-4-5': {
    levels: 'off' | 'minimal' | 'low' | 'medium' | 'high'
    budget: true
  }
  'opencode/gpt-5.1-codex': { levels: 'low' | 'medium' | 'high'; budget: false }
}

/** The same data at runtime. `false`: the model does not reason. */
export const OPENCODE_MODEL_REASONING: Readonly<
  Record<string, ModelReasoning>
> = {
  'anthropic/claude-opus-4-5': {
    map: {
      off: null,
      minimal: null,
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: true,
  },
  'anthropic/claude-sonnet-4-5': { budget: true },
  'openai/gpt-5.2': {
    map: {
      off: 'none',
      minimal: null,
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: 'xhigh',
      max: null,
    },
    budget: false,
  },
  'openai/gpt-5.1-codex': {
    map: {
      off: null,
      minimal: null,
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'opencode/claude-sonnet-4-5': { budget: true },
  'opencode/gpt-5.1-codex': {
    map: {
      off: null,
      minimal: null,
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
}
