// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const PredictRequestSchema = {
  type: 'object',
  description: 'Request message for PredictionService.Predict.',
  properties: {
    instances: {
      type: 'array',
      description:
        'Required. The instances that are the input to the prediction call.',
      items: { type: 'any' },
    },
    parameters: {
      type: 'any',
      description: 'Optional. The parameters that govern the prediction call.',
    },
  },
} as const

export const PredictResponseSchema = {
  type: 'object',
  description: 'Response message for [PredictionService.Predict].',
  properties: {
    predictions: {
      type: 'array',
      description: 'The outputs of the prediction call.',
      items: { type: 'any' },
    },
  },
} as const
