// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const EditImageRequestSchema = {
  type: 'object',
  description: 'Request for editing image',
  required: ['prompt'],
  properties: {
    aspect_ratio: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/ImageAspectRatio',
          description:
            'Aspect ratio of the output image for image editing with multiple images.\nFor single image editing, do not set this. It will always auto-detect from the input image.',
        },
      ],
    },
    image: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/ImageUrl',
          description:
            'Input image to perform edit on. Mutually exclusive with `images`.',
        },
      ],
    },
    images: {
      type: 'array',
      items: { $ref: '#/$defs/ImageUrl' },
      description:
        'List of input images for multi-reference editing.\nMutually exclusive with `image`. When multiple images are provided,\nrefer to them as \\<IMAGE_0\\>, \\<IMAGE_1\\>, etc. in the prompt.',
    },
    model: {
      type: ['string', 'null'],
      description: 'Model to be used.',
      example: 'grok-imagine-image',
    },
    n: {
      type: ['integer', 'null'],
      format: 'int32',
      description: 'Number of image edits to be generated.',
    },
    prompt: { type: 'string', description: 'Prompt for image editing.' },
    resolution: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/ImageResolution',
          description:
            'Resolution of the generated image. Defaults to `1k`.\nOnly supported by grok-imagine models.',
        },
      ],
    },
    response_format: {
      type: ['string', 'null'],
      description:
        'Response format to return the image in. Can be `url` or `b64_json`. If `b64_json` is specified, the image will be returned as a base64-encoded string instead of a url to the generated image file.',
      default: 'url',
    },
    user: {
      type: ['string', 'null'],
      description:
        'A unique identifier representing your end-user, which can help xAI to monitor and detect abuse.',
    },
  },
  $defs: {
    ImageAspectRatio: {
      type: 'string',
      description:
        'Aspect ratio for image generation.\nOnly supported by grok-imagine models.',
      enum: [
        '1:1',
        '3:4',
        '4:3',
        '9:16',
        '16:9',
        '2:3',
        '3:2',
        '9:19.5',
        '19.5:9',
        '9:20',
        '20:9',
        '1:2',
        '2:1',
        'auto',
      ],
    },
    ImageResolution: {
      type: 'string',
      description:
        'Resolution for image generation.\nOnly supported by grok-imagine models.',
      enum: ['1k', '2k'],
    },
    ImageUrl: {
      type: 'object',
      description:
        'Image input for generation and editing requests.\nAccepts a public URL, a base64-encoded data URL, or a file_id from the xAI Files API.',
      properties: {
        file_id: {
          type: ['string', 'null'],
          description:
            'File ID from the xAI Files API. Mutually exclusive with `url`.\nThe file must be an image (JPEG, PNG, or WebP) and fully uploaded.',
        },
        url: {
          type: 'string',
          description:
            'Public URL or base64-encoded data URL of the image (JPEG, PNG, or WebP).\nAlso accepts `image_url` for compatibility.\nRequired when `file_id` is not set.',
        },
      },
    },
  },
} as const

export const GenerateImageRequestSchema = {
  type: 'object',
  properties: {
    aspect_ratio: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/ImageAspectRatio',
          description:
            'Aspect ratio of the generated image. Can be `1:1`, `3:4`, `4:3`, `9:16`, `16:9`, `2:3`, `3:2`, `9:19.5`, `19.5:9`, `9:20`, `20:9`, `1:2`, `2:1`, or `auto`.\nDefaults to `auto` for automatically selecting the best ratio for the prompt.\nOnly supported by grok-imagine models.',
        },
      ],
    },
    model: {
      type: ['string', 'null'],
      description: 'Model to be used.',
      example: 'grok-imagine-image',
    },
    n: {
      type: ['integer', 'null'],
      format: 'int32',
      description: 'Number of images to be generated',
      default: 1,
      maximum: 10,
      minimum: 1,
    },
    prompt: { type: 'string', description: 'Prompt for image generation.' },
    resolution: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/ImageResolution',
          description:
            'Resolution of the generated image. Defaults to `1k`.\nOnly supported by grok-imagine models.',
        },
      ],
    },
    response_format: {
      type: ['string', 'null'],
      description:
        'Response format to return the image in. Can be url or b64_json. If b64_json is specified, the image will be returned as a base64-encoded string instead of a url to the generated image file.',
      default: 'url',
    },
    user: {
      type: ['string', 'null'],
      description:
        'A unique identifier representing your end-user, which can help xAI to monitor and detect abuse.',
    },
  },
  $defs: {
    ImageAspectRatio: {
      type: 'string',
      description:
        'Aspect ratio for image generation.\nOnly supported by grok-imagine models.',
      enum: [
        '1:1',
        '3:4',
        '4:3',
        '9:16',
        '16:9',
        '2:3',
        '3:2',
        '9:19.5',
        '19.5:9',
        '9:20',
        '20:9',
        '1:2',
        '2:1',
        'auto',
      ],
    },
    ImageResolution: {
      type: 'string',
      description:
        'Resolution for image generation.\nOnly supported by grok-imagine models.',
      enum: ['1k', '2k'],
    },
  },
} as const

export const GeneratedImageSchema = {
  type: 'object',
  description: 'Generated images',
  properties: {
    b64_json: {
      type: ['string', 'null'],
      description:
        'A base64-encoded string representation of the generated image (without the data-URI prefix), if `b64_json` is specified as `response_format` in the request.',
    },
    mime_type: {
      type: ['string', 'null'],
      description:
        'The MIME type of the generated image (e.g. `image/png`, `image/jpeg`, `image/webp`).',
    },
    url: {
      type: ['string', 'null'],
      description:
        'A url to the generated image, if `response_format` is not specified or with `url` in the request.',
    },
  },
} as const

export const GeneratedImageResponseSchema = {
  type: 'object',
  description: 'Image generation response for `/v1/image/generations` endpoint',
  required: ['data'],
  properties: {
    data: {
      type: 'array',
      items: { $ref: '#/$defs/GeneratedImage' },
      description: 'A list of generated image objects.',
    },
    usage: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/MediaUsage',
          description: 'Billing and cost information for this request.',
        },
      ],
    },
  },
  $defs: {
    GeneratedImage: {
      type: 'object',
      description: 'Generated images',
      properties: {
        b64_json: {
          type: ['string', 'null'],
          description:
            'A base64-encoded string representation of the generated image (without the data-URI prefix), if `b64_json` is specified as `response_format` in the request.',
        },
        mime_type: {
          type: ['string', 'null'],
          description:
            'The MIME type of the generated image (e.g. `image/png`, `image/jpeg`, `image/webp`).',
        },
        url: {
          type: ['string', 'null'],
          description:
            'A url to the generated image, if `response_format` is not specified or with `url` in the request.',
        },
      },
    },
    MediaUsage: {
      type: 'object',
      description:
        'Billing and cost information for media generation requests (image and video).',
      required: ['cost_in_usd_ticks'],
      properties: {
        cost_in_usd_ticks: {
          type: 'integer',
          format: 'int64',
          description:
            'The cost of this request expressed in USD ticks.\nOne USD cent equals 100,000,000 ticks, so one US dollar equals\n10,000,000,000 ticks.',
        },
      },
    },
  },
} as const

export const ImageAspectRatioSchema = {
  type: 'string',
  description:
    'Aspect ratio for image generation.\nOnly supported by grok-imagine models.',
  enum: [
    '1:1',
    '3:4',
    '4:3',
    '9:16',
    '16:9',
    '2:3',
    '3:2',
    '9:19.5',
    '19.5:9',
    '9:20',
    '20:9',
    '1:2',
    '2:1',
    'auto',
  ],
} as const

export const ImageResolutionSchema = {
  type: 'string',
  description:
    'Resolution for image generation.\nOnly supported by grok-imagine models.',
  enum: ['1k', '2k'],
} as const

export const ImageUrlSchema = {
  type: 'object',
  description:
    'Image input for generation and editing requests.\nAccepts a public URL, a base64-encoded data URL, or a file_id from the xAI Files API.',
  properties: {
    file_id: {
      type: ['string', 'null'],
      description:
        'File ID from the xAI Files API. Mutually exclusive with `url`.\nThe file must be an image (JPEG, PNG, or WebP) and fully uploaded.',
    },
    url: {
      type: 'string',
      description:
        'Public URL or base64-encoded data URL of the image (JPEG, PNG, or WebP).\nAlso accepts `image_url` for compatibility.\nRequired when `file_id` is not set.',
    },
  },
} as const

export const MediaUsageSchema = {
  type: 'object',
  description:
    'Billing and cost information for media generation requests (image and video).',
  required: ['cost_in_usd_ticks'],
  properties: {
    cost_in_usd_ticks: {
      type: 'integer',
      format: 'int64',
      description:
        'The cost of this request expressed in USD ticks.\nOne USD cent equals 100,000,000 ticks, so one US dollar equals\n10,000,000,000 ticks.',
    },
  },
} as const
