// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Configuration for audio output format.
 */
export const zAudioResponseFormat = z.object({
  mimeType: z
    .enum([
      'MIME_TYPE_UNSPECIFIED',
      'AUDIO_MP3',
      'AUDIO_OGG_OPUS',
      'AUDIO_L16',
      'AUDIO_WAV',
      'AUDIO_ALAW',
      'AUDIO_MULAW',
    ])
    .optional(),
  delivery: z.enum(['DELIVERY_UNSPECIFIED', 'INLINE', 'URI']).optional(),
  sampleRate: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  bitRate: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
})

/**
 * Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.
 */
export const zBlob = z.object({
  mimeType: z.string().optional(),
  data: z.string().optional(),
})

/**
 * A citation to a source for a portion of a specific response.
 */
export const zCitationSource = z.object({
  startIndex: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  endIndex: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  uri: z.string().optional(),
  license: z.string().optional(),
})

/**
 * A collection of source attributions for a piece of content.
 */
export const zCitationMetadata = z.object({
  citationSources: z.array(zCitationSource).optional(),
})

/**
 * Tool that executes code generated by the model, and automatically returns the result to the model. See also `ExecutableCode` and `CodeExecutionResult` which are only generated when using this tool.
 */
export const zCodeExecution = z.record(z.string(), z.unknown())

/**
 * Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.
 */
export const zCodeExecutionResult = z.object({
  id: z.string().optional(),
  outcome: z
    .enum([
      'OUTCOME_UNSPECIFIED',
      'OUTCOME_OK',
      'OUTCOME_FAILED',
      'OUTCOME_DEADLINE_EXCEEDED',
    ])
    .optional(),
  output: z.string().optional(),
})

/**
 * Computer Use tool type.
 */
export const zComputerUse = z.object({
  environment: z
    .enum(['ENVIRONMENT_UNSPECIFIED', 'ENVIRONMENT_BROWSER'])
    .optional(),
  excludedPredefinedFunctions: z.array(z.string()).optional(),
})

/**
 * Filter condition applicable to a single key.
 */
export const zCondition = z.object({
  stringValue: z.string().optional(),
  numericValue: z.number().optional(),
  operation: z
    .enum([
      'OPERATOR_UNSPECIFIED',
      'LESS',
      'LESS_EQUAL',
      'EQUAL',
      'GREATER_EQUAL',
      'GREATER',
      'NOT_EQUAL',
      'INCLUDES',
      'EXCLUDES',
    ])
    .optional(),
})

/**
 * Content filtering metadata associated with processing a single request. ContentFilter contains a reason and an optional supporting string. The reason may be unspecified.
 */
export const zContentFilter = z.object({
  reason: z.enum(['BLOCKED_REASON_UNSPECIFIED', 'SAFETY', 'OTHER']).optional(),
  message: z.string().optional(),
})

/**
 * A response from `CountMessageTokens`. It returns the model's `token_count` for the `prompt`.
 */
export const zCountMessageTokensResponse = z.object({
  tokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
})

/**
 * A response from `CountTextTokens`. It returns the model's `token_count` for the `prompt`.
 */
export const zCountTextTokensResponse = z.object({
  tokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
})

/**
 * Describes the options to customize dynamic retrieval.
 */
export const zDynamicRetrievalConfig = z.object({
  mode: z.enum(['MODE_UNSPECIFIED', 'MODE_DYNAMIC']).optional(),
  dynamicThreshold: z.number().optional(),
})

/**
 * Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.
 */
export const zExecutableCode = z.object({
  id: z.string().optional(),
  language: z.enum(['LANGUAGE_UNSPECIFIED', 'PYTHON']).optional(),
  code: z.string().optional(),
})

/**
 * URI based data.
 */
export const zFileData = z.object({
  mimeType: z.string().optional(),
  fileUri: z.string().optional(),
})

/**
 * The FileSearch tool that retrieves knowledge from Semantic Retrieval corpora. Files are imported to Semantic Retrieval corpora using the ImportFile API.
 */
export const zFileSearch = z.object({
  fileSearchStoreNames: z.array(z.string()).optional(),
  topK: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  metadataFilter: z.string().optional(),
})

/**
 * A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.
 */
export const zFunctionCall = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  args: z.record(z.string(), z.unknown()).optional(),
})

/**
 * Configuration for specifying function calling behavior.
 */
export const zFunctionCallingConfig = z.object({
  mode: z
    .enum(['MODE_UNSPECIFIED', 'AUTO', 'ANY', 'NONE', 'VALIDATED'])
    .optional(),
  allowedFunctionNames: z.array(z.string()).optional(),
})

/**
 * Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.
 */
export const zFunctionResponseBlob = z.object({
  mimeType: z.string().optional(),
  data: z.string().optional(),
})

/**
 * A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.
 */
export const zFunctionResponsePart = z.object({
  inlineData: zFunctionResponseBlob.optional(),
})

/**
 * The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.
 */
export const zFunctionResponse = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  response: z.record(z.string(), z.unknown()).optional(),
  parts: z.array(zFunctionResponsePart).optional(),
  willContinue: z.boolean().optional(),
  scheduling: z
    .enum(['SCHEDULING_UNSPECIFIED', 'SILENT', 'WHEN_IDLE', 'INTERRUPT'])
    .optional(),
})

/**
 * Segment of the content.
 */
export const zGoogleAiGenerativelanguageV1BetaSegment = z.object({
  partIndex: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  startIndex: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  endIndex: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  text: z.string().optional(),
})

/**
 * Grounding support.
 */
export const zGoogleAiGenerativelanguageV1BetaGroundingSupport = z.object({
  segment: zGoogleAiGenerativelanguageV1BetaSegment.optional(),
  groundingChunkIndices: z
    .array(
      z
        .int()
        .min(-2147483648, {
          error: 'Invalid value: Expected int32 to be >= -2147483648',
        })
        .max(2147483647, {
          error: 'Invalid value: Expected int32 to be <= 2147483647',
        }),
    )
    .optional(),
  confidenceScores: z.array(z.number()).optional(),
  renderedParts: z
    .array(
      z
        .int()
        .min(-2147483648, {
          error: 'Invalid value: Expected int32 to be >= -2147483648',
        })
        .max(2147483647, {
          error: 'Invalid value: Expected int32 to be <= 2147483647',
        }),
    )
    .optional(),
})

/**
 * The GoogleMaps Tool that provides geospatial context for the user's query.
 */
export const zGoogleMaps = z.object({
  enableWidget: z.boolean().optional(),
})

/**
 * Tool to retrieve public web data for grounding, powered by Google.
 */
export const zGoogleSearchRetrieval = z.object({
  dynamicRetrievalConfig: zDynamicRetrievalConfig.optional(),
})

/**
 * A list of string values.
 */
export const zGroundingChunkStringList = z.object({
  values: z.array(z.string()).optional(),
})

/**
 * User provided metadata about the GroundingFact.
 */
export const zGroundingChunkCustomMetadata = z.object({
  stringValue: z.string().optional(),
  stringListValue: zGroundingChunkStringList.optional(),
  numericValue: z.number().optional(),
  key: z.string().optional(),
})

/**
 * Identifier for a part within a `GroundingPassage`.
 */
export const zGroundingPassageId = z.object({
  passageId: z.string().optional(),
  partIndex: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
})

/**
 * Chunk from image search.
 */
export const zImage = z.object({
  sourceUri: z.string().optional(),
  imageUri: z.string().optional(),
  title: z.string().optional(),
  domain: z.string().optional(),
})

/**
 * Config for image generation features.
 */
export const zImageConfig = z.object({
  aspectRatio: z.string().optional(),
  imageSize: z.string().optional(),
})

/**
 * Configuration for image output format.
 */
export const zImageResponseFormat = z.object({
  mimeType: z.enum(['MIME_TYPE_UNSPECIFIED', 'IMAGE_JPEG']).optional(),
  delivery: z.enum(['DELIVERY_UNSPECIFIED', 'INLINE', 'URI']).optional(),
  aspectRatio: z
    .enum([
      'ASPECT_RATIO_UNSPECIFIED',
      'ASPECT_RATIO_ONE_BY_ONE',
      'ASPECT_RATIO_TWO_BY_THREE',
      'ASPECT_RATIO_THREE_BY_TWO',
      'ASPECT_RATIO_THREE_BY_FOUR',
      'ASPECT_RATIO_FOUR_BY_THREE',
      'ASPECT_RATIO_FOUR_BY_FIVE',
      'ASPECT_RATIO_FIVE_BY_FOUR',
      'ASPECT_RATIO_NINE_BY_SIXTEEN',
      'ASPECT_RATIO_SIXTEEN_BY_NINE',
      'ASPECT_RATIO_TWENTY_ONE_BY_NINE',
      'ASPECT_RATIO_ONE_BY_EIGHT',
      'ASPECT_RATIO_EIGHT_BY_ONE',
      'ASPECT_RATIO_ONE_BY_FOUR',
      'ASPECT_RATIO_FOUR_BY_ONE',
    ])
    .optional(),
  imageSize: z
    .enum([
      'IMAGE_SIZE_UNSPECIFIED',
      'IMAGE_SIZE_FIVE_TWELVE',
      'IMAGE_SIZE_ONE_K',
      'IMAGE_SIZE_TWO_K',
      'IMAGE_SIZE_FOUR_K',
    ])
    .optional(),
})

/**
 * Image search for grounding and related configurations.
 */
export const zImageSearch = z.record(z.string(), z.unknown())

/**
 * Represents a time interval, encoded as a Timestamp start (inclusive) and a Timestamp end (exclusive). The start must be less than or equal to the end. When the start equals the end, the interval is empty (matches no time). When both start and end are unspecified, the interval matches any time.
 */
export const zInterval = z.object({
  startTime: z.string().optional(),
  endTime: z.string().optional(),
})

/**
 * An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
 */
export const zLatLng = z.object({
  latitude: z.number().optional(),
  longitude: z.number().optional(),
})

/**
 * Candidate for the logprobs token and score.
 */
export const zLogprobsResultCandidate = z.object({
  token: z.string().optional(),
  tokenId: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  logProbability: z.number().optional(),
})

/**
 * Schema referenced but not defined upstream (missing from source OpenAPI spec)
 */
export const zMediaResolution = z.record(z.string(), z.unknown())

/**
 * The base unit of structured text. A `Message` includes an `author` and the `content` of the `Message`. The `author` is used to tag messages when they are fed to the model as text.
 */
export const zMessage = z.object({
  author: z.string().optional(),
  content: z.string().optional(),
  citationMetadata: zCitationMetadata.optional(),
})

/**
 * An input/output example used to instruct the Model. It demonstrates how the model should respond or format its response.
 */
export const zExample = z.object({
  input: zMessage.optional(),
  output: zMessage.optional(),
})

/**
 * The response from the model. This includes candidate messages and conversation history in the form of chronologically-ordered messages.
 */
export const zGenerateMessageResponse = z.object({
  candidates: z.array(zMessage).optional(),
  messages: z.array(zMessage).optional(),
  filters: z.array(zContentFilter).optional(),
})

/**
 * All of the structured input text passed to the model as a prompt. A `MessagePrompt` contains a structured set of fields that provide context for the conversation, examples of user input/model output message pairs that prime the model to respond in different ways, and the conversation history or list of messages representing the alternating turns of the conversation between the user and the model.
 */
export const zMessagePrompt = z.object({
  context: z.string().optional(),
  examples: z.array(zExample).optional(),
  messages: z.array(zMessage).optional(),
})

/**
 * Counts the number of tokens in the `prompt` sent to a model. Models may tokenize text differently, so each model may return a different `token_count`.
 */
export const zCountMessageTokensRequest = z.object({
  prompt: zMessagePrompt.optional(),
})

/**
 * Request to generate a message response from the model.
 */
export const zGenerateMessageRequest = z.object({
  prompt: zMessagePrompt.optional(),
  temperature: z.number().optional(),
  candidateCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  topP: z.number().optional(),
  topK: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
})

/**
 * User provided filter to limit retrieval based on `Chunk` or `Document` level metadata values. Example (genre = drama OR genre = action): key = "document.custom_metadata.genre" conditions = [{string_value = "drama", operation = EQUAL}, {string_value = "action", operation = EQUAL}]
 */
export const zMetadataFilter = z.object({
  key: z.string().optional(),
  conditions: z.array(zCondition).optional(),
})

/**
 * Represents token counting info for a single modality.
 */
export const zModalityTokenCount = z.object({
  modality: z
    .enum([
      'MODALITY_UNSPECIFIED',
      'TEXT',
      'IMAGE',
      'VIDEO',
      'AUDIO',
      'DOCUMENT',
    ])
    .optional(),
  tokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
})

/**
 * A response from `CountTokens`. It returns the model's `token_count` for the `prompt`.
 */
export const zCountTokensResponse = z.object({
  totalTokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  cachedContentTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  promptTokensDetails: z.array(zModalityTokenCount).optional(),
  cacheTokensDetails: z.array(zModalityTokenCount).optional(),
})

/**
 * The status of the underlying model. This is used to indicate the stage of the underlying model and the retirement time if applicable.
 */
export const zModelStatus = z.object({
  modelStage: z
    .enum([
      'MODEL_STAGE_UNSPECIFIED',
      'UNSTABLE_EXPERIMENTAL',
      'EXPERIMENTAL',
      'PREVIEW',
      'STABLE',
      'LEGACY',
      'DEPRECATED',
      'RETIRED',
    ])
    .optional(),
  retirementTime: z.string().optional(),
  message: z.string().optional(),
})

/**
 * The configuration for the prebuilt speaker to use.
 */
export const zPrebuiltVoiceConfig = z.object({
  voiceName: z.string().optional(),
})

/**
 * Retrieval config.
 */
export const zRetrievalConfig = z.object({
  latLng: zLatLng.optional(),
  languageCode: z.string().optional(),
})

/**
 * Metadata related to retrieval in the grounding flow.
 */
export const zRetrievalMetadata = z.object({
  googleSearchDynamicRetrievalScore: z.number().optional(),
})

/**
 * Chunk from context retrieved by the file search tool.
 */
export const zRetrievedContext = z.object({
  uri: z.string().optional(),
  title: z.string().optional(),
  text: z.string().optional(),
  fileSearchStore: z.string().optional(),
  customMetadata: z.array(zGroundingChunkCustomMetadata).optional(),
  pageNumber: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  mediaId: z.string().optional(),
})

/**
 * Encapsulates a snippet of a user review that answers a question about the features of a specific place in Google Maps.
 */
export const zReviewSnippet = z.object({
  reviewId: z.string().optional(),
  googleMapsUri: z.string().optional(),
  title: z.string().optional(),
})

/**
 * Collection of sources that provide answers about the features of a given place in Google Maps. Each PlaceAnswerSources message corresponds to a specific place in Google Maps. The Google Maps tool used these sources in order to answer questions about features of the place (e.g: "does Bar Foo have Wifi" or "is Foo Bar wheelchair accessible?"). Currently we only support review snippets as sources.
 */
export const zPlaceAnswerSources = z.object({
  reviewSnippets: z.array(zReviewSnippet).optional(),
})

/**
 * A grounding chunk from Google Maps. A Maps chunk corresponds to a single place.
 */
export const zMaps = z.object({
  uri: z.string().optional(),
  title: z.string().optional(),
  text: z.string().optional(),
  placeId: z.string().optional(),
  placeAnswerSources: zPlaceAnswerSources.optional(),
})

/**
 * Safety rating for a piece of content. The safety rating contains the category of harm and the harm probability level in that category for a piece of content. Content is classified for safety across a number of harm categories and the probability of the harm classification is included here.
 */
export const zSafetyRating = z.object({
  category: z
    .enum([
      'HARM_CATEGORY_UNSPECIFIED',
      'HARM_CATEGORY_DEROGATORY',
      'HARM_CATEGORY_TOXICITY',
      'HARM_CATEGORY_VIOLENCE',
      'HARM_CATEGORY_SEXUAL',
      'HARM_CATEGORY_MEDICAL',
      'HARM_CATEGORY_DANGEROUS',
      'HARM_CATEGORY_HARASSMENT',
      'HARM_CATEGORY_HATE_SPEECH',
      'HARM_CATEGORY_SEXUALLY_EXPLICIT',
      'HARM_CATEGORY_DANGEROUS_CONTENT',
      'HARM_CATEGORY_CIVIC_INTEGRITY',
    ])
    .optional(),
  probability: z
    .enum([
      'HARM_PROBABILITY_UNSPECIFIED',
      'NEGLIGIBLE',
      'LOW',
      'MEDIUM',
      'HIGH',
    ])
    .optional(),
  blocked: z.boolean().optional(),
})

/**
 * Feedback related to the input data used to answer the question, as opposed to the model-generated response to the question.
 */
export const zInputFeedback = z.object({
  blockReason: z
    .enum(['BLOCK_REASON_UNSPECIFIED', 'SAFETY', 'OTHER'])
    .optional(),
  safetyRatings: z.array(zSafetyRating).optional(),
})

/**
 * A set of the feedback metadata the prompt specified in `GenerateContentRequest.content`.
 */
export const zPromptFeedback = z.object({
  blockReason: z
    .enum([
      'BLOCK_REASON_UNSPECIFIED',
      'SAFETY',
      'OTHER',
      'BLOCKLIST',
      'PROHIBITED_CONTENT',
      'IMAGE_SAFETY',
    ])
    .optional(),
  safetyRatings: z.array(zSafetyRating).optional(),
})

/**
 * Safety setting, affecting the safety-blocking behavior. Passing a safety setting for a category changes the allowed probability that content is blocked.
 */
export const zSafetySetting = z.object({
  category: z
    .enum([
      'HARM_CATEGORY_UNSPECIFIED',
      'HARM_CATEGORY_DEROGATORY',
      'HARM_CATEGORY_TOXICITY',
      'HARM_CATEGORY_VIOLENCE',
      'HARM_CATEGORY_SEXUAL',
      'HARM_CATEGORY_MEDICAL',
      'HARM_CATEGORY_DANGEROUS',
      'HARM_CATEGORY_HARASSMENT',
      'HARM_CATEGORY_HATE_SPEECH',
      'HARM_CATEGORY_SEXUALLY_EXPLICIT',
      'HARM_CATEGORY_DANGEROUS_CONTENT',
      'HARM_CATEGORY_CIVIC_INTEGRITY',
    ])
    .optional(),
  threshold: z
    .enum([
      'HARM_BLOCK_THRESHOLD_UNSPECIFIED',
      'BLOCK_LOW_AND_ABOVE',
      'BLOCK_MEDIUM_AND_ABOVE',
      'BLOCK_ONLY_HIGH',
      'BLOCK_NONE',
      'OFF',
    ])
    .optional(),
})

/**
 * Safety feedback for an entire request. This field is populated if content in the input and/or response is blocked due to safety settings. SafetyFeedback may not exist for every HarmCategory. Each SafetyFeedback will return the safety settings used by the request as well as the lowest HarmProbability that should be allowed in order to return a result.
 */
export const zSafetyFeedback = z.object({
  rating: zSafetyRating.optional(),
  setting: zSafetySetting.optional(),
})

/**
 * The `Schema` object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. Represents a select subset of an [OpenAPI 3.0 schema object](https://spec.openapis.org/oas/v3.0.3#schema).
 */
export const zSchema = z.object({
  type: z
    .enum([
      'TYPE_UNSPECIFIED',
      'STRING',
      'NUMBER',
      'INTEGER',
      'BOOLEAN',
      'ARRAY',
      'OBJECT',
      'NULL',
    ])
    .optional(),
  format: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  nullable: z.boolean().optional(),
  enum: z.array(z.string()).optional(),
  items: z.lazy((): any => zSchema).optional(),
  maxItems: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .optional(),
  minItems: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .optional(),
  properties: z
    .record(
      z.string(),
      z.lazy((): any => zSchema),
    )
    .optional(),
  required: z.array(z.string()).optional(),
  minProperties: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .optional(),
  maxProperties: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .optional(),
  minimum: z.number().optional(),
  maximum: z.number().optional(),
  minLength: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .optional(),
  maxLength: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .optional(),
  pattern: z.string().optional(),
  example: z.unknown().optional(),
  anyOf: z.array(z.lazy((): any => zSchema)).optional(),
  propertyOrdering: z.array(z.string()).optional(),
  default: z.unknown().optional(),
})

/**
 * Structured representation of a function declaration as defined by the [OpenAPI 3.03 specification](https://spec.openapis.org/oas/v3.0.3). Included in this declaration are the function name and parameters. This FunctionDeclaration is a representation of a block of code that can be used as a `Tool` by the model and executed by the client.
 */
export const zFunctionDeclaration = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  parameters: zSchema.optional(),
  parametersJsonSchema: z.unknown().optional(),
  response: zSchema.optional(),
  responseJsonSchema: z.unknown().optional(),
  behavior: z.enum(['UNSPECIFIED', 'BLOCKING', 'NON_BLOCKING']).optional(),
})

/**
 * Google search entry point.
 */
export const zSearchEntryPoint = z.object({
  renderedContent: z.string().optional(),
  sdkBlob: z.string().optional(),
})

/**
 * Identifier for a `Chunk` retrieved via Semantic Retriever specified in the `GenerateAnswerRequest` using `SemanticRetrieverConfig`.
 */
export const zSemanticRetrieverChunk = z.object({
  source: z.string().optional(),
  chunk: z.string().optional(),
})

/**
 * Identifier for the source contributing to this attribution.
 */
export const zAttributionSourceId = z.object({
  groundingPassage: zGroundingPassageId.optional(),
  semanticRetrieverChunk: zSemanticRetrieverChunk.optional(),
})

/**
 * A transport that can stream HTTP requests and responses. Next ID: 6
 */
export const zStreamableHttpTransport = z.object({
  url: z.string().optional(),
  headers: z.record(z.string(), z.string()).optional(),
  timeout: z.string().optional(),
  sseReadTimeout: z.string().optional(),
  terminateOnClose: z.boolean().optional(),
})

/**
 * A MCPServer is a server that can be called by the model to perform actions. It is a server that implements the MCP protocol. Next ID: 6
 */
export const zMcpServer = z.object({
  streamableHttpTransport: zStreamableHttpTransport.optional(),
  name: z.string().optional(),
})

/**
 * Output text returned from a model.
 */
export const zTextCompletion = z.object({
  output: z.string().optional(),
  safetyRatings: z.array(zSafetyRating).optional(),
  citationMetadata: zCitationMetadata.optional(),
})

/**
 * The response from the model, including candidate completions.
 */
export const zGenerateTextResponse = z.object({
  candidates: z.array(zTextCompletion).optional(),
  filters: z.array(zContentFilter).optional(),
  safetyFeedback: z.array(zSafetyFeedback).optional(),
})

/**
 * Text given to the model as a prompt. The Model will use this TextPrompt to Generate a text completion.
 */
export const zTextPrompt = z.object({
  text: z.string().optional(),
})

/**
 * Counts the number of tokens in the `prompt` sent to a model. Models may tokenize text differently, so each model may return a different `token_count`.
 */
export const zCountTextTokensRequest = z.object({
  prompt: zTextPrompt.optional(),
})

/**
 * Request to generate a text completion response from the model.
 */
export const zGenerateTextRequest = z.object({
  prompt: zTextPrompt.optional(),
  temperature: z.number().optional(),
  candidateCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  maxOutputTokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  topP: z.number().optional(),
  topK: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  safetySettings: z.array(zSafetySetting).optional(),
  stopSequences: z.array(z.string()).optional(),
})

/**
 * Configuration for text output format.
 */
export const zTextResponseFormat = z.object({
  mimeType: z
    .enum(['MIME_TYPE_UNSPECIFIED', 'APPLICATION_JSON', 'TEXT_PLAIN'])
    .optional(),
  schema: z.unknown().optional(),
})

/**
 * Configuration for the response output format. This is a flat object where each optional sub-field configures a specific output modality.
 */
export const zResponseFormatConfig = z.object({
  text: zTextResponseFormat.optional(),
  audio: zAudioResponseFormat.optional(),
  image: zImageResponseFormat.optional(),
})

/**
 * Config for thinking features.
 */
export const zThinkingConfig = z.object({
  includeThoughts: z.boolean().optional(),
  thinkingBudget: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  thinkingLevel: z
    .enum(['THINKING_LEVEL_UNSPECIFIED', 'MINIMAL', 'LOW', 'MEDIUM', 'HIGH'])
    .optional(),
})

/**
 * A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.
 */
export const zToolCall = z.object({
  id: z.string().optional(),
  toolType: z
    .enum([
      'TOOL_TYPE_UNSPECIFIED',
      'GOOGLE_SEARCH_WEB',
      'GOOGLE_SEARCH_IMAGE',
      'URL_CONTEXT',
      'GOOGLE_MAPS',
      'FILE_SEARCH',
    ])
    .optional(),
  args: z.record(z.string(), z.unknown()).optional(),
})

/**
 * The Tool configuration containing parameters for specifying `Tool` use in the request.
 */
export const zToolConfig = z.object({
  functionCallingConfig: zFunctionCallingConfig.optional(),
  retrievalConfig: zRetrievalConfig.optional(),
  includeServerSideToolInvocations: z.boolean().optional(),
})

/**
 * The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.
 */
export const zToolResponse = z.object({
  id: z.string().optional(),
  toolType: z
    .enum([
      'TOOL_TYPE_UNSPECIFIED',
      'GOOGLE_SEARCH_WEB',
      'GOOGLE_SEARCH_IMAGE',
      'URL_CONTEXT',
      'GOOGLE_MAPS',
      'FILE_SEARCH',
    ])
    .optional(),
  response: z.record(z.string(), z.unknown()).optional(),
})

/**
 * Candidates with top log probabilities at each decoding step.
 */
export const zTopCandidates = z.object({
  candidates: z.array(zLogprobsResultCandidate).optional(),
})

/**
 * Logprobs Result
 */
export const zLogprobsResult = z.object({
  logProbabilitySum: z.number().optional(),
  topCandidates: z.array(zTopCandidates).optional(),
  chosenCandidates: z.array(zLogprobsResultCandidate).optional(),
})

/**
 * Tool to support URL context retrieval.
 */
export const zUrlContext = z.record(z.string(), z.unknown())

/**
 * Context of the a single url retrieval.
 */
export const zUrlMetadata = z.object({
  retrievedUrl: z.string().optional(),
  urlRetrievalStatus: z
    .enum([
      'URL_RETRIEVAL_STATUS_UNSPECIFIED',
      'URL_RETRIEVAL_STATUS_SUCCESS',
      'URL_RETRIEVAL_STATUS_ERROR',
      'URL_RETRIEVAL_STATUS_PAYWALL',
      'URL_RETRIEVAL_STATUS_UNSAFE',
    ])
    .optional(),
})

/**
 * Metadata related to url context retrieval tool.
 */
export const zUrlContextMetadata = z.object({
  urlMetadata: z.array(zUrlMetadata).optional(),
})

/**
 * Metadata on the generation request's token usage.
 */
export const zUsageMetadata = z.object({
  promptTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  cachedContentTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  candidatesTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  toolUsePromptTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  thoughtsTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  totalTokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  promptTokensDetails: z.array(zModalityTokenCount).optional(),
  cacheTokensDetails: z.array(zModalityTokenCount).optional(),
  candidatesTokensDetails: z.array(zModalityTokenCount).optional(),
  toolUsePromptTokensDetails: z.array(zModalityTokenCount).optional(),
  serviceTier: z
    .enum(['unspecified', 'standard', 'flex', 'priority'])
    .optional(),
})

/**
 * Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.
 */
export const zVideoMetadata = z.object({
  startOffset: z.string().optional(),
  endOffset: z.string().optional(),
  fps: z.number().optional(),
})

/**
 * A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in `Part.data`. A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.
 */
export const zPart = z.object({
  text: z.string().optional(),
  inlineData: zBlob.optional(),
  functionCall: zFunctionCall.optional(),
  functionResponse: zFunctionResponse.optional(),
  fileData: zFileData.optional(),
  executableCode: zExecutableCode.optional(),
  codeExecutionResult: zCodeExecutionResult.optional(),
  toolCall: zToolCall.optional(),
  toolResponse: zToolResponse.optional(),
  videoMetadata: zVideoMetadata.optional(),
  thought: z.boolean().optional(),
  thoughtSignature: z.string().optional(),
  partMetadata: z.record(z.string(), z.unknown()).optional(),
  mediaResolution: zMediaResolution.optional(),
})

/**
 * The base structured datatype containing multi-part content of a message. A `Content` includes a `role` field designating the producer of the `Content` and a `parts` field containing multi-part data that contains the content of the message turn.
 */
export const zContent = z.object({
  parts: z.array(zPart).optional(),
  role: z.string().optional(),
})

/**
 * Attribution for a source that contributed to an answer.
 */
export const zGroundingAttribution = z.object({
  sourceId: zAttributionSourceId.optional(),
  content: zContent.optional(),
})

/**
 * Passage included inline with a grounding configuration.
 */
export const zGroundingPassage = z.object({
  id: z.string().optional(),
  content: zContent.optional(),
})

/**
 * A repeated list of passages.
 */
export const zGroundingPassages = z.object({
  passages: z.array(zGroundingPassage).optional(),
})

/**
 * Configuration for retrieving grounding content from a `Corpus` or `Document` created using the Semantic Retriever API.
 */
export const zSemanticRetrieverConfig = z.object({
  source: z.string().optional(),
  query: zContent.optional(),
  metadataFilters: z.array(zMetadataFilter).optional(),
  maxChunksCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  minimumRelevanceScore: z.number().optional(),
})

/**
 * Request to generate a grounded answer from the `Model`.
 */
export const zGenerateAnswerRequest = z.object({
  inlinePassages: zGroundingPassages.optional(),
  semanticRetriever: zSemanticRetrieverConfig.optional(),
  contents: z.array(zContent).optional(),
  answerStyle: z
    .enum(['ANSWER_STYLE_UNSPECIFIED', 'ABSTRACTIVE', 'EXTRACTIVE', 'VERBOSE'])
    .optional(),
  safetySettings: z.array(zSafetySetting).optional(),
  temperature: z.number().optional(),
})

/**
 * The configuration for the voice to use.
 */
export const zVoiceConfig = z.object({
  prebuiltVoiceConfig: zPrebuiltVoiceConfig.optional(),
})

/**
 * The configuration for a single speaker in a multi speaker setup.
 */
export const zSpeakerVoiceConfig = z.object({
  speaker: z.string().optional(),
  voiceConfig: zVoiceConfig.optional(),
})

/**
 * The configuration for the multi-speaker setup.
 */
export const zMultiSpeakerVoiceConfig = z.object({
  speakerVoiceConfigs: z.array(zSpeakerVoiceConfig).optional(),
})

/**
 * Config for speech generation and transcription.
 */
export const zSpeechConfig = z.object({
  voiceConfig: zVoiceConfig.optional(),
  multiSpeakerVoiceConfig: zMultiSpeakerVoiceConfig.optional(),
  languageCode: z.string().optional(),
})

/**
 * Configuration options for model generation and outputs. Not all parameters are configurable for every model.
 */
export const zGenerationConfig = z.object({
  candidateCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  stopSequences: z.array(z.string()).optional(),
  maxOutputTokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  temperature: z.number().optional(),
  topP: z.number().optional(),
  topK: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  seed: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  responseMimeType: z.string().optional(),
  responseSchema: zSchema.optional(),
  _responseJsonSchema: z.unknown().optional(),
  responseJsonSchema: z.unknown().optional(),
  presencePenalty: z.number().optional(),
  frequencyPenalty: z.number().optional(),
  responseLogprobs: z.boolean().optional(),
  logprobs: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  enableEnhancedCivicAnswers: z.boolean().optional(),
  responseModalities: z
    .array(z.enum(['MODALITY_UNSPECIFIED', 'TEXT', 'IMAGE', 'AUDIO']))
    .optional(),
  speechConfig: zSpeechConfig.optional(),
  thinkingConfig: zThinkingConfig.optional(),
  imageConfig: zImageConfig.optional(),
  mediaResolution: z
    .enum([
      'MEDIA_RESOLUTION_UNSPECIFIED',
      'MEDIA_RESOLUTION_LOW',
      'MEDIA_RESOLUTION_MEDIUM',
      'MEDIA_RESOLUTION_HIGH',
    ])
    .optional(),
  responseFormat: zResponseFormatConfig.optional(),
})

/**
 * Chunk from the web.
 */
export const zWeb = z.object({
  uri: z.string().optional(),
  title: z.string().optional(),
})

/**
 * A `GroundingChunk` represents a segment of supporting evidence that grounds the model's response. It can be a chunk from the web, a retrieved context from a file, or information from Google Maps.
 */
export const zGroundingChunk = z.object({
  web: zWeb.optional(),
  image: zImage.optional(),
  retrievedContext: zRetrievedContext.optional(),
  maps: zMaps.optional(),
})

/**
 * Metadata returned to client when grounding is enabled.
 */
export const zGroundingMetadata = z.object({
  searchEntryPoint: zSearchEntryPoint.optional(),
  groundingChunks: z.array(zGroundingChunk).optional(),
  groundingSupports: z
    .array(zGoogleAiGenerativelanguageV1BetaGroundingSupport)
    .optional(),
  retrievalMetadata: zRetrievalMetadata.optional(),
  webSearchQueries: z.array(z.string()).optional(),
  imageSearchQueries: z.array(z.string()).optional(),
  googleMapsWidgetContextToken: z.string().optional(),
})

/**
 * A response candidate generated from the model.
 */
export const zCandidate = z.object({
  index: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  content: zContent.optional(),
  finishReason: z
    .enum([
      'FINISH_REASON_UNSPECIFIED',
      'STOP',
      'MAX_TOKENS',
      'SAFETY',
      'RECITATION',
      'LANGUAGE',
      'OTHER',
      'BLOCKLIST',
      'PROHIBITED_CONTENT',
      'SPII',
      'MALFORMED_FUNCTION_CALL',
      'IMAGE_SAFETY',
      'IMAGE_PROHIBITED_CONTENT',
      'IMAGE_OTHER',
      'NO_IMAGE',
      'IMAGE_RECITATION',
      'UNEXPECTED_TOOL_CALL',
      'TOO_MANY_TOOL_CALLS',
      'MISSING_THOUGHT_SIGNATURE',
      'MALFORMED_RESPONSE',
    ])
    .optional(),
  finishMessage: z.string().optional(),
  safetyRatings: z.array(zSafetyRating).optional(),
  citationMetadata: zCitationMetadata.optional(),
  tokenCount: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    })
    .optional(),
  groundingAttributions: z.array(zGroundingAttribution).optional(),
  groundingMetadata: zGroundingMetadata.optional(),
  avgLogprobs: z.number().optional(),
  logprobsResult: zLogprobsResult.optional(),
  urlContextMetadata: zUrlContextMetadata.optional(),
})

/**
 * Response from the model for a grounded answer.
 */
export const zGenerateAnswerResponse = z.object({
  answer: zCandidate.optional(),
  answerableProbability: z.number().optional(),
  inputFeedback: zInputFeedback.optional(),
})

/**
 * Response from the model supporting multiple candidate responses. Safety ratings and content filtering are reported for both prompt in `GenerateContentResponse.prompt_feedback` and for each candidate in `finish_reason` and in `safety_ratings`. The API: - Returns either all requested candidates or none of them - Returns no candidates at all only if there was something wrong with the prompt (check `prompt_feedback`) - Reports feedback on each candidate in `finish_reason` and `safety_ratings`.
 */
export const zGenerateContentResponse = z.object({
  candidates: z.array(zCandidate).optional(),
  promptFeedback: zPromptFeedback.optional(),
  usageMetadata: zUsageMetadata.optional(),
  modelVersion: z.string().optional(),
  responseId: z.string().optional(),
  modelStatus: zModelStatus.optional(),
})

/**
 * Standard web search for grounding and related configurations.
 */
export const zWebSearch = z.record(z.string(), z.unknown())

/**
 * Different types of search that can be enabled on the GoogleSearch tool.
 */
export const zSearchTypes = z.object({
  webSearch: zWebSearch.optional(),
  imageSearch: zImageSearch.optional(),
})

/**
 * GoogleSearch tool type. Tool to support Google Search in Model. Powered by Google.
 */
export const zGoogleSearch = z.object({
  timeRangeFilter: zInterval.optional(),
  searchTypes: zSearchTypes.optional(),
})

/**
 * Tool details that the model may use to generate response. A `Tool` is a piece of code that enables the system to interact with external systems to perform an action, or set of actions, outside of knowledge and scope of the model. Next ID: 16
 */
export const zTool = z.object({
  functionDeclarations: z.array(zFunctionDeclaration).optional(),
  googleSearchRetrieval: zGoogleSearchRetrieval.optional(),
  codeExecution: zCodeExecution.optional(),
  googleSearch: zGoogleSearch.optional(),
  computerUse: zComputerUse.optional(),
  urlContext: zUrlContext.optional(),
  fileSearch: zFileSearch.optional(),
  mcpServers: z.array(zMcpServer).optional(),
  googleMaps: zGoogleMaps.optional(),
})

/**
 * Request to generate a completion from the model.
 */
export const zGenerateContentRequest = z.object({
  model: z.string().optional(),
  systemInstruction: zContent.optional(),
  contents: z.array(zContent).optional(),
  tools: z.array(zTool).optional(),
  toolConfig: zToolConfig.optional(),
  safetySettings: z.array(zSafetySetting).optional(),
  generationConfig: zGenerationConfig.optional(),
  cachedContent: z.string().optional(),
  serviceTier: z
    .enum(['unspecified', 'standard', 'flex', 'priority'])
    .optional(),
  store: z.boolean().optional(),
})

/**
 * Counts the number of tokens in the `prompt` sent to a model. Models may tokenize text differently, so each model may return a different `token_count`.
 */
export const zCountTokensRequest = z.object({
  contents: z.array(zContent).optional(),
  generateContentRequest: zGenerateContentRequest.optional(),
})

export const zGenerativelanguageDynamicGenerateContentBody =
  zGenerateContentRequest

export const zGenerativelanguageDynamicGenerateContentPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageDynamicGenerateContentResponse =
  zGenerateContentResponse

export const zGenerativelanguageDynamicStreamGenerateContentBody =
  zGenerateContentRequest

export const zGenerativelanguageDynamicStreamGenerateContentPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageDynamicStreamGenerateContentResponse =
  zGenerateContentResponse

export const zGenerativelanguageModelsCountMessageTokensBody =
  zCountMessageTokensRequest

export const zGenerativelanguageModelsCountMessageTokensPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsCountMessageTokensResponse =
  zCountMessageTokensResponse

export const zGenerativelanguageModelsCountTextTokensBody =
  zCountTextTokensRequest

export const zGenerativelanguageModelsCountTextTokensPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsCountTextTokensResponse =
  zCountTextTokensResponse

export const zGenerativelanguageModelsCountTokensBody = zCountTokensRequest

export const zGenerativelanguageModelsCountTokensPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsCountTokensResponse = zCountTokensResponse

export const zGenerativelanguageModelsGenerateAnswerBody =
  zGenerateAnswerRequest

export const zGenerativelanguageModelsGenerateAnswerPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsGenerateAnswerResponse =
  zGenerateAnswerResponse

export const zGenerativelanguageModelsGenerateContentBody =
  zGenerateContentRequest

export const zGenerativelanguageModelsGenerateContentPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsGenerateContentResponse =
  zGenerateContentResponse

export const zGenerativelanguageModelsGenerateMessageBody =
  zGenerateMessageRequest

export const zGenerativelanguageModelsGenerateMessagePath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsGenerateMessageResponse =
  zGenerateMessageResponse

export const zGenerativelanguageModelsGenerateTextBody = zGenerateTextRequest

export const zGenerativelanguageModelsGenerateTextPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsGenerateTextResponse =
  zGenerateTextResponse

export const zGenerativelanguageModelsStreamGenerateContentBody =
  zGenerateContentRequest

export const zGenerativelanguageModelsStreamGenerateContentPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageModelsStreamGenerateContentResponse =
  zGenerateContentResponse

export const zGenerativelanguageTunedModelsGenerateContentBody =
  zGenerateContentRequest

export const zGenerativelanguageTunedModelsGenerateContentPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageTunedModelsGenerateContentResponse =
  zGenerateContentResponse

export const zGenerativelanguageTunedModelsGenerateTextBody =
  zGenerateTextRequest

export const zGenerativelanguageTunedModelsGenerateTextPath = z.object({
  model: z.string(),
})

/**
 * Success
 */
export const zGenerativelanguageTunedModelsGenerateTextResponse =
  zGenerateTextResponse

export const zGenerativelanguageTunedModelsStreamGenerateContentBody =
  zGenerateContentRequest

export const zGenerativelanguageTunedModelsStreamGenerateContentPath = z.object(
  {
    model: z.string(),
  },
)

/**
 * Success
 */
export const zGenerativelanguageTunedModelsStreamGenerateContentResponse =
  zGenerateContentResponse
