// Generated by Wrangler by running `pnpm cf-typegen`.
// This is a stub so the example typechecks without a live `wrangler types` run.
// After editing wrangler.jsonc, run `pnpm cf-typegen` to overwrite.

interface Env {
  RUN_COORDINATOR: DurableObjectNamespace
  Sandbox: DurableObjectNamespace
  SANDBOX_TRANSPORT?: string
  XAI_API_KEY?: string
  GROK_API_KEY?: string
}
