// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const EmbeddingSchema = {
  type: 'object',
  required: ['index', 'embedding', 'object'],
  properties: {
    embedding: {
      $ref: '#/$defs/EmbeddingContent',
      description: 'Embedding content.',
    },
    index: {
      type: 'integer',
      format: 'int32',
      description: 'Index of the embedding object in the data list.',
    },
    object: {
      type: 'string',
      description: 'The object type, which is always `"embedding"`.',
    },
  },
  $defs: {
    EmbeddingContent: {
      oneOf: [
        { type: 'string', description: 'Embedding in base64 string.' },
        {
          type: 'array',
          items: { type: 'number', format: 'float' },
          description: 'Embedding as an array of floats.',
        },
      ],
    },
  },
} as const

export const EmbeddingContentSchema = {
  oneOf: [
    { type: 'string', description: 'Embedding in base64 string.' },
    {
      type: 'array',
      items: { type: 'number', format: 'float' },
      description: 'Embedding as an array of floats.',
    },
  ],
} as const

export const EmbeddingInputSchema = {
  oneOf: [
    {
      type: 'object',
      description:
        'A strings to be embedded. For best performance, prepend "query: " in front of query content and prepend "passage: " in front of passage/text',
      required: ['String'],
      properties: {
        String: {
          type: 'string',
          description:
            'A strings to be embedded. For best performance, prepend "query: " in front of query content and prepend "passage: " in front of passage/text',
        },
      },
    },
    {
      type: 'object',
      description: 'An array of strings to be embedded',
      required: ['StringArray'],
      properties: {
        StringArray: {
          type: 'array',
          items: { type: 'string' },
          description: 'An array of strings to be embedded',
        },
      },
    },
    {
      type: 'object',
      description: 'A token in integer to be embedded',
      required: ['Ints'],
      properties: {
        Ints: {
          type: 'array',
          items: { type: 'integer', format: 'int32' },
          description: 'A token in integer to be embedded',
        },
      },
    },
    {
      type: 'object',
      description: 'An array of tokens in integers to be embedded',
      required: ['IntsArray'],
      properties: {
        IntsArray: {
          type: 'array',
          items: { type: 'array', items: { type: 'integer', format: 'int32' } },
          description: 'An array of tokens in integers to be embedded',
        },
      },
    },
  ],
} as const

export const EmbeddingRequestSchema = {
  type: 'object',
  properties: {
    dimensions: {
      type: ['integer', 'null'],
      format: 'int32',
      description:
        'The number of dimensions the resulting output embeddings should have.',
    },
    encoding_format: {
      type: ['string', 'null'],
      description:
        'The format to return the embeddings in. Can be either `float` or `base64`.',
    },
    input: {
      $ref: '#/$defs/EmbeddingInput',
      description:
        'Input text to embed, encoded as a string or list of tokens. To embed multiple inputs in a single request, pass a list of strings or list of token lists. The total tokens in the input must not exceed the context window for the model and cannot be an empty string. If the input is a list, the maximum length of the list is 128.',
    },
    model: {
      type: 'string',
      description: 'ID of the model to use.',
      example: 'v1',
    },
    preview: {
      type: ['boolean', 'null'],
      description: 'Flag to use the new format of the API.',
    },
    user: {
      type: ['string', 'null'],
      description:
        'A unique identifier representing your end-user, which can help xAI to monitor and detect abuse.',
    },
  },
  $defs: {
    EmbeddingInput: {
      oneOf: [
        {
          type: 'object',
          description:
            'A strings to be embedded. For best performance, prepend "query: " in front of query content and prepend "passage: " in front of passage/text',
          required: ['String'],
          properties: {
            String: {
              type: 'string',
              description:
                'A strings to be embedded. For best performance, prepend "query: " in front of query content and prepend "passage: " in front of passage/text',
            },
          },
        },
        {
          type: 'object',
          description: 'An array of strings to be embedded',
          required: ['StringArray'],
          properties: {
            StringArray: {
              type: 'array',
              items: { type: 'string' },
              description: 'An array of strings to be embedded',
            },
          },
        },
        {
          type: 'object',
          description: 'A token in integer to be embedded',
          required: ['Ints'],
          properties: {
            Ints: {
              type: 'array',
              items: { type: 'integer', format: 'int32' },
              description: 'A token in integer to be embedded',
            },
          },
        },
        {
          type: 'object',
          description: 'An array of tokens in integers to be embedded',
          required: ['IntsArray'],
          properties: {
            IntsArray: {
              type: 'array',
              items: {
                type: 'array',
                items: { type: 'integer', format: 'int32' },
              },
              description: 'An array of tokens in integers to be embedded',
            },
          },
        },
      ],
    },
  },
} as const

export const EmbeddingResponseSchema = {
  type: 'object',
  required: ['object', 'model', 'data'],
  properties: {
    data: {
      type: 'array',
      items: { $ref: '#/$defs/Embedding' },
      description: 'A list of embedding objects.',
    },
    model: {
      type: 'string',
      description: 'Model ID used to create embedding.',
    },
    object: {
      type: 'string',
      description: 'The object type of `data` field, which is always `"list"`.',
    },
    usage: {
      oneOf: [
        { type: 'null' },
        {
          $ref: '#/$defs/EmbeddingUsage',
          description: 'Token usage information.',
        },
      ],
    },
  },
  $defs: {
    Embedding: {
      type: 'object',
      required: ['index', 'embedding', 'object'],
      properties: {
        embedding: {
          $ref: '#/$defs/EmbeddingContent',
          description: 'Embedding content.',
        },
        index: {
          type: 'integer',
          format: 'int32',
          description: 'Index of the embedding object in the data list.',
        },
        object: {
          type: 'string',
          description: 'The object type, which is always `"embedding"`.',
        },
      },
    },
    EmbeddingContent: {
      oneOf: [
        { type: 'string', description: 'Embedding in base64 string.' },
        {
          type: 'array',
          items: { type: 'number', format: 'float' },
          description: 'Embedding as an array of floats.',
        },
      ],
    },
    EmbeddingUsage: {
      type: 'object',
      required: ['prompt_tokens', 'total_tokens'],
      properties: {
        prompt_tokens: {
          type: 'integer',
          format: 'int32',
          description: 'Prompt token used.',
        },
        total_tokens: {
          type: 'integer',
          format: 'int32',
          description: 'Total token used.',
        },
      },
    },
  },
} as const

export const EmbeddingUsageSchema = {
  type: 'object',
  required: ['prompt_tokens', 'total_tokens'],
  properties: {
    prompt_tokens: {
      type: 'integer',
      format: 'int32',
      description: 'Prompt token used.',
    },
    total_tokens: {
      type: 'integer',
      format: 'int32',
      description: 'Total token used.',
    },
  },
} as const
