// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zEmbeddingContent = z.union([z.string(), z.array(z.number())])

export const zEmbedding = z.object({
  embedding: zEmbeddingContent,
  index: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  object: z.string(),
})

export const zEmbeddingInput = z.union([
  z.object({
    String: z.string(),
  }),
  z.object({
    StringArray: z.array(z.string()),
  }),
  z.object({
    Ints: z.array(
      z
        .int()
        .min(-2147483648, {
          error: 'Invalid value: Expected int32 to be >= -2147483648',
        })
        .max(2147483647, {
          error: 'Invalid value: Expected int32 to be <= 2147483647',
        }),
    ),
  }),
  z.object({
    IntsArray: z.array(
      z.array(
        z
          .int()
          .min(-2147483648, {
            error: 'Invalid value: Expected int32 to be >= -2147483648',
          })
          .max(2147483647, {
            error: 'Invalid value: Expected int32 to be <= 2147483647',
          }),
      ),
    ),
  }),
])

export const zEmbeddingRequest = z.object({
  dimensions: z.unknown().optional(),
  encoding_format: z.unknown().optional(),
  input: zEmbeddingInput.optional(),
  model: z.string().optional(),
  preview: z.unknown().optional(),
  user: z.unknown().optional(),
})

export const zEmbeddingUsage = z.object({
  prompt_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
  total_tokens: z
    .int()
    .min(-2147483648, {
      error: 'Invalid value: Expected int32 to be >= -2147483648',
    })
    .max(2147483647, {
      error: 'Invalid value: Expected int32 to be <= 2147483647',
    }),
})

export const zEmbeddingResponse = z.object({
  data: z.array(zEmbedding),
  model: z.string(),
  object: z.string(),
  usage: z.union([z.unknown(), zEmbeddingUsage]).optional(),
})

export const zHandleEmbeddingRequestBody = zEmbeddingRequest

/**
 * Success
 */
export const zHandleEmbeddingRequestResponse = zEmbeddingResponse
