import { memoryPersistence } from '@tanstack/ai-persistence'

/**
 * Server-side generation persistence for the example app — the counterpart to
 * `generation-persistence.ts`, which is the client-driven half.
 *
 * `memoryPersistence()` ships all three stores this needs: `generationRuns`
 * (the run record `reconstructGeneration` reads back) plus `artifacts` + `blobs`
 * (the generated bytes, so a restored `result` can actually render its image
 * rather than coming back `null`).
 *
 * Module-level on purpose: the POST that records a run and the GET that reads
 * it back are separate requests, so they have to share one instance. In-memory
 * means it resets when the dev server restarts — fine for a demo, and exactly
 * what the docs recommend for development. Point the stores at a durable
 * backend for production; `sqlite-persistence.ts` in this folder shows the
 * shape for the chat stores.
 */
export const generationServerPersistence = memoryPersistence()

/** Serve URL for a stored artifact — must match the GET route below it. */
export function artifactServeUrl(artifactId: string): string {
  return `/api/generate/image?artifact=${encodeURIComponent(artifactId)}`
}
