import { toolDefinition } from '@tanstack/ai'
import { z } from 'zod'
import type { ContentPart } from '@tanstack/ai'

/**
 * Repro for https://github.com/TanStack/ai/issues/363
 *
 * `getReproImage` returns a multimodal tool result — an array of `ContentPart`
 * (a text part + an image part). With multimodal tool results supported, the
 * OpenAI Responses adapter sends the image as a structured `input_image` in
 * `function_call_output.output`, so the model can actually see it. Before the
 * fix every tool result was `JSON.stringify`'d and the model never received the
 * image.
 *
 * The image is a PNG showing a fixed 3-digit secret number ({@link REPRO_SECRET})
 * rendered as black pixels on white. The number appears nowhere in any text the
 * tool returns, so a model that can genuinely see the image can read it back and
 * a model that only received stringified JSON cannot — a clean pass/fail signal
 * that a blind model cannot fake (1-in-1000 to guess).
 *
 * Generated by `scripts/make-repro-image.mjs` (also written to
 * `public/repro-secret.png` for human comparison). Keep REPRO_SECRET in sync
 * with the SECRET constant in that script.
 */
export const REPRO_SECRET = '473'

const REPRO_IMAGE_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAOAAAACACAIAAACdu/LsAAAEIElEQVR4nO2SgWkAMRDDfv+l2wlSaJA5JbEG8FmHv59SxHzTBUr5iw60qOlAi5oOtKjpQIuaDrSo6UCLmg60qOlAi5oOtKjpQIuaDrSo6UCLmg60qOlAi5oOtKjpQIuaDrSo6UCLmg60qOlAi5oOtKjpQIsabKDfPzk9P81r/ZdeWFBYwJaf5rX+Sy8sKCxgy0/zWv+lFxYUFrDlp3mt/9ILCwoL2PLTvNZ/6YUFhQVs+Wle67/0woLCArb8NK/1X3phQWEBW36a1/ovvbCgsIAtP81r/ZdeWFBYwJaf5rX+Sy8sKCxgy0/zWv+lFxYUFrDlp3mt/9ILCwoL2PLTvNZ/6YUFhQVs+Wle67/0woLCArb8NK/1X3phQWEBW36a1/ovvbCgsMDUgyjaf/MuFhQWmHoQRftv3sWCwgJTD6Jo/827WFBYYOpBFO2/eRcLCgtMPYii/TfvYkFhgakHUbT/5l0sKCww9SCK9t+8iwWFBaYeRNH+m3exoLDA1IMo2n/zLhYUFph6EEX7b97FgsICUw+iaP/Nu1hQWGDqQRTtv3kXCwoLTD2Iov0372JBYYGpB1G0/+ZdLCgsMPUgivbfvIsFhQWmHkTR/pt3sSAZlBfla+uTBvPCgmRQXpSvrU8azAsLkkF5Ub62PmkwLyxIBuVF+dr6pMG8sCAZlBfla+uTBvPCgmRQXpSvrU8azAsLkkF5Ub62PmkwLyxIBuVF+dr6pMG8sCAZlBfla+uTBvPCgmRQXpSvrU8azAsLkkF5Ub62PmkwLyxIBuVF+dr6pMG8sCAZlBfla+uTBvPCgmRQXpSvrU8azAsLkkF5Ub62PmkwLyxIBuVF+dr6pMG8qKA0Uw86pU+aKd9jHmcbhK1PminfYx5nG4StT5op32MeZxuErU+aKd9jHmcbhK1PminfYx5nG4StT5op32MeZxuErU+aKd9jHmcbhK1PminfYx5nG4StT5op32MeZxuErU+aKd9jHmcbhK1PminfYx5nG4StT5op32MeZxuErU+aKd9jHmcbhK1PminfYx5nG4StT5op32MeZxuErU+aKd9jHmcbxOl90mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFpZl60K190mBeVFCaqQfd2icN5kUFlZKgAy1qOtCipgMtajrQoqYDLWo60KKmAy1qOtCipgMtajrQoqYDLWo60KKmAy1qOtCipgMtajrQoqYDLWo60KKmAy1qOtCipgMtajrQoqYDLWp+ARIFD+N3ElIHAAAAAElFTkSuQmCC'

export const getReproImageToolDef = toolDefinition({
  name: 'getReproImage',
  description:
    'Returns an image for the user to inspect. Call this whenever the user asks you to look at, view, or describe the image.',
  inputSchema: z.object({}),
})

// Server implementation: returns a multimodal content-part array, NOT a string.
export const getReproImage = getReproImageToolDef.server(
  (): Array<ContentPart> => [
    {
      type: 'text',
      content:
        'Here is the image you asked to inspect. Read whatever it shows.',
    },
    {
      type: 'image',
      source: {
        type: 'data',
        value: REPRO_IMAGE_BASE64,
        mimeType: 'image/png',
      },
    },
  ],
)
