// Generated by scripts/sync-model-reasoning.ts from models.dev. Do not edit.
import type { ModelReasoning } from '@tanstack/ai'

/**
 * Each model's reasoning levels, and whether it takes a token budget, for
 * `chat({ reasoning })`. A model that is not here does not reason.
 */
export type BytePlusModelReasoningByName = {
  'seed-2-0-lite-260428': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-2-0-mini-260428': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-2-0-pro-260328': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-2-0-code-preview-260328': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-1-8-251228': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-1-6-250915': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-1-6-250615': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'seed-1-6-flash-250715': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'glm-5-2-260617': {
    levels: 'off' | 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
}

/** The same data at runtime. `false`: the model does not reason. */
export const BYTEPLUS_MODEL_REASONING: Readonly<
  Record<string, ModelReasoning>
> = {
  'seed-2-0-lite-260428': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-2-0-mini-260428': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-2-0-pro-260328': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-2-0-code-preview-260328': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-1-8-251228': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-1-6-250915': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-1-6-250615': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'seed-1-6-flash-250715': {
    map: {
      off: null,
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
  'glm-5-2-260617': {
    map: {
      off: 'none',
      minimal: 'minimal',
      low: 'low',
      medium: 'medium',
      high: 'high',
      xhigh: null,
      max: null,
    },
    budget: false,
  },
}
