/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImageGenRouteImport } from './routes/image-gen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTanchatRouteImport } from './routes/api.tanchat'
import { Route as ApiImageGenRouteImport } from './routes/api.image-gen'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'

const ImageGenRoute = ImageGenRouteImport.update({
  id: '/image-gen',
  path: '/image-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTanchatRoute = ApiTanchatRouteImport.update({
  id: '/api/tanchat',
  path: '/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageGenRoute = ApiImageGenRouteImport.update({
  id: '/api/image-gen',
  path: '/api/image-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-gen': typeof ImageGenRoute
  '/api/image-gen': typeof ApiImageGenRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-gen': typeof ImageGenRoute
  '/api/image-gen': typeof ApiImageGenRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-gen': typeof ImageGenRoute
  '/api/image-gen': typeof ApiImageGenRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image-gen'
    | '/api/image-gen'
    | '/api/tanchat'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image-gen'
    | '/api/image-gen'
    | '/api/tanchat'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
  id:
    | '__root__'
    | '/'
    | '/image-gen'
    | '/api/image-gen'
    | '/api/tanchat'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageGenRoute: typeof ImageGenRoute
  ApiImageGenRoute: typeof ApiImageGenRoute
  ApiTanchatRoute: typeof ApiTanchatRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/image-gen': {
      id: '/image-gen'
      path: '/image-gen'
      fullPath: '/image-gen'
      preLoaderRoute: typeof ImageGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tanchat': {
      id: '/api/tanchat'
      path: '/api/tanchat'
      fullPath: '/api/tanchat'
      preLoaderRoute: typeof ApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-gen': {
      id: '/api/image-gen'
      path: '/api/image-gen'
      fullPath: '/api/image-gen'
      preLoaderRoute: typeof ApiImageGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars/'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageGenRoute: ImageGenRoute,
  ApiImageGenRoute: ApiImageGenRoute,
  ApiTanchatRoute: ApiTanchatRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
