// Generated by scripts/generate-ai-models.ts from models.dev. Do not edit.
import type { ModelRecord, ProviderRecord } from '../types'

/** Xiaomi MiMo Token Plan (Amsterdam). */
export const provider: ProviderRecord = {
  id: 'xiaomi-token-plan-ams',
  name: 'Xiaomi MiMo Token Plan (Amsterdam)',
  baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
  apis: ['openai-completions'],
  env: [['XIAOMI_TOKEN_PLAN_AMS_API_KEY']],
}

/** Every Xiaomi MiMo Token Plan (Amsterdam) model, sorted by id. */
export const models: ReadonlyArray<ModelRecord> = [
  {
    id: 'mimo-v2.5',
    provider: 'xiaomi-token-plan-ams',
    name: 'MiMo-V2.5',
    api: 'openai-completions',
    baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
    input: ['text', 'image', 'audio', 'video'],
    reasoning: true,
    reasoningMap: {
      off: 'off',
      minimal: null,
      low: null,
      medium: null,
      high: 'high',
    },
    cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
    contextWindow: 1048576,
    maxTokens: 131072,
    compat: {
      supportsStrictMode: true,
      requiresReasoningContentOnAssistantMessages: true,
      thinkingFormat: 'deepseek',
    },
  },
  {
    id: 'mimo-v2.5-pro',
    provider: 'xiaomi-token-plan-ams',
    name: 'MiMo-V2.5-Pro',
    api: 'openai-completions',
    baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
    input: ['text'],
    reasoning: true,
    reasoningMap: {
      off: 'off',
      minimal: null,
      low: null,
      medium: null,
      high: 'high',
    },
    cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
    contextWindow: 1048576,
    maxTokens: 131072,
    compat: {
      supportsStrictMode: true,
      requiresReasoningContentOnAssistantMessages: true,
      thinkingFormat: 'deepseek',
    },
  },
  {
    id: 'mimo-v2.6-flash',
    provider: 'xiaomi-token-plan-ams',
    name: 'MiMo-V2.6-Flash',
    api: 'openai-completions',
    baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
    input: ['text', 'image', 'audio', 'video'],
    reasoning: true,
    reasoningMap: {
      off: 'off',
      minimal: null,
      low: null,
      medium: null,
      high: 'high',
    },
    cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
    contextWindow: 1048576,
    maxTokens: 131072,
    compat: {
      supportsStrictMode: true,
      requiresReasoningContentOnAssistantMessages: true,
      thinkingFormat: 'deepseek',
    },
  },
  {
    id: 'mimo-v2.6-pro',
    provider: 'xiaomi-token-plan-ams',
    name: 'MiMo-V2.6-Pro',
    api: 'openai-completions',
    baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
    input: ['text', 'image', 'audio', 'video'],
    reasoning: true,
    reasoningMap: {
      off: 'off',
      minimal: null,
      low: null,
      medium: null,
      high: 'high',
    },
    cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
    contextWindow: 1048576,
    maxTokens: 131072,
    compat: {
      supportsStrictMode: true,
      requiresReasoningContentOnAssistantMessages: true,
      thinkingFormat: 'deepseek',
    },
  },
]
