// Generated by scripts/sync-model-reasoning.ts from models.dev. Do not edit.
import type { ModelReasoning } from '@tanstack/ai'

/**
 * Each model's reasoning levels, and whether it takes a token budget, for
 * `chat({ reasoning })`. A model that is not here does not reason.
 */
export type LovableModelReasoningByName = {
  'google/gemini-3.7-flash': {
    levels: 'low' | 'medium' | 'high'
    budget: false
  }
  'google/gemini-3.6-flash': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'google/gemini-3.5-flash': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'google/gemini-3.1-pro-preview': {
    levels: 'low' | 'medium' | 'high'
    budget: false
  }
  'google/gemini-3.1-flash-lite': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'google/gemini-3-flash-preview': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'google/gemini-2.5-pro': {
    levels: 'off' | 'minimal' | 'low' | 'medium' | 'high'
    budget: true
  }
  'google/gemini-2.5-flash': { levels: 'off' | 'high'; budget: true }
  'google/gemini-2.5-flash-lite': { levels: 'off' | 'high'; budget: true }
  'openai/gpt-5.6-sol': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
    budget: false
  }
  'openai/gpt-5.6-terra': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
    budget: false
  }
  'openai/gpt-5.6-luna': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
    budget: false
  }
  'openai/gpt-5.5-pro': { levels: 'medium' | 'high' | 'xhigh'; budget: false }
  'openai/gpt-5.5': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh'
    budget: false
  }
  'openai/gpt-5.4-pro': { levels: 'medium' | 'high' | 'xhigh'; budget: false }
  'openai/gpt-5.4': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh'
    budget: false
  }
  'openai/gpt-5.4-mini': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh'
    budget: false
  }
  'openai/gpt-5.4-nano': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh'
    budget: false
  }
  'openai/gpt-5.2': {
    levels: 'off' | 'low' | 'medium' | 'high' | 'xhigh'
    budget: false
  }
  'openai/gpt-5': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'openai/gpt-5-mini': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
  'openai/gpt-5-nano': {
    levels: 'minimal' | 'low' | 'medium' | 'high'
    budget: false
  }
}

/** The same data at runtime. `false`: the model does not reason. */
export const LOVABLE_MODEL_REASONING: Readonly<Record<string, ModelReasoning>> =
  {
    'google/gemini-3.7-flash': {
      map: {
        off: null,
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'google/gemini-3.6-flash': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'google/gemini-3.5-flash': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'google/gemini-3.1-pro-preview': {
      map: {
        off: null,
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'google/gemini-3.1-flash-lite': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'google/gemini-3-flash-preview': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'google/gemini-2.5-pro': { budget: true },
    'google/gemini-2.5-flash': {
      map: { off: 'off', minimal: null, low: null, medium: null, high: 'high' },
      budget: true,
    },
    'google/gemini-2.5-flash-lite': {
      map: { off: 'off', minimal: null, low: null, medium: null, high: 'high' },
      budget: true,
    },
    'openai/gpt-5.6-sol': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: 'max',
      },
      budget: false,
    },
    'openai/gpt-5.6-terra': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: 'max',
      },
      budget: false,
    },
    'openai/gpt-5.6-luna': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: 'max',
      },
      budget: false,
    },
    'openai/gpt-5.5-pro': {
      map: {
        off: null,
        minimal: null,
        low: null,
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5.5': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5.4-pro': {
      map: {
        off: null,
        minimal: null,
        low: null,
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5.4': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5.4-mini': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5.4-nano': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5.2': {
      map: {
        off: 'none',
        minimal: null,
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: 'xhigh',
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5-mini': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
    'openai/gpt-5-nano': {
      map: {
        off: null,
        minimal: 'minimal',
        low: 'low',
        medium: 'medium',
        high: 'high',
        xhigh: null,
        max: null,
      },
      budget: false,
    },
  }
