import { compile } from 'json-schema-to-typescript'
import type { ServerSurface } from './introspect'

function pascal(name: string): string {
  const base = name
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
  const safe = base || 'Generated'
  return /^[A-Za-z_]/.test(safe) ? safe : `_${safe}`
}

/** Escape a value as a TypeScript string literal (handles quotes/newlines). */
function tsString(value: string): string {
  return JSON.stringify(value)
}

async function schemaToType(
  schema: unknown,
  typeName: string,
): Promise<string> {
  if (!schema) return 'unknown'
  if (typeof schema !== 'object') return 'unknown'
  const compiled = await compile(schema, typeName, {
    bannerComment: '',
    additionalProperties: false,
    declareExternallyReferenced: true,
  })
  return compiled.trim()
}

export interface EmitInput {
  [serverName: string]: { prefix?: string; surface: ServerSurface }
}

export async function emitDescriptors(input: EmitInput): Promise<string> {
  const blocks: Array<string> = [
    '// AUTO-GENERATED by `npx @tanstack/ai-mcp generate`. Do not edit.',
    "import type { ServerDescriptor } from '@tanstack/ai-mcp'",
    '',
  ]
  // Track config-key -> interface-name so we can emit the combined pool map.
  const mapEntries: Array<[string, string]> = []
  const seenIfaces = new Set<string>()
  const servers = Object.entries(input)
  for (const [serverName, { prefix, surface }] of servers) {
    const iface = `${pascal(serverName)}Server`
    if (seenIfaces.has(iface)) {
      throw new Error(
        `Interface name collision for server key "${serverName}" -> ${iface}. ` +
          `Rename one of the colliding servers in your codegen config.`,
      )
    }
    seenIfaces.add(iface)
    mapEntries.push([serverName, iface])
    const toolEntries: Array<string> = []
    for (const tool of surface.tools) {
      const key = prefix ? `${prefix}_${tool.name}` : tool.name
      const inputType = await schemaToType(
        tool.inputSchema,
        `${pascal(key)}Input`,
      )
      const outputType = tool.outputSchema
        ? await schemaToType(tool.outputSchema, `${pascal(key)}Output`)
        : 'unknown'
      // Inline the compiled interface bodies as anonymous object types.
      toolEntries.push(
        `    ${tsString(key)}: { input: ${inlineBody(inputType)}; output: ${inlineBody(outputType)} }`,
      )
    }
    blocks.push(
      `export interface ${iface} extends ServerDescriptor {`,
      `  tools: {`,
      toolEntries.join('\n'),
      `  }`,
      `  resources: ${emitResources(surface)}`,
      `  prompts: ${emitPrompts(surface)}`,
      `  capabilities: ${JSON.stringify(surface.capabilities)} & Record<string, unknown>`,
      `}`,
      '',
    )
  }
  blocks.push(
    'export interface MCPServers extends Record<string, ServerDescriptor> {',
    ...mapEntries.map(([key, iface]) => `  ${tsString(key)}: ${iface}`),
    '}',
    '',
  )
  return blocks.join('\n')
}

function inlineBody(compiled: string): string {
  const brace = compiled.indexOf('{')
  return brace >= 0
    ? compiled.slice(brace).replace(/\n/g, ' ').trim()
    : 'unknown'
}

function emitResources(s: ServerSurface): string {
  if (!s.resources.length) return '{}'
  return `{ ${s.resources
    .map(
      (r) => `${tsString(r.uri)}: { uri: ${tsString(r.uri)}; data: unknown }`,
    )
    .join('; ')} }`
}

function emitPrompts(s: ServerSurface): string {
  if (!s.prompts.length) return '{}'
  return `{ ${s.prompts
    .map(
      (p) =>
        `${tsString(p.name)}: { args: Record<string, string>; messages: unknown }`,
    )
    .join('; ')} }`
}
