/**
 * Converts Vercel AI Gateway catalog rows into packages/ai-vercel-gateway/src/model-meta.ts.
 *
 * Usage:
 *   pnpm tsx scripts/convert-vercel-gateway-models.ts
 */

import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { models } from './vercel-gateway.models'
import type { VercelGatewayCatalogModel } from './vercel-gateway.models'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(
  __dirname,
  '../packages/ai-vercel-gateway/src/model-meta.ts',
)

type CatalogKind =
  | 'language'
  | 'embedding'
  | 'image'
  | 'video'
  | 'reranking'
  | 'other'

const TYPE_ALIASES: Record<string, CatalogKind> = {
  language: 'language',
  chat: 'language',
  embedding: 'embedding',
  embeddings: 'embedding',
  image: 'image',
  video: 'video',
  reranking: 'reranking',
  rerank: 'reranking',
}

function classifyModel(model: VercelGatewayCatalogModel): CatalogKind {
  const type = typeof model.type === 'string' ? model.type.toLowerCase() : ''
  if (type in TYPE_ALIASES) {
    return TYPE_ALIASES[type]!
  }

  const id = model.id
  if (/embed/i.test(id)) return 'embedding'
  if (/image|dall-e|imagen|flux|seedream/i.test(id)) return 'image'
  if (/rerank/i.test(id)) return 'reranking'
  if (/video|veo|sora|seedance/i.test(id)) return 'video'
  return 'language'
}

function formatStringArray(ids: Array<string>): string {
  if (ids.length === 0) {
    return '[] as const'
  }
  return `[\n${ids.map((id) => `  ${JSON.stringify(id)},`).join('\n')}\n] as const`
}

function convertModels(): string {
  const chat: Array<string> = []
  const embedding: Array<string> = []
  const image: Array<string> = []
  let video = 0
  let reranking = 0
  let other = 0

  for (const model of models) {
    const kind = classifyModel(model)
    switch (kind) {
      case 'language':
        chat.push(model.id)
        break
      case 'embedding':
        embedding.push(model.id)
        break
      case 'image':
        image.push(model.id)
        break
      case 'video':
        video += 1
        break
      case 'reranking':
        reranking += 1
        break
      default:
        other += 1
    }
  }

  chat.sort((a, b) => a.localeCompare(b))
  embedding.sort((a, b) => a.localeCompare(b))
  image.sort((a, b) => a.localeCompare(b))

  if (chat.length === 0) {
    throw new Error(
      'Vercel AI Gateway catalog produced no chat models. Refusing to overwrite model-meta.ts.',
    )
  }
  if (embedding.length === 0) {
    throw new Error(
      'Vercel AI Gateway catalog produced no embedding models. Refusing to overwrite model-meta.ts.',
    )
  }
  if (image.length === 0) {
    throw new Error(
      'Vercel AI Gateway catalog produced no image models. Refusing to overwrite model-meta.ts.',
    )
  }

  console.log(
    `Classified ${models.length} models: chat=${chat.length} embedding=${embedding.length} image=${image.length} video=${video} reranking=${reranking} other=${other}`,
  )

  return `/**
 * This file is generated by scripts/convert-vercel-gateway-models.ts. Do not edit by hand.
 */

import type { VercelGatewayEmbeddingProviderOptions } from './embedding/embedding-provider-options'
import type {
  VercelGatewayImageProviderOptions,
  VercelGatewayImageSize,
} from './image/image-provider-options'
import type { VercelGatewayTextProviderOptions } from './text/text-provider-options'

export const VERCEL_GATEWAY_CHAT_MODELS = ${formatStringArray(chat)}

export type VercelGatewayChatModel = (typeof VERCEL_GATEWAY_CHAT_MODELS)[number]

export const VERCEL_GATEWAY_EMBEDDING_MODELS = ${formatStringArray(embedding)}

export type VercelGatewayEmbeddingModel =
  (typeof VERCEL_GATEWAY_EMBEDDING_MODELS)[number]

export const VERCEL_GATEWAY_IMAGE_MODELS = ${formatStringArray(image)}

export type VercelGatewayImageModel =
  (typeof VERCEL_GATEWAY_IMAGE_MODELS)[number]

export type VercelGatewayChatModelProviderOptionsByName = {
  [K in VercelGatewayChatModel]: VercelGatewayTextProviderOptions
}

export type VercelGatewayModelInputModalitiesByName = {
  [K in VercelGatewayChatModel]: readonly ['text', 'image']
}

export type VercelGatewayChatModelToolCapabilitiesByName = {
  [K in VercelGatewayChatModel]: readonly []
}

export type VercelGatewayEmbeddingModelProviderOptionsByName = {
  [K in VercelGatewayEmbeddingModel]: VercelGatewayEmbeddingProviderOptions
}

export type VercelGatewayEmbeddingModelInputModalitiesByName = {
  [K in VercelGatewayEmbeddingModel]: readonly ['text']
}

export type VercelGatewayImageModelProviderOptionsByName = {
  [K in VercelGatewayImageModel]: VercelGatewayImageProviderOptions
}

export type VercelGatewayImageModelSizeByName = {
  [K in VercelGatewayImageModel]: VercelGatewayImageSize
}

export type VercelGatewayImageModelInputModalitiesByName = {
  [K in VercelGatewayImageModel]: readonly []
}

export type ResolveProviderOptions<TModel extends string> =
  TModel extends keyof VercelGatewayChatModelProviderOptionsByName
    ? VercelGatewayChatModelProviderOptionsByName[TModel]
    : TModel extends VercelGatewayEmbeddingModel
      ? VercelGatewayEmbeddingProviderOptions
      : TModel extends VercelGatewayImageModel
        ? VercelGatewayImageProviderOptions
        : VercelGatewayTextProviderOptions

export type ResolveInputModalities<TModel extends string> =
  TModel extends keyof VercelGatewayModelInputModalitiesByName
    ? VercelGatewayModelInputModalitiesByName[TModel]
    : readonly ['text']
`
}

async function main() {
  const file = convertModels()
  await writeFile(OUTPUT_PATH, file, 'utf-8')
  console.log(`Model meta file written to ${OUTPUT_PATH}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
