/**
 * Generates the package catalogs the repo-level skills in `skills/` use for
 * capability discovery. Catalogs are derived from `packages/*` so a new package
 * shows up without anyone editing a skill by hand.
 *
 * Run `pnpm generate:plugin-catalog` to write them; the test asserts they are
 * current.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export type Category = 'core' | 'providers' | 'clients' | 'agents' | 'state'

export type Entry = {
  name: string
  description: string
  skills: Array<string>
  category: Category
}

const CORE = ['@tanstack/ai', '@tanstack/ai-utils', '@tanstack/openai-base']

const CLIENTS = [
  '@tanstack/ai-angular',
  '@tanstack/ai-client',
  '@tanstack/ai-devtools-core',
  '@tanstack/ai-octane',
  '@tanstack/ai-preact',
  '@tanstack/ai-react',
  '@tanstack/ai-react-ui',
  '@tanstack/ai-remix',
  '@tanstack/ai-solid',
  '@tanstack/ai-solid-ui',
  '@tanstack/ai-svelte',
  '@tanstack/ai-vue',
  '@tanstack/ai-vue-ui',
]

const STATE = [
  '@tanstack/ai-compaction',
  '@tanstack/ai-durable-stream',
  '@tanstack/ai-persistence',
]

const AGENTS = [
  '@tanstack/ai-acp',
  '@tanstack/ai-claude-code',
  '@tanstack/ai-codex',
  '@tanstack/ai-grok-build',
  '@tanstack/ai-mcp',
  '@tanstack/ai-memory',
  '@tanstack/ai-opencode',
  '@tanstack/ai-skills',
]

/**
 * Provider adapters are the default: a new provider lands in the right catalog
 * with no edit here. Everything else is listed above or matched by prefix.
 */
export function categorize(name: string): Category {
  if (CORE.includes(name)) return 'core'
  if (CLIENTS.includes(name) || name.endsWith('-ai-devtools')) return 'clients'
  if (STATE.includes(name)) return 'state'
  if (
    AGENTS.includes(name) ||
    name.startsWith('@tanstack/ai-code-mode') ||
    name.startsWith('@tanstack/ai-isolate-') ||
    name.startsWith('@tanstack/ai-sandbox')
  ) {
    return 'agents'
  }
  return 'providers'
}

export function collectPackages(packagesDir: string): Array<Entry> {
  const entries: Array<Entry> = []

  for (const dir of readdirSync(packagesDir)) {
    const manifestPath = join(packagesDir, dir, 'package.json')
    if (!existsSync(manifestPath)) continue

    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
      name?: string
      private?: boolean
      description?: string
    }
    if (!manifest.name || manifest.private) continue

    const skillsDir = join(packagesDir, dir, 'skills')
    entries.push({
      name: manifest.name,
      description: manifest.description ?? '',
      skills: existsSync(skillsDir) ? readdirSync(skillsDir).sort() : [],
      category: categorize(manifest.name),
    })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

const HEADER =
  '<!-- Generated by scripts/generate-plugin-catalog.ts. Run `pnpm generate:plugin-catalog`. -->'

const INTRO = `Packages with a skill ship their own \`SKILL.md\`. Once the package is
installed, read \`node_modules/<package>/skills/<skill>/SKILL.md\` instead of
guessing at the API. Packages without one are documented at
https://tanstack.com/ai/latest/docs and in their own \`src\` directory, which
ships in the published package.`

function table(entries: Array<Entry>): string {
  const rows = entries.map((entry) => {
    const skills = entry.skills.length
      ? entry.skills.map((skill) => `\`${skill}\``).join(', ')
      : '—'
    return `| \`${entry.name}\` | ${skills} | ${entry.description.replaceAll('|', '\\|')} |`
  })

  return [
    '| Package | Skills | What it does |',
    '| --- | --- | --- |',
    ...rows,
  ].join('\n')
}

export function renderCatalog(title: string, entries: Array<Entry>): string {
  return `# ${title}\n\n${HEADER}\n\n${INTRO}\n\n${table(entries)}\n`
}

/** Catalog file path → its rendered content. */
export function buildCatalogs(packagesDir: string): Record<string, string> {
  const all = collectPackages(packagesDir)
  const of = (category: Category) => all.filter((e) => e.category === category)

  return {
    'skills/tanstack-ai/packages.md': renderCatalog(
      'Every TanStack AI package',
      all,
    ),
    'skills/tanstack-ai-providers/packages.md': renderCatalog(
      'Provider adapters',
      of('providers'),
    ),
    'skills/tanstack-ai-clients/packages.md': renderCatalog(
      'Client and framework packages',
      of('clients'),
    ),
    'skills/tanstack-ai-agents/packages.md': renderCatalog(
      'Agent, tool, and sandbox packages',
      of('agents'),
    ),
    'skills/tanstack-ai-state/packages.md': renderCatalog(
      'State and delivery packages',
      of('state'),
    ),
  }
}

if (process.argv[1]?.endsWith('generate-plugin-catalog.ts')) {
  const catalogs = buildCatalogs('packages')
  const check = process.argv.includes('--check')
  let stale = false

  for (const [path, content] of Object.entries(catalogs)) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : ''
    if (current === content) continue
    if (check) {
      console.error(`${path} is out of date.`)
      stale = true
    } else {
      writeFileSync(path, content)
      console.log(`Wrote ${path}.`)
    }
  }

  if (stale) {
    console.error('Run `pnpm generate:plugin-catalog`.')
    process.exit(1)
  }
}
