/**
 * Generates the package catalog the `tanstack-ai` marketplace plugin uses for
 * capability discovery. The catalog is derived from `packages/*` so a new
 * package shows up without anyone editing the skill by hand.
 *
 * Run `pnpm generate:plugin-catalog` to write it; the test asserts it is current.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export const CATALOG_PATH = 'plugins/tanstack-ai/skills/tanstack-ai/packages.md'

type Entry = { name: string; description: string; skills: Array<string> }

export function collectPackages(packagesDir: string): Array<Entry> {
  const entries: Array<Entry> = []

  for (const dir of readdirSync(packagesDir)) {
    const manifestPath = join(packagesDir, dir, 'package.json')
    if (!existsSync(manifestPath)) continue

    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
      name?: string
      private?: boolean
      description?: string
    }
    if (!manifest.name || manifest.private) continue

    const skillsDir = join(packagesDir, dir, 'skills')
    entries.push({
      name: manifest.name,
      description: manifest.description ?? '',
      skills: existsSync(skillsDir) ? readdirSync(skillsDir).sort() : [],
    })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

export function renderCatalog(entries: Array<Entry>): string {
  const rows = entries.map((entry) => {
    const skills = entry.skills.length
      ? entry.skills.map((skill) => `\`${skill}\``).join(', ')
      : '—'
    const description = entry.description.replaceAll('|', '\\|')
    return `| \`${entry.name}\` | ${skills} | ${description} |`
  })

  return `# TanStack AI package catalog

<!-- Generated by scripts/generate-plugin-catalog.ts. Run \`pnpm generate:plugin-catalog\`. -->

Every published TanStack AI package. Packages in the **Skills** column ship
their own \`SKILL.md\` files — once installed, read
\`node_modules/<package>/skills/<skill>/SKILL.md\` instead of guessing at the
API. Packages without skills are documented at
https://tanstack.com/ai/latest/docs and in their README.

| Package | Skills | What it does |
| --- | --- | --- |
${rows.join('\n')}
`
}

export function buildCatalog(packagesDir: string): string {
  return renderCatalog(collectPackages(packagesDir))
}

if (process.argv[1]?.endsWith('generate-plugin-catalog.ts')) {
  const catalog = buildCatalog('packages')
  if (process.argv.includes('--check')) {
    const current = existsSync(CATALOG_PATH)
      ? readFileSync(CATALOG_PATH, 'utf8')
      : ''
    if (current !== catalog) {
      console.error(
        `${CATALOG_PATH} is out of date. Run \`pnpm generate:plugin-catalog\`.`,
      )
      process.exit(1)
    }
    console.log(`${CATALOG_PATH} is up to date.`)
  } else {
    writeFileSync(CATALOG_PATH, catalog)
    console.log(`Wrote ${CATALOG_PATH}.`)
  }
}
