/**
 * Hand-written wrapper. DO NOT regenerate this file.
 *
 * The model data lives in `lovable-gateway.models.json` (regenerated by
 * `fetch-lovable-gateway-models.ts`). This wrapper re-exports it typed so
 * consumers can keep `import { models } from './lovable-gateway.models'`.
 *
 * The data is loaded via `JSON.parse(readFileSync(...))` rather than an
 * `import ... with { type: 'json' }` attribute so the loader doesn't have
 * to support JSON import attributes.
 */

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export interface LovableGatewayCatalogModel {
  id: string
  object?: string
  created?: number
  released?: number
  expiration_date?: number | null
  owned_by?: string
  name?: string
  description?: string
  context_window?: number
  max_tokens?: number
  knowledge?: string
  modalities?: {
    input?: Array<string>
    output?: Array<string>
  }
  [key: string]: unknown
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const DATA_PATH = resolve(__dirname, 'lovable-gateway.models.json')

export const models: Array<LovableGatewayCatalogModel> = JSON.parse(
  readFileSync(DATA_PATH, 'utf-8'),
)
