// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const CreateImageEditRequestSchema = {
  type: 'object',
  properties: {
    image: {
      anyOf: [
        { type: 'string', format: 'binary' },
        {
          type: 'array',
          maxItems: 16,
          items: { type: 'string', format: 'binary' },
        },
      ],
      description:
        'The image(s) to edit. Must be a supported image file or an array of images.\n\nFor the GPT image models (`gpt-image-1`, `gpt-image-1-mini`, and `gpt-image-1.5`), each image should be a `png`, `webp`, or `jpg`\nfile less than 50MB. You can provide up to 16 images.\n`chatgpt-image-latest` follows the same input constraints as GPT image models.\n\nFor `dall-e-2`, you can only provide one image, and it should be a square\n`png` file less than 4MB.\n',
    },
    prompt: {
      description:
        'A text description of the desired image(s). The maximum length is 1000 characters for `dall-e-2`, and 32000 characters for the GPT image models.',
      type: 'string',
      example: 'A cute baby sea otter wearing a beret',
    },
    mask: {
      description:
        'An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. If there are multiple images provided, the mask will be applied on the first image. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`.',
      type: 'string',
      format: 'binary',
    },
    background: {
      type: 'string',
      enum: ['transparent', 'opaque', 'auto'],
      default: 'auto',
      example: 'transparent',
      nullable: true,
      description:
        'Allows to set transparency for the background of the generated image(s).\nThis parameter is only supported for the GPT image models. Must be one of\n`transparent`, `opaque` or `auto` (default value). When `auto` is used, the\nmodel will automatically determine the best background for the image.\n\nIf `transparent`, the output format needs to support transparency, so it\nshould be set to either `png` (default value) or `webp`.\n',
    },
    model: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'gpt-image-1.5',
            'dall-e-2',
            'gpt-image-1',
            'gpt-image-1-mini',
            'chatgpt-image-latest',
          ],
          'x-stainless-const': true,
        },
      ],
      'x-oaiTypeLabel': 'string',
      default: 'gpt-image-1.5',
      example: 'gpt-image-1.5',
      nullable: true,
      description:
        'The model to use for image generation. Defaults to `gpt-image-1.5`.',
    },
    n: {
      type: 'integer',
      minimum: 1,
      maximum: 10,
      default: 1,
      example: 1,
      nullable: true,
      description:
        'The number of images to generate. Must be between 1 and 10.',
    },
    size: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            '256x256',
            '512x512',
            '1024x1024',
            '1536x1024',
            '1024x1536',
            'auto',
          ],
        },
      ],
      default: '1024x1024',
      example: '1024x1024',
      nullable: true,
      description:
        "The size of the generated images. For `gpt-image-2` and `gpt-image-2-2026-04-21`, arbitrary resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`. Width and height must both be divisible by 16 and the requested aspect ratio must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and the maximum supported resolution is `3840x2160`. The requested size must also satisfy the model's current pixel and edge limits. The standard sizes `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models; `auto` is supported for models that allow automatic sizing. For `dall-e-2`, use one of `256x256`, `512x512`, or `1024x1024`. For `dall-e-3`, use one of `1024x1024`, `1792x1024`, or `1024x1792`.",
    },
    response_format: {
      type: 'string',
      enum: ['url', 'b64_json'],
      example: 'url',
      nullable: true,
      description:
        'The format in which the generated images are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter is only supported for `dall-e-2` (default is `url` for `dall-e-2`), as GPT image models always return base64-encoded images.',
    },
    output_format: {
      type: 'string',
      enum: ['png', 'jpeg', 'webp'],
      default: 'png',
      example: 'png',
      nullable: true,
      description:
        'The format in which the generated images are returned. This parameter is\nonly supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.\nThe default value is `png`.\n',
    },
    output_compression: {
      type: 'integer',
      default: 100,
      example: 100,
      nullable: true,
      description:
        'The compression level (0-100%) for the generated images. This parameter\nis only supported for the GPT image models with the `webp` or `jpeg` output\nformats, and defaults to 100.\n',
    },
    user: {
      type: 'string',
      example: 'user-1234',
      description:
        'A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).\n',
    },
    input_fidelity: {
      anyOf: [{ $ref: '#/$defs/InputFidelity' }, { type: 'null' }],
    },
    stream: {
      type: 'boolean',
      default: false,
      example: false,
      nullable: true,
      description:
        'Edit the image in streaming mode. Defaults to `false`. See the\n[Image generation guide](/docs/guides/image-generation) for more information.\n',
    },
    partial_images: { $ref: '#/$defs/PartialImages' },
    quality: {
      type: 'string',
      enum: ['standard', 'low', 'medium', 'high', 'auto'],
      default: 'auto',
      example: 'high',
      nullable: true,
      description:
        'The quality of the image that will be generated for GPT image models. Defaults to `auto`.\n',
    },
  },
  required: ['prompt', 'image'],
  $defs: {
    InputFidelity: {
      type: 'string',
      enum: ['high', 'low'],
      description:
        'Control how much effort the model will exert to match the style and features, especially facial features, of input images. This parameter is only supported for `gpt-image-1` and `gpt-image-1.5` and later models, unsupported for `gpt-image-1-mini`. Supports `high` and `low`. Defaults to `low`.',
    },
    PartialImages: {
      anyOf: [
        {
          type: 'integer',
          maximum: 3,
          minimum: 0,
          default: 0,
          example: 1,
          description:
            'The number of partial images to generate. This parameter is used for\nstreaming responses that return partial images. Value must be between 0 and 3.\nWhen set to 0, the response will be a single image sent in one streaming event.\n\nNote that the final image may be sent before the full number of partial images\nare generated if the full image is generated more quickly.\n',
        },
        { type: 'null' },
      ],
    },
  },
} as const

export const CreateImageRequestSchema = {
  type: 'object',
  properties: {
    prompt: {
      description:
        'A text description of the desired image(s). The maximum length is 32000 characters for the GPT image models, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.',
      type: 'string',
      example: 'A cute baby sea otter',
    },
    model: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'gpt-image-1.5',
            'dall-e-2',
            'dall-e-3',
            'gpt-image-1',
            'gpt-image-1-mini',
          ],
        },
      ],
      'x-oaiTypeLabel': 'string',
      default: 'dall-e-2',
      example: 'gpt-image-1.5',
      nullable: true,
      description:
        'The model to use for image generation. One of `dall-e-2`, `dall-e-3`, or a GPT image model (`gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`). Defaults to `dall-e-2` unless a parameter specific to the GPT image models is used.',
    },
    n: {
      type: 'integer',
      minimum: 1,
      maximum: 10,
      default: 1,
      example: 1,
      nullable: true,
      description:
        'The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.',
    },
    quality: {
      type: 'string',
      enum: ['standard', 'hd', 'low', 'medium', 'high', 'auto'],
      default: 'auto',
      example: 'medium',
      nullable: true,
      description:
        'The quality of the image that will be generated.\n\n- `auto` (default value) will automatically select the best quality for the given model.\n- `high`, `medium` and `low` are supported for the GPT image models.\n- `hd` and `standard` are supported for `dall-e-3`.\n- `standard` is the only option for `dall-e-2`.\n',
    },
    response_format: {
      type: 'string',
      enum: ['url', 'b64_json'],
      default: 'url',
      example: 'url',
      nullable: true,
      description:
        "The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for the GPT image models, which always return base64-encoded images.",
    },
    output_format: {
      type: 'string',
      enum: ['png', 'jpeg', 'webp'],
      default: 'png',
      example: 'png',
      nullable: true,
      description:
        'The format in which the generated images are returned. This parameter is only supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.',
    },
    output_compression: {
      type: 'integer',
      default: 100,
      example: 100,
      nullable: true,
      description:
        'The compression level (0-100%) for the generated images. This parameter is only supported for the GPT image models with the `webp` or `jpeg` output formats, and defaults to 100.',
    },
    stream: {
      type: 'boolean',
      default: false,
      example: false,
      nullable: true,
      description:
        'Generate the image in streaming mode. Defaults to `false`. See the\n[Image generation guide](/docs/guides/image-generation) for more information.\nThis parameter is only supported for the GPT image models.\n',
    },
    partial_images: { $ref: '#/$defs/PartialImages' },
    size: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'auto',
            '1024x1024',
            '1536x1024',
            '1024x1536',
            '256x256',
            '512x512',
            '1792x1024',
            '1024x1792',
          ],
        },
      ],
      default: 'auto',
      example: '1024x1024',
      nullable: true,
      description:
        "The size of the generated images. For `gpt-image-2` and `gpt-image-2-2026-04-21`, arbitrary resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`. Width and height must both be divisible by 16 and the requested aspect ratio must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and the maximum supported resolution is `3840x2160`. The requested size must also satisfy the model's current pixel and edge limits. The standard sizes `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models; `auto` is supported for models that allow automatic sizing. For `dall-e-2`, use one of `256x256`, `512x512`, or `1024x1024`. For `dall-e-3`, use one of `1024x1024`, `1792x1024`, or `1024x1792`.",
    },
    moderation: {
      type: 'string',
      enum: ['low', 'auto'],
      default: 'auto',
      example: 'low',
      nullable: true,
      description:
        'Control the content-moderation level for images generated by the GPT image models. Must be either `low` for less restrictive filtering or `auto` (default value).',
    },
    background: {
      type: 'string',
      enum: ['transparent', 'opaque', 'auto'],
      default: 'auto',
      example: 'transparent',
      nullable: true,
      description:
        'Allows to set transparency for the background of the generated image(s).\nThis parameter is only supported for the GPT image models. Must be one of\n`transparent`, `opaque` or `auto` (default value). When `auto` is used, the\nmodel will automatically determine the best background for the image.\n\nIf `transparent`, the output format needs to support transparency, so it\nshould be set to either `png` (default value) or `webp`.\n',
    },
    style: {
      type: 'string',
      enum: ['vivid', 'natural'],
      default: 'vivid',
      example: 'vivid',
      nullable: true,
      description:
        'The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.',
    },
    user: {
      type: 'string',
      example: 'user-1234',
      description:
        'A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).\n',
    },
  },
  required: ['prompt'],
  $defs: {
    PartialImages: {
      anyOf: [
        {
          type: 'integer',
          maximum: 3,
          minimum: 0,
          default: 0,
          example: 1,
          description:
            'The number of partial images to generate. This parameter is used for\nstreaming responses that return partial images. Value must be between 0 and 3.\nWhen set to 0, the response will be a single image sent in one streaming event.\n\nNote that the final image may be sent before the full number of partial images\nare generated if the full image is generated more quickly.\n',
        },
        { type: 'null' },
      ],
    },
  },
} as const

export const CreateImageVariationRequestSchema = {
  type: 'object',
  properties: {
    image: {
      description:
        'The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square.',
      type: 'string',
      format: 'binary',
    },
    model: {
      anyOf: [
        { type: 'string' },
        { type: 'string', enum: ['dall-e-2'], 'x-stainless-const': true },
      ],
      'x-oaiTypeLabel': 'string',
      default: 'dall-e-2',
      example: 'dall-e-2',
      nullable: true,
      description:
        'The model to use for image generation. Only `dall-e-2` is supported at this time.',
    },
    n: {
      type: 'integer',
      minimum: 1,
      maximum: 10,
      default: 1,
      example: 1,
      nullable: true,
      description:
        'The number of images to generate. Must be between 1 and 10.',
    },
    response_format: {
      type: 'string',
      enum: ['url', 'b64_json'],
      default: 'url',
      example: 'url',
      nullable: true,
      description:
        'The format in which the generated images are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated.',
    },
    size: {
      type: 'string',
      enum: ['256x256', '512x512', '1024x1024'],
      default: '1024x1024',
      example: '1024x1024',
      nullable: true,
      description:
        'The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.',
    },
    user: {
      type: 'string',
      example: 'user-1234',
      description:
        'A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids).\n',
    },
  },
  required: ['image'],
} as const

export const EditImageBodyJsonParamSchema = {
  type: 'object',
  description:
    'JSON request body for image edits.\n\nUse `images` (array of `ImageRefParam`) instead of multipart `image` uploads.\nYou can reference images via external URLs, data URLs, or uploaded file IDs.\nJSON edits support GPT image models only; DALL-E edits require multipart (`dall-e-2` only).\n',
  properties: {
    model: {
      anyOf: [
        { type: 'string' },
        {
          type: 'string',
          enum: [
            'gpt-image-1.5',
            'gpt-image-1',
            'gpt-image-1-mini',
            'chatgpt-image-latest',
          ],
        },
        { type: 'null' },
      ],
      'x-oaiTypeLabel': 'string',
      default: 'gpt-image-1.5',
      example: 'gpt-image-1.5',
      description: 'The model to use for image editing.',
    },
    images: {
      type: 'array',
      minItems: 1,
      maxItems: 16,
      description:
        'Input image references to edit.\nFor GPT image models, you can provide up to 16 images.\n',
      items: { $ref: '#/$defs/ImageRefParam' },
    },
    mask: { $ref: '#/$defs/ImageRefParam' },
    prompt: {
      type: 'string',
      minLength: 1,
      maxLength: 32000,
      example: 'Add a watercolor effect and keep the subject centered',
      description: 'A text description of the desired image edit.',
    },
    n: {
      anyOf: [{ type: 'integer', minimum: 1, maximum: 10 }, { type: 'null' }],
      default: 1,
      example: 1,
      description: 'The number of edited images to generate.',
    },
    quality: {
      anyOf: [
        { type: 'string', enum: ['low', 'medium', 'high', 'auto'] },
        { type: 'null' },
      ],
      default: 'auto',
      example: 'high',
      description: 'Output quality for GPT image models.\n',
    },
    input_fidelity: {
      anyOf: [{ type: 'string', enum: ['high', 'low'] }, { type: 'null' }],
      description: 'Controls fidelity to the original input image(s).',
    },
    size: {
      anyOf: [
        {
          type: 'string',
          enum: ['auto', '1024x1024', '1536x1024', '1024x1536'],
        },
        { type: 'null' },
      ],
      default: 'auto',
      example: '1024x1024',
      description: 'Requested output image size.',
    },
    user: {
      type: 'string',
      example: 'user-1234',
      description:
        'A unique identifier representing your end-user, which can help OpenAI\nmonitor and detect abuse.\n',
    },
    output_format: {
      anyOf: [
        { type: 'string', enum: ['png', 'jpeg', 'webp'] },
        { type: 'null' },
      ],
      default: 'png',
      example: 'png',
      description: 'Output image format. Supported for GPT image models.',
    },
    output_compression: {
      anyOf: [{ type: 'integer', minimum: 0, maximum: 100 }, { type: 'null' }],
      example: 100,
      description: 'Compression level for `jpeg` or `webp` output.',
    },
    moderation: {
      anyOf: [{ type: 'string', enum: ['low', 'auto'] }, { type: 'null' }],
      default: 'auto',
      example: 'auto',
      description: 'Moderation level for GPT image models.',
    },
    background: {
      anyOf: [
        { type: 'string', enum: ['transparent', 'opaque', 'auto'] },
        { type: 'null' },
      ],
      default: 'auto',
      example: 'transparent',
      description: 'Background behavior for generated image output.',
    },
    stream: {
      anyOf: [{ type: 'boolean' }, { type: 'null' }],
      default: false,
      example: false,
      description: 'Stream partial image results as events.',
    },
    partial_images: { $ref: '#/$defs/PartialImages' },
  },
  required: ['images', 'prompt'],
  $defs: {
    ImageRefParam: {
      type: 'object',
      description:
        'Reference an input image by either URL or uploaded file ID.\nProvide exactly one of `image_url` or `file_id`.\n',
      properties: {
        image_url: {
          type: 'string',
          format: 'uri',
          maxLength: 20971520,
          description: 'A fully qualified URL or base64-encoded data URL.',
          example: 'https://example.com/source-image.png',
        },
        file_id: {
          type: 'string',
          description: 'The File API ID of an uploaded image to use as input.',
          example: 'file-abc123',
        },
      },
      anyOf: [{ required: ['image_url'] }, { required: ['file_id'] }],
      not: { required: ['image_url', 'file_id'] },
      additionalProperties: false,
    },
    PartialImages: {
      anyOf: [
        {
          type: 'integer',
          maximum: 3,
          minimum: 0,
          default: 0,
          example: 1,
          description:
            'The number of partial images to generate. This parameter is used for\nstreaming responses that return partial images. Value must be between 0 and 3.\nWhen set to 0, the response will be a single image sent in one streaming event.\n\nNote that the final image may be sent before the full number of partial images\nare generated if the full image is generated more quickly.\n',
        },
        { type: 'null' },
      ],
    },
  },
} as const

export const ImageSchema = {
  type: 'object',
  description:
    'Represents the content or the URL of an image generated by the OpenAI API.',
  properties: {
    b64_json: {
      type: 'string',
      description:
        'The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.',
    },
    url: {
      type: 'string',
      format: 'uri',
      description:
        'When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for the GPT image models.',
    },
    revised_prompt: {
      type: 'string',
      description:
        'For `dall-e-3` only, the revised prompt that was used to generate the image.',
    },
  },
} as const

export const ImageEditCompletedEventSchema = {
  type: 'object',
  description:
    'Emitted when image editing has completed and the final image is available.\n',
  properties: {
    type: {
      type: 'string',
      description: 'The type of the event. Always `image_edit.completed`.\n',
      enum: ['image_edit.completed'],
      'x-stainless-const': true,
    },
    b64_json: {
      type: 'string',
      description:
        'Base64-encoded final edited image data, suitable for rendering as an image.\n',
    },
    created_at: {
      type: 'integer',
      format: 'unixtime',
      description: 'The Unix timestamp when the event was created.\n',
    },
    size: {
      type: 'string',
      description: 'The size of the edited image.\n',
      enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
    },
    quality: {
      type: 'string',
      description: 'The quality setting for the edited image.\n',
      enum: ['low', 'medium', 'high', 'auto'],
    },
    background: {
      type: 'string',
      description: 'The background setting for the edited image.\n',
      enum: ['transparent', 'opaque', 'auto'],
    },
    output_format: {
      type: 'string',
      description: 'The output format for the edited image.\n',
      enum: ['png', 'webp', 'jpeg'],
    },
    usage: { $ref: '#/$defs/ImagesUsage' },
  },
  required: [
    'type',
    'b64_json',
    'created_at',
    'size',
    'quality',
    'background',
    'output_format',
    'usage',
  ],
  'x-oaiMeta': {
    name: 'image_edit.completed',
    group: 'images',
    example:
      '{\n  "type": "image_edit.completed",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "usage": {\n    "total_tokens": 100,\n    "input_tokens": 50,\n    "output_tokens": 50,\n    "input_tokens_details": {\n      "text_tokens": 10,\n      "image_tokens": 40\n    }\n  }\n}\n',
  },
  $defs: {
    ImagesUsage: {
      type: 'object',
      description:
        'For the GPT image models only, the token usage information for the image generation.\n',
      required: [
        'total_tokens',
        'input_tokens',
        'output_tokens',
        'input_tokens_details',
      ],
      properties: {
        total_tokens: {
          type: 'integer',
          description:
            'The total number of tokens (images and text) used for the image generation.\n',
        },
        input_tokens: {
          type: 'integer',
          description:
            'The number of tokens (images and text) in the input prompt.',
        },
        output_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the output image.',
        },
        input_tokens_details: {
          type: 'object',
          description:
            'The input tokens detailed information for the image generation.',
          required: ['text_tokens', 'image_tokens'],
          properties: {
            text_tokens: {
              type: 'integer',
              description: 'The number of text tokens in the input prompt.',
            },
            image_tokens: {
              type: 'integer',
              description: 'The number of image tokens in the input prompt.',
            },
          },
        },
      },
    },
  },
} as const

export const ImageEditPartialImageEventSchema = {
  type: 'object',
  description:
    'Emitted when a partial image is available during image editing streaming.\n',
  properties: {
    type: {
      type: 'string',
      description:
        'The type of the event. Always `image_edit.partial_image`.\n',
      enum: ['image_edit.partial_image'],
      'x-stainless-const': true,
    },
    b64_json: {
      type: 'string',
      description:
        'Base64-encoded partial image data, suitable for rendering as an image.\n',
    },
    created_at: {
      type: 'integer',
      format: 'unixtime',
      description: 'The Unix timestamp when the event was created.\n',
    },
    size: {
      type: 'string',
      description: 'The size of the requested edited image.\n',
      enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
    },
    quality: {
      type: 'string',
      description: 'The quality setting for the requested edited image.\n',
      enum: ['low', 'medium', 'high', 'auto'],
    },
    background: {
      type: 'string',
      description: 'The background setting for the requested edited image.\n',
      enum: ['transparent', 'opaque', 'auto'],
    },
    output_format: {
      type: 'string',
      description: 'The output format for the requested edited image.\n',
      enum: ['png', 'webp', 'jpeg'],
    },
    partial_image_index: {
      type: 'integer',
      description: '0-based index for the partial image (streaming).\n',
    },
  },
  required: [
    'type',
    'b64_json',
    'created_at',
    'size',
    'quality',
    'background',
    'output_format',
    'partial_image_index',
  ],
  'x-oaiMeta': {
    name: 'image_edit.partial_image',
    group: 'images',
    example:
      '{\n  "type": "image_edit.partial_image",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "partial_image_index": 0\n}\n',
  },
} as const

export const ImageEditStreamEventSchema = {
  anyOf: [
    { $ref: '#/$defs/ImageEditPartialImageEvent' },
    { $ref: '#/$defs/ImageEditCompletedEvent' },
  ],
  discriminator: { propertyName: 'type' },
  $defs: {
    ImageEditCompletedEvent: {
      type: 'object',
      description:
        'Emitted when image editing has completed and the final image is available.\n',
      properties: {
        type: {
          type: 'string',
          description:
            'The type of the event. Always `image_edit.completed`.\n',
          enum: ['image_edit.completed'],
          'x-stainless-const': true,
        },
        b64_json: {
          type: 'string',
          description:
            'Base64-encoded final edited image data, suitable for rendering as an image.\n',
        },
        created_at: {
          type: 'integer',
          format: 'unixtime',
          description: 'The Unix timestamp when the event was created.\n',
        },
        size: {
          type: 'string',
          description: 'The size of the edited image.\n',
          enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
        },
        quality: {
          type: 'string',
          description: 'The quality setting for the edited image.\n',
          enum: ['low', 'medium', 'high', 'auto'],
        },
        background: {
          type: 'string',
          description: 'The background setting for the edited image.\n',
          enum: ['transparent', 'opaque', 'auto'],
        },
        output_format: {
          type: 'string',
          description: 'The output format for the edited image.\n',
          enum: ['png', 'webp', 'jpeg'],
        },
        usage: { $ref: '#/$defs/ImagesUsage' },
      },
      required: [
        'type',
        'b64_json',
        'created_at',
        'size',
        'quality',
        'background',
        'output_format',
        'usage',
      ],
      'x-oaiMeta': {
        name: 'image_edit.completed',
        group: 'images',
        example:
          '{\n  "type": "image_edit.completed",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "usage": {\n    "total_tokens": 100,\n    "input_tokens": 50,\n    "output_tokens": 50,\n    "input_tokens_details": {\n      "text_tokens": 10,\n      "image_tokens": 40\n    }\n  }\n}\n',
      },
    },
    ImageEditPartialImageEvent: {
      type: 'object',
      description:
        'Emitted when a partial image is available during image editing streaming.\n',
      properties: {
        type: {
          type: 'string',
          description:
            'The type of the event. Always `image_edit.partial_image`.\n',
          enum: ['image_edit.partial_image'],
          'x-stainless-const': true,
        },
        b64_json: {
          type: 'string',
          description:
            'Base64-encoded partial image data, suitable for rendering as an image.\n',
        },
        created_at: {
          type: 'integer',
          format: 'unixtime',
          description: 'The Unix timestamp when the event was created.\n',
        },
        size: {
          type: 'string',
          description: 'The size of the requested edited image.\n',
          enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
        },
        quality: {
          type: 'string',
          description: 'The quality setting for the requested edited image.\n',
          enum: ['low', 'medium', 'high', 'auto'],
        },
        background: {
          type: 'string',
          description:
            'The background setting for the requested edited image.\n',
          enum: ['transparent', 'opaque', 'auto'],
        },
        output_format: {
          type: 'string',
          description: 'The output format for the requested edited image.\n',
          enum: ['png', 'webp', 'jpeg'],
        },
        partial_image_index: {
          type: 'integer',
          description: '0-based index for the partial image (streaming).\n',
        },
      },
      required: [
        'type',
        'b64_json',
        'created_at',
        'size',
        'quality',
        'background',
        'output_format',
        'partial_image_index',
      ],
      'x-oaiMeta': {
        name: 'image_edit.partial_image',
        group: 'images',
        example:
          '{\n  "type": "image_edit.partial_image",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "partial_image_index": 0\n}\n',
      },
    },
    ImagesUsage: {
      type: 'object',
      description:
        'For the GPT image models only, the token usage information for the image generation.\n',
      required: [
        'total_tokens',
        'input_tokens',
        'output_tokens',
        'input_tokens_details',
      ],
      properties: {
        total_tokens: {
          type: 'integer',
          description:
            'The total number of tokens (images and text) used for the image generation.\n',
        },
        input_tokens: {
          type: 'integer',
          description:
            'The number of tokens (images and text) in the input prompt.',
        },
        output_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the output image.',
        },
        input_tokens_details: {
          type: 'object',
          description:
            'The input tokens detailed information for the image generation.',
          required: ['text_tokens', 'image_tokens'],
          properties: {
            text_tokens: {
              type: 'integer',
              description: 'The number of text tokens in the input prompt.',
            },
            image_tokens: {
              type: 'integer',
              description: 'The number of image tokens in the input prompt.',
            },
          },
        },
      },
    },
  },
} as const

export const ImageGenCompletedEventSchema = {
  type: 'object',
  description:
    'Emitted when image generation has completed and the final image is available.\n',
  properties: {
    type: {
      type: 'string',
      description:
        'The type of the event. Always `image_generation.completed`.\n',
      enum: ['image_generation.completed'],
      'x-stainless-const': true,
    },
    b64_json: {
      type: 'string',
      description:
        'Base64-encoded image data, suitable for rendering as an image.\n',
    },
    created_at: {
      type: 'integer',
      format: 'unixtime',
      description: 'The Unix timestamp when the event was created.\n',
    },
    size: {
      type: 'string',
      description: 'The size of the generated image.\n',
      enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
    },
    quality: {
      type: 'string',
      description: 'The quality setting for the generated image.\n',
      enum: ['low', 'medium', 'high', 'auto'],
    },
    background: {
      type: 'string',
      description: 'The background setting for the generated image.\n',
      enum: ['transparent', 'opaque', 'auto'],
    },
    output_format: {
      type: 'string',
      description: 'The output format for the generated image.\n',
      enum: ['png', 'webp', 'jpeg'],
    },
    usage: { $ref: '#/$defs/ImagesUsage' },
  },
  required: [
    'type',
    'b64_json',
    'created_at',
    'size',
    'quality',
    'background',
    'output_format',
    'usage',
  ],
  'x-oaiMeta': {
    name: 'image_generation.completed',
    group: 'images',
    example:
      '{\n  "type": "image_generation.completed",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "usage": {\n    "total_tokens": 100,\n    "input_tokens": 50,\n    "output_tokens": 50,\n    "input_tokens_details": {\n      "text_tokens": 10,\n      "image_tokens": 40\n    }\n  }\n}\n',
  },
  $defs: {
    ImagesUsage: {
      type: 'object',
      description:
        'For the GPT image models only, the token usage information for the image generation.\n',
      required: [
        'total_tokens',
        'input_tokens',
        'output_tokens',
        'input_tokens_details',
      ],
      properties: {
        total_tokens: {
          type: 'integer',
          description:
            'The total number of tokens (images and text) used for the image generation.\n',
        },
        input_tokens: {
          type: 'integer',
          description:
            'The number of tokens (images and text) in the input prompt.',
        },
        output_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the output image.',
        },
        input_tokens_details: {
          type: 'object',
          description:
            'The input tokens detailed information for the image generation.',
          required: ['text_tokens', 'image_tokens'],
          properties: {
            text_tokens: {
              type: 'integer',
              description: 'The number of text tokens in the input prompt.',
            },
            image_tokens: {
              type: 'integer',
              description: 'The number of image tokens in the input prompt.',
            },
          },
        },
      },
    },
  },
} as const

export const ImageGenInputUsageDetailsSchema = {
  properties: {
    text_tokens: {
      type: 'integer',
      description: 'The number of text tokens in the input prompt.',
    },
    image_tokens: {
      type: 'integer',
      description: 'The number of image tokens in the input prompt.',
    },
  },
  type: 'object',
  required: ['text_tokens', 'image_tokens'],
  title: 'Input usage details',
  description:
    'The input tokens detailed information for the image generation.',
} as const

export const ImageGenOutputTokensDetailsSchema = {
  properties: {
    image_tokens: {
      type: 'integer',
      description: 'The number of image output tokens generated by the model.',
    },
    text_tokens: {
      type: 'integer',
      description: 'The number of text output tokens generated by the model.',
    },
  },
  type: 'object',
  required: ['image_tokens', 'text_tokens'],
  title: 'Image generation output token details',
  description: 'The output token details for the image generation.',
} as const

export const ImageGenPartialImageEventSchema = {
  type: 'object',
  description:
    'Emitted when a partial image is available during image generation streaming.\n',
  properties: {
    type: {
      type: 'string',
      description:
        'The type of the event. Always `image_generation.partial_image`.\n',
      enum: ['image_generation.partial_image'],
      'x-stainless-const': true,
    },
    b64_json: {
      type: 'string',
      description:
        'Base64-encoded partial image data, suitable for rendering as an image.\n',
    },
    created_at: {
      type: 'integer',
      format: 'unixtime',
      description: 'The Unix timestamp when the event was created.\n',
    },
    size: {
      type: 'string',
      description: 'The size of the requested image.\n',
      enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
    },
    quality: {
      type: 'string',
      description: 'The quality setting for the requested image.\n',
      enum: ['low', 'medium', 'high', 'auto'],
    },
    background: {
      type: 'string',
      description: 'The background setting for the requested image.\n',
      enum: ['transparent', 'opaque', 'auto'],
    },
    output_format: {
      type: 'string',
      description: 'The output format for the requested image.\n',
      enum: ['png', 'webp', 'jpeg'],
    },
    partial_image_index: {
      type: 'integer',
      description: '0-based index for the partial image (streaming).\n',
    },
  },
  required: [
    'type',
    'b64_json',
    'created_at',
    'size',
    'quality',
    'background',
    'output_format',
    'partial_image_index',
  ],
  'x-oaiMeta': {
    name: 'image_generation.partial_image',
    group: 'images',
    example:
      '{\n  "type": "image_generation.partial_image",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "partial_image_index": 0\n}\n',
  },
} as const

export const ImageGenStreamEventSchema = {
  anyOf: [
    { $ref: '#/$defs/ImageGenPartialImageEvent' },
    { $ref: '#/$defs/ImageGenCompletedEvent' },
  ],
  discriminator: { propertyName: 'type' },
  $defs: {
    ImageGenCompletedEvent: {
      type: 'object',
      description:
        'Emitted when image generation has completed and the final image is available.\n',
      properties: {
        type: {
          type: 'string',
          description:
            'The type of the event. Always `image_generation.completed`.\n',
          enum: ['image_generation.completed'],
          'x-stainless-const': true,
        },
        b64_json: {
          type: 'string',
          description:
            'Base64-encoded image data, suitable for rendering as an image.\n',
        },
        created_at: {
          type: 'integer',
          format: 'unixtime',
          description: 'The Unix timestamp when the event was created.\n',
        },
        size: {
          type: 'string',
          description: 'The size of the generated image.\n',
          enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
        },
        quality: {
          type: 'string',
          description: 'The quality setting for the generated image.\n',
          enum: ['low', 'medium', 'high', 'auto'],
        },
        background: {
          type: 'string',
          description: 'The background setting for the generated image.\n',
          enum: ['transparent', 'opaque', 'auto'],
        },
        output_format: {
          type: 'string',
          description: 'The output format for the generated image.\n',
          enum: ['png', 'webp', 'jpeg'],
        },
        usage: { $ref: '#/$defs/ImagesUsage' },
      },
      required: [
        'type',
        'b64_json',
        'created_at',
        'size',
        'quality',
        'background',
        'output_format',
        'usage',
      ],
      'x-oaiMeta': {
        name: 'image_generation.completed',
        group: 'images',
        example:
          '{\n  "type": "image_generation.completed",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "usage": {\n    "total_tokens": 100,\n    "input_tokens": 50,\n    "output_tokens": 50,\n    "input_tokens_details": {\n      "text_tokens": 10,\n      "image_tokens": 40\n    }\n  }\n}\n',
      },
    },
    ImageGenPartialImageEvent: {
      type: 'object',
      description:
        'Emitted when a partial image is available during image generation streaming.\n',
      properties: {
        type: {
          type: 'string',
          description:
            'The type of the event. Always `image_generation.partial_image`.\n',
          enum: ['image_generation.partial_image'],
          'x-stainless-const': true,
        },
        b64_json: {
          type: 'string',
          description:
            'Base64-encoded partial image data, suitable for rendering as an image.\n',
        },
        created_at: {
          type: 'integer',
          format: 'unixtime',
          description: 'The Unix timestamp when the event was created.\n',
        },
        size: {
          type: 'string',
          description: 'The size of the requested image.\n',
          enum: ['1024x1024', '1024x1536', '1536x1024', 'auto'],
        },
        quality: {
          type: 'string',
          description: 'The quality setting for the requested image.\n',
          enum: ['low', 'medium', 'high', 'auto'],
        },
        background: {
          type: 'string',
          description: 'The background setting for the requested image.\n',
          enum: ['transparent', 'opaque', 'auto'],
        },
        output_format: {
          type: 'string',
          description: 'The output format for the requested image.\n',
          enum: ['png', 'webp', 'jpeg'],
        },
        partial_image_index: {
          type: 'integer',
          description: '0-based index for the partial image (streaming).\n',
        },
      },
      required: [
        'type',
        'b64_json',
        'created_at',
        'size',
        'quality',
        'background',
        'output_format',
        'partial_image_index',
      ],
      'x-oaiMeta': {
        name: 'image_generation.partial_image',
        group: 'images',
        example:
          '{\n  "type": "image_generation.partial_image",\n  "b64_json": "...",\n  "created_at": 1620000000,\n  "size": "1024x1024",\n  "quality": "high",\n  "background": "transparent",\n  "output_format": "png",\n  "partial_image_index": 0\n}\n',
      },
    },
    ImagesUsage: {
      type: 'object',
      description:
        'For the GPT image models only, the token usage information for the image generation.\n',
      required: [
        'total_tokens',
        'input_tokens',
        'output_tokens',
        'input_tokens_details',
      ],
      properties: {
        total_tokens: {
          type: 'integer',
          description:
            'The total number of tokens (images and text) used for the image generation.\n',
        },
        input_tokens: {
          type: 'integer',
          description:
            'The number of tokens (images and text) in the input prompt.',
        },
        output_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the output image.',
        },
        input_tokens_details: {
          type: 'object',
          description:
            'The input tokens detailed information for the image generation.',
          required: ['text_tokens', 'image_tokens'],
          properties: {
            text_tokens: {
              type: 'integer',
              description: 'The number of text tokens in the input prompt.',
            },
            image_tokens: {
              type: 'integer',
              description: 'The number of image tokens in the input prompt.',
            },
          },
        },
      },
    },
  },
} as const

export const ImageGenUsageSchema = {
  properties: {
    input_tokens: {
      type: 'integer',
      description:
        'The number of tokens (images and text) in the input prompt.',
    },
    total_tokens: {
      type: 'integer',
      description:
        'The total number of tokens (images and text) used for the image generation.',
    },
    output_tokens: {
      type: 'integer',
      description: 'The number of output tokens generated by the model.',
    },
    output_tokens_details: { $ref: '#/$defs/ImageGenOutputTokensDetails' },
    input_tokens_details: { $ref: '#/$defs/ImageGenInputUsageDetails' },
  },
  type: 'object',
  required: [
    'input_tokens',
    'total_tokens',
    'output_tokens',
    'input_tokens_details',
  ],
  title: 'Image generation usage',
  description:
    'For `gpt-image-1` only, the token usage information for the image generation.',
  $defs: {
    ImageGenInputUsageDetails: {
      properties: {
        text_tokens: {
          type: 'integer',
          description: 'The number of text tokens in the input prompt.',
        },
        image_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the input prompt.',
        },
      },
      type: 'object',
      required: ['text_tokens', 'image_tokens'],
      title: 'Input usage details',
      description:
        'The input tokens detailed information for the image generation.',
    },
    ImageGenOutputTokensDetails: {
      properties: {
        image_tokens: {
          type: 'integer',
          description:
            'The number of image output tokens generated by the model.',
        },
        text_tokens: {
          type: 'integer',
          description:
            'The number of text output tokens generated by the model.',
        },
      },
      type: 'object',
      required: ['image_tokens', 'text_tokens'],
      title: 'Image generation output token details',
      description: 'The output token details for the image generation.',
    },
  },
} as const

export const ImageRefParamSchema = {
  type: 'object',
  description:
    'Reference an input image by either URL or uploaded file ID.\nProvide exactly one of `image_url` or `file_id`.\n',
  properties: {
    image_url: {
      type: 'string',
      format: 'uri',
      maxLength: 20971520,
      description: 'A fully qualified URL or base64-encoded data URL.',
      example: 'https://example.com/source-image.png',
    },
    file_id: {
      type: 'string',
      description: 'The File API ID of an uploaded image to use as input.',
      example: 'file-abc123',
    },
  },
  anyOf: [{ required: ['image_url'] }, { required: ['file_id'] }],
  not: { required: ['image_url', 'file_id'] },
  additionalProperties: false,
} as const

export const ImagesResponseSchema = {
  type: 'object',
  title: 'Image generation response',
  description: 'The response from the image generation endpoint.',
  properties: {
    created: {
      type: 'integer',
      format: 'unixtime',
      description:
        'The Unix timestamp (in seconds) of when the image was created.',
    },
    data: {
      type: 'array',
      description: 'The list of generated images.',
      items: { $ref: '#/$defs/Image' },
    },
    background: {
      type: 'string',
      description:
        'The background parameter used for the image generation. Either `transparent` or `opaque`.',
      enum: ['transparent', 'opaque'],
    },
    output_format: {
      type: 'string',
      description:
        'The output format of the image generation. Either `png`, `webp`, or `jpeg`.',
      enum: ['png', 'webp', 'jpeg'],
    },
    size: {
      type: 'string',
      description:
        'The size of the image generated. Either `1024x1024`, `1024x1536`, or `1536x1024`.',
      enum: ['1024x1024', '1024x1536', '1536x1024'],
    },
    quality: {
      type: 'string',
      description:
        'The quality of the image generated. Either `low`, `medium`, or `high`.',
      enum: ['low', 'medium', 'high'],
    },
    usage: { $ref: '#/$defs/ImageGenUsage' },
  },
  required: ['created'],
  'x-oaiMeta': {
    name: 'The image generation response',
    group: 'images',
    example:
      '{\n  "created": 1713833628,\n  "data": [\n    {\n      "b64_json": "..."\n    }\n  ],\n  "background": "transparent",\n  "output_format": "png",\n  "size": "1024x1024",\n  "quality": "high",\n  "usage": {\n    "total_tokens": 100,\n    "input_tokens": 50,\n    "output_tokens": 50,\n    "input_tokens_details": {\n      "text_tokens": 10,\n      "image_tokens": 40\n    }\n  }\n}\n',
  },
  $defs: {
    Image: {
      type: 'object',
      description:
        'Represents the content or the URL of an image generated by the OpenAI API.',
      properties: {
        b64_json: {
          type: 'string',
          description:
            'The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.',
        },
        url: {
          type: 'string',
          format: 'uri',
          description:
            'When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for the GPT image models.',
        },
        revised_prompt: {
          type: 'string',
          description:
            'For `dall-e-3` only, the revised prompt that was used to generate the image.',
        },
      },
    },
    ImageGenInputUsageDetails: {
      properties: {
        text_tokens: {
          type: 'integer',
          description: 'The number of text tokens in the input prompt.',
        },
        image_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the input prompt.',
        },
      },
      type: 'object',
      required: ['text_tokens', 'image_tokens'],
      title: 'Input usage details',
      description:
        'The input tokens detailed information for the image generation.',
    },
    ImageGenOutputTokensDetails: {
      properties: {
        image_tokens: {
          type: 'integer',
          description:
            'The number of image output tokens generated by the model.',
        },
        text_tokens: {
          type: 'integer',
          description:
            'The number of text output tokens generated by the model.',
        },
      },
      type: 'object',
      required: ['image_tokens', 'text_tokens'],
      title: 'Image generation output token details',
      description: 'The output token details for the image generation.',
    },
    ImageGenUsage: {
      properties: {
        input_tokens: {
          type: 'integer',
          description:
            'The number of tokens (images and text) in the input prompt.',
        },
        total_tokens: {
          type: 'integer',
          description:
            'The total number of tokens (images and text) used for the image generation.',
        },
        output_tokens: {
          type: 'integer',
          description: 'The number of output tokens generated by the model.',
        },
        output_tokens_details: { $ref: '#/$defs/ImageGenOutputTokensDetails' },
        input_tokens_details: { $ref: '#/$defs/ImageGenInputUsageDetails' },
      },
      type: 'object',
      required: [
        'input_tokens',
        'total_tokens',
        'output_tokens',
        'input_tokens_details',
      ],
      title: 'Image generation usage',
      description:
        'For `gpt-image-1` only, the token usage information for the image generation.',
    },
  },
} as const

export const ImagesUsageSchema = {
  type: 'object',
  description:
    'For the GPT image models only, the token usage information for the image generation.\n',
  required: [
    'total_tokens',
    'input_tokens',
    'output_tokens',
    'input_tokens_details',
  ],
  properties: {
    total_tokens: {
      type: 'integer',
      description:
        'The total number of tokens (images and text) used for the image generation.\n',
    },
    input_tokens: {
      type: 'integer',
      description:
        'The number of tokens (images and text) in the input prompt.',
    },
    output_tokens: {
      type: 'integer',
      description: 'The number of image tokens in the output image.',
    },
    input_tokens_details: {
      type: 'object',
      description:
        'The input tokens detailed information for the image generation.',
      required: ['text_tokens', 'image_tokens'],
      properties: {
        text_tokens: {
          type: 'integer',
          description: 'The number of text tokens in the input prompt.',
        },
        image_tokens: {
          type: 'integer',
          description: 'The number of image tokens in the input prompt.',
        },
      },
    },
  },
} as const

export const InputFidelitySchema = {
  type: 'string',
  enum: ['high', 'low'],
  description:
    'Control how much effort the model will exert to match the style and features, especially facial features, of input images. This parameter is only supported for `gpt-image-1` and `gpt-image-1.5` and later models, unsupported for `gpt-image-1-mini`. Supports `high` and `low`. Defaults to `low`.',
} as const

export const PartialImagesSchema = {
  anyOf: [
    {
      type: 'integer',
      maximum: 3,
      minimum: 0,
      default: 0,
      example: 1,
      description:
        'The number of partial images to generate. This parameter is used for\nstreaming responses that return partial images. Value must be between 0 and 3.\nWhen set to 0, the response will be a single image sent in one streaming event.\n\nNote that the final image may be sent before the full number of partial images\nare generated if the full image is generated more quickly.\n',
    },
    { type: 'null' },
  ],
} as const
