// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zCreateImageVariationRequest = z.object({
  image: z.string(),
  model: z.union([z.string(), z.enum(['dall-e-2'])]).nullish(),
  n: z.int().gte(1).lte(10).nullish().default(1),
  response_format: z.enum(['url', 'b64_json']).optional().default('url'),
  size: z
    .enum(['256x256', '512x512', '1024x1024'])
    .optional()
    .default('1024x1024'),
  user: z.string().optional(),
})

/**
 * Represents the content or the URL of an image generated by the OpenAI API.
 */
export const zImage = z.object({
  b64_json: z.string().optional(),
  url: z.url().optional(),
  revised_prompt: z.string().optional(),
})

/**
 * Emitted when a partial image is available during image editing streaming.
 *
 */
export const zImageEditPartialImageEvent = z.object({
  type: z.enum(['image_edit.partial_image']),
  b64_json: z.string(),
  created_at: z.int(),
  size: z.enum(['1024x1024', '1024x1536', '1536x1024', 'auto']),
  quality: z.enum(['low', 'medium', 'high', 'auto']),
  background: z.enum(['transparent', 'opaque', 'auto']),
  output_format: z.enum(['png', 'webp', 'jpeg']),
  partial_image_index: z.int(),
})

/**
 * Input usage details
 *
 * The input tokens detailed information for the image generation.
 */
export const zImageGenInputUsageDetails = z.object({
  text_tokens: z.int(),
  image_tokens: z.int(),
})

/**
 * Image generation output token details
 *
 * The output token details for the image generation.
 */
export const zImageGenOutputTokensDetails = z.object({
  image_tokens: z.int(),
  text_tokens: z.int(),
})

/**
 * Emitted when a partial image is available during image generation streaming.
 *
 */
export const zImageGenPartialImageEvent = z.object({
  type: z.enum(['image_generation.partial_image']),
  b64_json: z.string(),
  created_at: z.int(),
  size: z.enum(['1024x1024', '1024x1536', '1536x1024', 'auto']),
  quality: z.enum(['low', 'medium', 'high', 'auto']),
  background: z.enum(['transparent', 'opaque', 'auto']),
  output_format: z.enum(['png', 'webp', 'jpeg']),
  partial_image_index: z.int(),
})

/**
 * Image generation usage
 *
 * For `gpt-image-1` only, the token usage information for the image generation.
 */
export const zImageGenUsage = z.object({
  input_tokens: z.int(),
  total_tokens: z.int(),
  output_tokens: z.int(),
  output_tokens_details: zImageGenOutputTokensDetails.optional(),
  input_tokens_details: zImageGenInputUsageDetails,
})

export const zImageRefParam = z.intersection(
  z.unknown(),
  z.object({
    image_url: z.url().max(20971520).optional(),
    file_id: z.string().optional(),
  }),
)

/**
 * Image generation response
 *
 * The response from the image generation endpoint.
 */
export const zImagesResponse = z.object({
  created: z.int(),
  data: z.array(zImage).optional(),
  background: z.enum(['transparent', 'opaque']).optional(),
  output_format: z.enum(['png', 'webp', 'jpeg']).optional(),
  size: z.enum(['1024x1024', '1024x1536', '1536x1024']).optional(),
  quality: z.enum(['low', 'medium', 'high']).optional(),
  usage: zImageGenUsage.optional(),
})

/**
 * For the GPT image models only, the token usage information for the image generation.
 *
 */
export const zImagesUsage = z.object({
  total_tokens: z.int(),
  input_tokens: z.int(),
  output_tokens: z.int(),
  input_tokens_details: z.object({
    text_tokens: z.int(),
    image_tokens: z.int(),
  }),
})

/**
 * Emitted when image editing has completed and the final image is available.
 *
 */
export const zImageEditCompletedEvent = z.object({
  type: z.enum(['image_edit.completed']),
  b64_json: z.string(),
  created_at: z.int(),
  size: z.enum(['1024x1024', '1024x1536', '1536x1024', 'auto']),
  quality: z.enum(['low', 'medium', 'high', 'auto']),
  background: z.enum(['transparent', 'opaque', 'auto']),
  output_format: z.enum(['png', 'webp', 'jpeg']),
  usage: zImagesUsage,
})

export const zImageEditStreamEvent = z.discriminatedUnion('type', [
  zImageEditPartialImageEvent,
  zImageEditCompletedEvent,
])

/**
 * Emitted when image generation has completed and the final image is available.
 *
 */
export const zImageGenCompletedEvent = z.object({
  type: z.enum(['image_generation.completed']),
  b64_json: z.string(),
  created_at: z.int(),
  size: z.enum(['1024x1024', '1024x1536', '1536x1024', 'auto']),
  quality: z.enum(['low', 'medium', 'high', 'auto']),
  background: z.enum(['transparent', 'opaque', 'auto']),
  output_format: z.enum(['png', 'webp', 'jpeg']),
  usage: zImagesUsage,
})

export const zImageGenStreamEvent = z.discriminatedUnion('type', [
  zImageGenPartialImageEvent,
  zImageGenCompletedEvent,
])

/**
 * Control how much effort the model will exert to match the style and features, especially facial features, of input images. This parameter is only supported for `gpt-image-1` and `gpt-image-1.5` and later models, unsupported for `gpt-image-1-mini`. Supports `high` and `low`. Defaults to `low`.
 */
export const zInputFidelity = z.enum(['high', 'low'])

export const zPartialImages = z.union([z.int().gte(0).lte(3), z.unknown()])

export const zCreateImageEditRequest = z.object({
  image: z.union([z.string(), z.array(z.string()).max(16)]),
  prompt: z.string(),
  mask: z.string().optional(),
  background: z
    .enum(['transparent', 'opaque', 'auto'])
    .optional()
    .default('auto'),
  model: z
    .union([
      z.string(),
      z.enum([
        'gpt-image-1.5',
        'dall-e-2',
        'gpt-image-1',
        'gpt-image-1-mini',
        'chatgpt-image-latest',
      ]),
    ])
    .nullish(),
  n: z.int().gte(1).lte(10).nullish().default(1),
  size: z
    .union([
      z.string(),
      z.enum([
        '256x256',
        '512x512',
        '1024x1024',
        '1536x1024',
        '1024x1536',
        'auto',
      ]),
    ])
    .nullish(),
  response_format: z.enum(['url', 'b64_json']).optional(),
  output_format: z.enum(['png', 'jpeg', 'webp']).optional().default('png'),
  output_compression: z.int().nullish().default(100),
  user: z.string().optional(),
  input_fidelity: z.union([zInputFidelity, z.unknown()]).optional(),
  stream: z.boolean().nullish().default(false),
  partial_images: zPartialImages.optional(),
  quality: z
    .enum(['standard', 'low', 'medium', 'high', 'auto'])
    .optional()
    .default('auto'),
})

export const zCreateImageRequest = z.object({
  prompt: z.string(),
  model: z
    .union([
      z.string(),
      z.enum([
        'gpt-image-1.5',
        'dall-e-2',
        'dall-e-3',
        'gpt-image-1',
        'gpt-image-1-mini',
      ]),
    ])
    .nullish(),
  n: z.int().gte(1).lte(10).nullish().default(1),
  quality: z
    .enum(['standard', 'hd', 'low', 'medium', 'high', 'auto'])
    .optional()
    .default('auto'),
  response_format: z.enum(['url', 'b64_json']).optional().default('url'),
  output_format: z.enum(['png', 'jpeg', 'webp']).optional().default('png'),
  output_compression: z.int().nullish().default(100),
  stream: z.boolean().nullish().default(false),
  partial_images: zPartialImages.optional(),
  size: z
    .union([
      z.string(),
      z.enum([
        'auto',
        '1024x1024',
        '1536x1024',
        '1024x1536',
        '256x256',
        '512x512',
        '1792x1024',
        '1024x1792',
      ]),
    ])
    .nullish(),
  moderation: z.enum(['low', 'auto']).optional().default('auto'),
  background: z
    .enum(['transparent', 'opaque', 'auto'])
    .optional()
    .default('auto'),
  style: z.enum(['vivid', 'natural']).optional().default('vivid'),
  user: z.string().optional(),
})

/**
 * JSON request body for image edits.
 *
 * Use `images` (array of `ImageRefParam`) instead of multipart `image` uploads.
 * You can reference images via external URLs, data URLs, or uploaded file IDs.
 * JSON edits support GPT image models only; DALL-E edits require multipart (`dall-e-2` only).
 *
 */
export const zEditImageBodyJsonParam = z.object({
  model: z
    .union([
      z.string(),
      z.enum([
        'gpt-image-1.5',
        'gpt-image-1',
        'gpt-image-1-mini',
        'chatgpt-image-latest',
      ]),
      z.unknown(),
    ])
    .optional(),
  images: z.array(zImageRefParam).min(1).max(16),
  mask: zImageRefParam.optional(),
  prompt: z.string().min(1).max(32000),
  n: z.union([z.int().gte(1).lte(10), z.unknown()]).optional(),
  quality: z
    .union([z.enum(['low', 'medium', 'high', 'auto']), z.unknown()])
    .optional(),
  input_fidelity: z.union([z.enum(['high', 'low']), z.unknown()]).optional(),
  size: z
    .union([
      z.enum(['auto', '1024x1024', '1536x1024', '1024x1536']),
      z.unknown(),
    ])
    .optional(),
  user: z.string().optional(),
  output_format: z
    .union([z.enum(['png', 'jpeg', 'webp']), z.unknown()])
    .optional(),
  output_compression: z
    .union([z.int().gte(0).lte(100), z.unknown()])
    .optional(),
  moderation: z.union([z.enum(['low', 'auto']), z.unknown()]).optional(),
  background: z
    .union([z.enum(['transparent', 'opaque', 'auto']), z.unknown()])
    .optional(),
  stream: z.union([z.boolean(), z.unknown()]).optional(),
  partial_images: zPartialImages.optional(),
})

export const zCreateImageEditBody = zEditImageBodyJsonParam

/**
 * OK
 */
export const zCreateImageEditResponse = zImagesResponse

export const zCreateImageBody = zCreateImageRequest

/**
 * OK
 */
export const zCreateImageResponse = zImagesResponse

export const zCreateImageVariationBody = zCreateImageVariationRequest

/**
 * OK
 */
export const zCreateImageVariationResponse = zImagesResponse
