/**
 * Drizzle-backed **state** persistence for TanStack AI.
 *
 * Two entry points, one `AIPersistence` contract:
 *
 * - {@link sqlPersistence} — batteries-included. Give it a `dialect` + `url` and
 *   it builds the database, applies the migrations bundled in `drizzle/`
 *   (generated by drizzle-kit), and returns a ready `AIPersistence`.
 * - {@link drizzlePersistence} — bring-your-own. Pass a Drizzle sqlite `db` you
 *   already constructed and migrated (via `drizzle-kit` against the exported
 *   {@link schema}); this just wires the stores over it.
 *
 * Locks are not part of the SQL schema — an in-memory lock is provided as a dev
 * default so the returned persistence is complete. Swap in a distributed lock
 * for multi-process deployments.
 */
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DatabaseSync } from 'node:sqlite'
import { drizzle } from 'drizzle-orm/sqlite-proxy'
import { InMemoryLockStore } from '@tanstack/ai'
import {
  createArtifactStore,
  createBlobStore,
  createInterruptStore,
  createMessageStore,
  createMetadataStore,
  createRunStore,
} from './stores'
import { schema } from './schema'
import type { DrizzleDb } from './stores'
import type { AIPersistence } from '@tanstack/ai-persistence'

export { schema }
export type { DrizzleDb } from './stores'
export * from './schema'

/** Wire the AIPersistence stores over an existing Drizzle sqlite database. */
export function drizzlePersistence(db: DrizzleDb): AIPersistence {
  return {
    stores: {
      messages: createMessageStore(db),
      runs: createRunStore(db),
      interrupts: createInterruptStore(db),
      metadata: createMetadataStore(db),
      artifacts: createArtifactStore(db),
      blobs: createBlobStore(db),
      locks: new InMemoryLockStore(),
    },
  }
}

export interface SqlPersistenceOptions {
  /**
   * SQL dialect. Only `'sqlite'` is bundled with batteries (migrations shipped
   * in `drizzle/`), so it is the sole accepted value and the default. For
   * `postgres`/`mysql`, construct your own Drizzle db and use
   * {@link drizzlePersistence} with migrations generated from the exported
   * {@link schema} — `sqlPersistence` cannot build those for you.
   */
  dialect?: 'sqlite'
  /** Database URL/path. For sqlite: `:memory:` or a file path (`file:` prefix optional). */
  url: string
  /** Apply the bundled migrations on construction (default false). */
  migrate?: boolean
}

/** Build an {@link AIPersistence} from a dialect + url, applying bundled migrations. */
export function sqlPersistence(opts: SqlPersistenceOptions): AIPersistence {
  // `dialect` is typed `'sqlite'` only, but guard at runtime so an untyped JS
  // caller passing another dialect fails loud instead of silently getting a
  // sqlite db.
  const dialect = opts.dialect ?? 'sqlite'
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  if (dialect !== 'sqlite') {
    throw new Error(
      `sqlPersistence bundles the sqlite dialect only; for '${dialect}' construct a Drizzle db yourself and use drizzlePersistence(db) with migrations generated from the exported schema.`,
    )
  }
  const sqlite = new DatabaseSync(normalizeSqliteUrl(opts.url))
  if (opts.migrate) applyBundledMigrations(sqlite)
  const db = drizzle((sql, params, method) => {
    const stmt = sqlite.prepare(sql)
    if (method === 'run') {
      stmt.run(...params)
      return Promise.resolve({ rows: [] })
    }
    if (method === 'get') {
      const row = stmt.get(...params)
      // The store impl only ever selects via `.all()`, so `get` is unused; a
      // missing row maps to an empty positional array either way.
      return Promise.resolve({ rows: row ? Object.values(row) : [] })
    }
    const rows = stmt.all(...params)
    return Promise.resolve({ rows: rows.map((row) => Object.values(row)) })
  })
  return drizzlePersistence(db)
}

function normalizeSqliteUrl(url: string): string {
  if (url === ':memory:') return url
  return url.startsWith('file:') ? url.slice('file:'.length) : url
}

interface MigrationJournal {
  entries?: Array<{ tag: string }>
}

/** Locate the bundled `drizzle/` migrations dir relative to this module (src or dist). */
function findMigrationsDir(): string {
  let dir = dirname(fileURLToPath(import.meta.url))
  for (let i = 0; i < 8; i++) {
    const candidate = join(dir, 'drizzle')
    if (existsSync(join(candidate, 'meta', '_journal.json'))) return candidate
    const parent = dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  throw new Error('Could not locate the bundled drizzle migrations directory.')
}

function applyBundledMigrations(sqlite: DatabaseSync): void {
  const migrationsDir = findMigrationsDir()
  const journal = JSON.parse(
    readFileSync(join(migrationsDir, 'meta', '_journal.json'), 'utf8'),
  ) as MigrationJournal
  sqlite.exec(
    'CREATE TABLE IF NOT EXISTS __drizzle_migrations (tag TEXT PRIMARY KEY, applied_at INTEGER NOT NULL)',
  )
  const appliedRows = sqlite
    .prepare('SELECT tag FROM __drizzle_migrations')
    .all() as Array<{ tag: string }>
  const applied = new Set(appliedRows.map((row) => row.tag))
  for (const entry of journal.entries ?? []) {
    if (applied.has(entry.tag)) continue
    const sql = readFileSync(join(migrationsDir, `${entry.tag}.sql`), 'utf8')
    sqlite.exec(sql)
    sqlite
      .prepare(
        'INSERT INTO __drizzle_migrations (tag, applied_at) VALUES (?, ?)',
      )
      .run(entry.tag, Date.now())
  }
}
